//! The engine's configuration as its virtual RDB$CONFIG answers it: read
//! from 6.0.0.2196 (`SELECT * FROM RDB$CONFIG`, natural order) - 70 rows,
//! none set in that server's firebird.conf, so every value is its default
//! and no source is named. Regenerate from the reference engine when it
//! changes; do not edit by hand.

/// One RDB$CONFIG row: id, name, value, default, is-set, source file.
pub struct ConfigRow {
    pub id: i32,
    pub name: &'static str,
    pub value: Option<&'static str>,
    pub default: Option<&'static str>,
    pub is_set: bool,
    pub source: Option<&'static str>,
}

/// The rows, in the engine's scan order.
pub const CONFIG: &[ConfigRow] = &[
    ConfigRow { id: 0, name: "TempBlockSize", value: Some("1048576"), default: Some("1048576"), is_set: false, source: None },
    ConfigRow { id: 1, name: "TempCacheLimit", value: Some("67108864"), default: Some("67108864"), is_set: false, source: None },
    ConfigRow { id: 2, name: "RemoteFileOpenAbility", value: Some("false"), default: Some("false"), is_set: false, source: None },
    ConfigRow { id: 3, name: "GuardianOption", value: Some("1"), default: Some("1"), is_set: false, source: None },
    ConfigRow { id: 4, name: "CpuAffinityMask", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 5, name: "TcpRemoteBufferSize", value: Some("8192"), default: Some("8192"), is_set: false, source: None },
    ConfigRow { id: 6, name: "TcpNoNagle", value: Some("true"), default: Some("true"), is_set: false, source: None },
    ConfigRow { id: 7, name: "DefaultDbCachePages", value: Some("2048"), default: Some("2048"), is_set: false, source: None },
    ConfigRow { id: 8, name: "ConnectionTimeout", value: Some("180"), default: Some("180"), is_set: false, source: None },
    ConfigRow { id: 9, name: "DummyPacketInterval", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 10, name: "DefaultTimeZone", value: None, default: None, is_set: false, source: None },
    ConfigRow { id: 11, name: "LockMemSize", value: Some("1048576"), default: Some("1048576"), is_set: false, source: None },
    ConfigRow { id: 12, name: "LockHashSlots", value: Some("8191"), default: Some("8191"), is_set: false, source: None },
    ConfigRow { id: 13, name: "LockAcquireSpins", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 14, name: "EventMemSize", value: Some("65536"), default: Some("65536"), is_set: false, source: None },
    ConfigRow { id: 15, name: "DeadlockTimeout", value: Some("10"), default: Some("10"), is_set: false, source: None },
    ConfigRow { id: 16, name: "RemoteServiceName", value: Some("gds_db"), default: Some("gds_db"), is_set: false, source: None },
    ConfigRow { id: 17, name: "RemoteServicePort", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 18, name: "RemoteServiceUnixSocket", value: None, default: None, is_set: false, source: None },
    ConfigRow { id: 19, name: "IpcName", value: Some("FirebirdIPI"), default: Some("FirebirdIPI"), is_set: false, source: None },
    ConfigRow { id: 20, name: "MaxUnflushedWrites", value: Some("-1"), default: Some("-1"), is_set: false, source: None },
    ConfigRow { id: 21, name: "MaxUnflushedWriteTime", value: Some("-1"), default: Some("-1"), is_set: false, source: None },
    ConfigRow { id: 22, name: "ProcessPriorityLevel", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 23, name: "RemoteAuxPort", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 24, name: "RemoteBindAddress", value: None, default: None, is_set: false, source: None },
    ConfigRow { id: 25, name: "ExternalFileAccess", value: Some("None"), default: Some("None"), is_set: false, source: None },
    ConfigRow { id: 26, name: "DatabaseAccess", value: Some("Full"), default: Some("Full"), is_set: false, source: None },
    ConfigRow { id: 27, name: "UdfAccess", value: Some("None"), default: Some("None"), is_set: false, source: None },
    ConfigRow { id: 28, name: "TempDirectories", value: None, default: None, is_set: false, source: None },
    ConfigRow { id: 29, name: "BugcheckAbort", value: Some("false"), default: Some("false"), is_set: false, source: None },
    ConfigRow { id: 30, name: "TraceDSQL", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 31, name: "LegacyHash", value: Some("true"), default: Some("true"), is_set: false, source: None },
    ConfigRow { id: 32, name: "GCPolicy", value: Some("combined"), default: Some("combined"), is_set: false, source: None },
    ConfigRow { id: 33, name: "DatabaseGrowthIncrement", value: Some("134217728"), default: Some("134217728"), is_set: false, source: None },
    ConfigRow { id: 34, name: "AuditTraceConfigFile", value: Some(""), default: Some(""), is_set: false, source: None },
    ConfigRow { id: 35, name: "MaxUserTraceLogSize", value: Some("10"), default: Some("10"), is_set: false, source: None },
    ConfigRow { id: 36, name: "Providers", value: Some("Remote, Engine14, Loopback"), default: Some("Remote, Engine14, Loopback"), is_set: false, source: None },
    ConfigRow { id: 37, name: "AuthServer", value: Some("Srp256"), default: Some("Srp256"), is_set: false, source: None },
    ConfigRow { id: 38, name: "AuthClient", value: Some("Srp256, Srp, Legacy_Auth"), default: Some("Srp256, Srp, Legacy_Auth"), is_set: false, source: None },
    ConfigRow { id: 39, name: "UserManager", value: Some("Srp"), default: Some("Srp"), is_set: false, source: None },
    ConfigRow { id: 40, name: "DefaultProfilerPlugin", value: Some("Default_Profiler"), default: Some("Default_Profiler"), is_set: false, source: None },
    ConfigRow { id: 41, name: "TracePlugin", value: Some("fbtrace"), default: Some("fbtrace"), is_set: false, source: None },
    ConfigRow { id: 42, name: "SecurityDatabase", value: Some("/opt/firebird/security6.fdb"), default: Some("/opt/firebird/security6.fdb"), is_set: false, source: None },
    ConfigRow { id: 43, name: "ServerMode", value: Some("Super"), default: Some("Super"), is_set: false, source: None },
    ConfigRow { id: 44, name: "WireCrypt", value: None, default: Some("Required"), is_set: false, source: None },
    ConfigRow { id: 45, name: "WireCryptPlugin", value: Some("ChaCha64, ChaCha, Arc4"), default: Some("ChaCha64, ChaCha, Arc4"), is_set: false, source: None },
    ConfigRow { id: 46, name: "KeyHolderPlugin", value: Some(""), default: Some(""), is_set: false, source: None },
    ConfigRow { id: 47, name: "RemoteAccess", value: Some("true"), default: Some("true"), is_set: false, source: None },
    ConfigRow { id: 48, name: "IPv6V6Only", value: Some("false"), default: Some("false"), is_set: false, source: None },
    ConfigRow { id: 49, name: "WireCompression", value: Some("false"), default: Some("false"), is_set: false, source: None },
    ConfigRow { id: 50, name: "AllowEncryptedSecurityDatabase", value: Some("false"), default: Some("false"), is_set: false, source: None },
    ConfigRow { id: 51, name: "StatementTimeout", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 52, name: "ConnectionIdleTimeout", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 53, name: "OnDisconnectTriggerTimeout", value: Some("180"), default: Some("180"), is_set: false, source: None },
    ConfigRow { id: 54, name: "ClientBatchBuffer", value: Some("131072"), default: Some("131072"), is_set: false, source: None },
    ConfigRow { id: 55, name: "OutputRedirectionFile", value: Some("/dev/null"), default: Some("/dev/null"), is_set: false, source: None },
    ConfigRow { id: 56, name: "ExtConnPoolSize", value: Some("0"), default: Some("0"), is_set: false, source: None },
    ConfigRow { id: 57, name: "ExtConnPoolLifeTime", value: Some("7200"), default: Some("7200"), is_set: false, source: None },
    ConfigRow { id: 58, name: "SnapshotsMemSize", value: Some("65536"), default: Some("65536"), is_set: false, source: None },
    ConfigRow { id: 59, name: "TipCacheBlockSize", value: Some("4194304"), default: Some("4194304"), is_set: false, source: None },
    ConfigRow { id: 60, name: "ReadConsistency", value: Some("true"), default: Some("true"), is_set: false, source: None },
    ConfigRow { id: 61, name: "DataTypeCompatibility", value: None, default: None, is_set: false, source: None },
    ConfigRow { id: 62, name: "UseFileSystemCache", value: Some("true"), default: Some("true"), is_set: false, source: None },
    ConfigRow { id: 63, name: "InlineSortThreshold", value: Some("1000"), default: Some("1000"), is_set: false, source: None },
    ConfigRow { id: 64, name: "TempTableDirectory", value: Some(""), default: Some(""), is_set: false, source: None },
    ConfigRow { id: 65, name: "MaxStatementCacheSize", value: Some("2097152"), default: Some("2097152"), is_set: false, source: None },
    ConfigRow { id: 66, name: "ParallelWorkers", value: Some("1"), default: Some("1"), is_set: false, source: None },
    ConfigRow { id: 67, name: "MaxParallelWorkers", value: Some("1"), default: Some("1"), is_set: false, source: None },
    ConfigRow { id: 68, name: "OptimizeForFirstRows", value: Some("false"), default: Some("false"), is_set: false, source: None },
    ConfigRow { id: 69, name: "AllowUpdateOverwrite", value: Some("true"), default: Some("true"), is_set: false, source: None },
];
