#!/bin/bash
# SQL -> BLR, oracle number TWO: RDB$PROCEDURE_BLR. Views cannot hold
# ORDER BY - a procedure's FOR SELECT ... DO SUSPEND body can, and the
# engine stores ITS compiled BLR verbatim too. For every statement in
# the battery: the ENGINE runs the CREATE PROCEDURE and fire-crab-dsql
# compiles the identical text. THE BYTES MUST MATCH - the whole body,
# wrapper and all: message layout, declares, stall, labels, the FOR
# loop, both sends.
#
# The battery goes beyond the unit-test probe pins - fresh parameter
# types, fresh sort keys - so the gate tests the COMPILER, not the
# probe notebook. Refusals must answer REFUSED.
#
#   qa/dsql-proc-blr.sh
#
# Builds its own scratch database.

set -u
FCDSQL="${FCDSQL:-$(dirname "$0")/../target/release/fcdsql}"
ISQL="${ISQL:-isql}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
DB="$D/fc-dsqlproc.fdb"

mkdir -p "$D"; rm -f "$DB"
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF >/dev/null 2>&1 || { echo "FAIL create"; exit 1; }
CREATE DATABASE '$DB' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
CREATE TABLE EMPLOYEE (
  EMP_NO INTEGER NOT NULL,
  DEPT_ID INTEGER,
  SALARY INTEGER,
  FIRST_NAME VARCHAR(20),
  RATE NUMERIC(9,2),
  HIRED DATE
);
CREATE TABLE SRC (
  ID INTEGER,
  AMT INTEGER
);
CREATE EXCEPTION E_BAD 'bad data';
COMMIT;
SET TERM ^ ;
CREATE PROCEDURE HELPER0 (P1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = :P1; END^
CREATE PROCEDURE HELPER1 RETURNS (R1 INTEGER) AS BEGIN R1 = 7; SUSPEND; END^
CREATE EXCEPTION E_ODD 'odd'^
SET TERM ; ^
COMMIT;
EOF

fail=0
n=0
check() { # <create procedure statement>
    n=$((n + 1))
    name="GP$n"
    stmt="CREATE PROCEDURE $name ${1}"
    got=$("$FCDSQL" "$stmt")
    "$ISQL" -q -b -user "$U" -pas "$P" "$DB" >/dev/null 2>&1 <<SQL
SET TERM ^ ;
$stmt^
SET TERM ; ^
COMMIT;
SQL
    want=$("$ISQL" -q -b -user "$U" -pas "$P" "$DB" 2>/dev/null <<SQL | tr -d ' \n'
SET HEADING OFF;
SELECT CAST(CAST(RDB\$PROCEDURE_BLR AS BLOB SUB_TYPE 0) AS VARCHAR(900) CHARACTER SET OCTETS) FROM RDB\$PROCEDURES WHERE RDB\$PROCEDURE_NAME = '$name';
SQL
)
    if [ -z "$want" ]; then
        echo "DIFF [$stmt] - the engine did not store a procedure (bad battery statement?)"
        fail=1
    elif [ "$got" = "$want" ]; then
        echo "OK   $stmt"
    else
        echo "DIFF $stmt"
        echo "     engine: $want"
        echo "     fcdsql: $got"
        fail=1
    fi
}
refuse() {
    if [ "$("$FCDSQL" "$1")" = "REFUSED" ]; then
        echo "OK   refused: $1"
    else
        echo "DIFF [$1] compiled instead of refusing"; fail=1
    fi
}

# --- the battery -------------------------------------------------------
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE ORDER BY SALARY DESC INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > 1000 ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 VARCHAR(20)) AS BEGIN FOR SELECT EMP_NO, FIRST_NAME FROM EMPLOYEE ORDER BY FIRST_NAME, EMP_NO DESC INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 NUMERIC(9,2)) AS BEGIN FOR SELECT RATE FROM EMPLOYEE WHERE RATE IS NOT NULL INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 DATE) AS BEGIN FOR SELECT HIRED FROM EMPLOYEE ORDER BY HIRED INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 SMALLINT, R2 BIGINT) AS BEGIN FOR SELECT DEPT_ID, SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 1 AND 90000 INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE UPPER(FIRST_NAME) LIKE 'R%' ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 CHAR(5)) AS BEGIN FOR SELECT FIRST_NAME FROM EMPLOYEE WHERE CASE WHEN SALARY > 100 THEN 1 ELSE 0 END = 1 INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (100, 600) AND SALARY + 1 > 500 ORDER BY DEPT_ID, EMP_NO INTO :R1 DO SUSPEND; END"
# INTO in a different order than RETURNS: variables follow the NAMES
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, EMP_NO FROM EMPLOYEE INTO :R2, :R1 DO SUSPEND; END"

# --- slice 8: aggregates and GROUP BY ----------------------------------
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT COUNT(*) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT SUM(SALARY) FROM EMPLOYEE WHERE DEPT_ID = 600 INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 NUMERIC(9,2)) AS BEGIN FOR SELECT AVG(RATE) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT MIN(SALARY), MAX(SALARY) FROM EMPLOYEE INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT COUNT(FIRST_NAME) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE GROUP BY DEPT_ID INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, SUM(SALARY) FROM EMPLOYEE WHERE SALARY > 0 GROUP BY DEPT_ID ORDER BY DEPT_ID INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE GROUP BY DEPT_ID HAVING COUNT(*) > 2 INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, MAX(SALARY) FROM EMPLOYEE GROUP BY DEPT_ID HAVING MIN(SALARY) > 100 AND DEPT_ID > 0 ORDER BY DEPT_ID DESC INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT SUM(SALARY * 12) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"

# --- slice 9: input parameters -----------------------------------------
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > :P1 INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER, P2 VARCHAR(20)) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID = :P1 AND FIRST_NAME = :P2 ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "(LO INTEGER, HI INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY BETWEEN :LO AND :HI INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE WHERE SALARY > :P1 GROUP BY DEPT_ID INTO :R1, :R2 DO SUSPEND; END"
check "(P1 NUMERIC(9,2)) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE RATE * 2 > :P1 INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (:P1, 600) INTO :R1 DO SUSPEND; END"
# an UNUSED input still shapes message 0 and the receive wrapper
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE INTO :R1 DO SUSPEND; END"

# --- slice 10: SELECT INTO, FIRST/SKIP, DISTINCT aggregates ------------
check "RETURNS (R1 INTEGER) AS BEGIN SELECT COUNT(*) FROM EMPLOYEE INTO :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN SELECT SUM(SALARY) FROM EMPLOYEE WHERE DEPT_ID = 600 INTO :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN SELECT EMP_NO FROM EMPLOYEE WHERE EMP_NO = 7 INTO :R1; END"
check "RETURNS (R1 INTEGER) AS BEGIN SELECT EMP_NO FROM EMPLOYEE INTO :R1; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN SELECT MAX(SALARY) FROM EMPLOYEE WHERE DEPT_ID = :P1 INTO :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT FIRST 10 EMP_NO FROM EMPLOYEE ORDER BY SALARY DESC INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT FIRST 10 SKIP 5 EMP_NO FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT SKIP 1 EMP_NO FROM EMPLOYEE WHERE SALARY > 0 ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT COUNT(DISTINCT DEPT_ID) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT SUM(DISTINCT SALARY) FROM EMPLOYEE WHERE SALARY > 0 INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(DISTINCT FIRST_NAME) FROM EMPLOYEE WHERE SALARY > :P1 GROUP BY DEPT_ID INTO :R1, :R2 DO SUSPEND; END"

# --- slice 14: general multi-statement bodies --------------------------
check "RETURNS (R1 INTEGER) AS BEGIN R1 = 42; SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN R1 = 1; R2 = R1 + 1; SUSPEND; R1 = 2; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER = 0; BEGIN WHILE (V1 < P1) DO V1 = V1 + 1; R1 = V1; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN IF (P1 > 100) THEN R1 = 100; ELSE R1 = P1; SUSPEND; END"
check "(P1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = :P1; END"
check "(P1 INTEGER, P2 INTEGER) AS BEGIN UPDATE EMPLOYEE SET SALARY = :P2 WHERE EMPLOYEE.EMP_NO = :P1; END"
check "(P1 INTEGER) AS BEGIN INSERT INTO EMPLOYEE (EMP_NO, SALARY) VALUES (:P1, 0); END"
check "RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; BEGIN SELECT COUNT(*) FROM EMPLOYEE INTO :V1; R1 = V1 * 2; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > :P1 ORDER BY EMP_NO INTO :R1 DO SUSPEND; R1 = 0; SUSPEND; END"
check "(P1 INTEGER) AS BEGIN IF (P1 > 0) THEN INSERT INTO EMPLOYEE (EMP_NO) VALUES (:P1); ELSE DELETE FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = 0; END"

# --- slice 15: calls, exceptions, exit ---------------------------------
check "AS BEGIN EXECUTE PROCEDURE HELPER0(42); END"
check "(P1 INTEGER) AS BEGIN EXECUTE PROCEDURE HELPER0(:P1 + 1); END"
check "RETURNS (R1 INTEGER) AS BEGIN EXECUTE PROCEDURE HELPER1 RETURNING_VALUES :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; BEGIN EXECUTE PROCEDURE HELPER1 RETURNING_VALUES :V1; R1 = V1 * 10; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN IF (P1 < 0) THEN EXCEPTION E_BAD; R1 = P1; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN R1 = P1; IF (P1 = 0) THEN EXIT; SUSPEND; END"
check "AS BEGIN IF (1 = 0) THEN EXCEPTION E_BAD; ELSE EXIT; END"
check "RETURNS (R1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.SALARY < 0; SELECT COUNT(*) FROM EMPLOYEE INTO :R1; SUSPEND; END"

# --- slice 19: WHEN handlers and ROW_COUNT -----------------------------
check "RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 100 / 0; WHEN ANY DO R1 = -1; END SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 1; WHEN EXCEPTION E_BAD DO R1 = -2; END SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 1; WHEN GDSCODE arith_except DO R1 = 0; END SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 100 / P1; WHEN ANY DO EXIT; END SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN UPDATE EMPLOYEE SET SALARY = 0 WHERE EMPLOYEE.EMP_NO = :P1; R1 = ROW_COUNT; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.SALARY < 0; IF (ROW_COUNT > 10) THEN EXCEPTION E_BAD; R1 = ROW_COUNT; SUSPEND; END"

# --- slice 20: UPDATE OR INSERT, context vars, richer handlers ---------
check "(P1 INTEGER, P2 INTEGER) AS BEGIN UPDATE OR INSERT INTO EMPLOYEE (EMP_NO, SALARY) VALUES (:P1, :P2) MATCHING (EMP_NO); END"
check "(P1 INTEGER) AS BEGIN UPDATE OR INSERT INTO EMPLOYEE (EMP_NO, DEPT_ID, SALARY) VALUES (:P1, 100, :P1 * 10) MATCHING (EMP_NO); END"
check "RETURNS (R1 BIGINT) AS BEGIN R1 = CURRENT_CONNECTION; SUSPEND; END"
check "RETURNS (R1 BIGINT, R2 BIGINT) AS BEGIN R1 = CURRENT_CONNECTION; R2 = CURRENT_TRANSACTION; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 1 / 0; WHEN GDSCODE arith_except DO R1 = -1; WHEN ANY DO R1 = -2; END SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 1; WHEN ANY DO BEGIN R1 = -1; EXIT; END END SUSPEND; END"

# --- refusals ----------------------------------------------------------
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE ORDER BY 1 INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE INTO :WRONG DO SUSPEND; END"
# (aliased FOR streams - a slice-7 refusal - flipped in slice 28)
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE E INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE INTO :R1, :R2 DO SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > :NOPE INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE GROUP BY DEPT_ID HAVING COUNT(*) > :P1 INTO :R1, :R2 DO SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT FIRST :P1 EMP_NO FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT FIRST 2 COUNT(*) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) AS BEGIN SUSPEND; END"

refuse "CREATE PROCEDURE X (P1 INTEGER) AS BEGIN UPDATE OR INSERT INTO EMPLOYEE (EMP_NO) VALUES (:P1); END"

# --- slice 22: cursor aliases, aggregate cursors, positioned DML -------
check "RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 100 / 0; WHEN SQLSTATE '22012' DO R1 = -1; WHEN ANY DO R1 = -2; END SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 1; WHEN ANY DO BEGIN R1 = -1; WHEN EXCEPTION E_BAD DO EXIT; END END SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 VARCHAR(20)) AS DECLARE CX CURSOR FOR (SELECT E.EMP_NO, E.FIRST_NAME FROM EMPLOYEE E WHERE E.SALARY > :P1 ORDER BY E.FIRST_NAME, E.EMP_NO DESC); BEGIN OPEN CX; FETCH CX INTO :R1, :R2; CLOSE CX; SUSPEND; END"
check "RETURNS (R1 NUMERIC(9,2)) AS DECLARE CX CURSOR FOR (SELECT AVG(RATE) AS A FROM EMPLOYEE); BEGIN OPEN CX; FETCH CX INTO :R1; CLOSE CX; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER, R3 INTEGER) AS DECLARE CX CURSOR FOR (SELECT DEPT_ID, COUNT(*) AS C, MAX(SALARY) AS M FROM EMPLOYEE WHERE SALARY > :P1 GROUP BY DEPT_ID); BEGIN OPEN CX; FETCH CX INTO :R1, :R2, :R3; CLOSE CX; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS DECLARE CX CURSOR FOR (SELECT COUNT(FIRST_NAME) AS C FROM EMPLOYEE); BEGIN OPEN CX; FETCH CX INTO :R1; CLOSE CX; SUSPEND; END"
check "AS DECLARE CX CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE WHERE SALARY < 0); BEGIN OPEN CX; FETCH CX; DELETE FROM EMPLOYEE WHERE CURRENT OF CX; CLOSE CX; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; DECLARE CX CURSOR FOR (SELECT EMP_NO, SALARY FROM EMPLOYEE); BEGIN OPEN CX; WHILE (1 = 1) DO BEGIN FETCH CX INTO :V1, :R1; IF (ROW_COUNT = 0) THEN EXIT; UPDATE EMPLOYEE SET SALARY = :P1, DEPT_ID = DEPT_ID + 1 WHERE CURRENT OF CX; SUSPEND; END CLOSE CX; END"

# --- slice 23: MERGE and FOR SELECT AS CURSOR --------------------------
check "(P1 INTEGER) AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN MATCHED THEN UPDATE SET SALARY = SRC.AMT * 2, DEPT_ID = 100 WHEN NOT MATCHED THEN INSERT (EMP_NO, SALARY) VALUES (SRC.ID, SRC.AMT + :P1); END"
check "AS BEGIN MERGE INTO EMPLOYEE E USING SRC S ON E.EMP_NO = S.ID WHEN MATCHED THEN DELETE WHEN NOT MATCHED THEN INSERT (EMP_NO, DEPT_ID) VALUES (S.ID, 100); END"
check "(P1 INTEGER) AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID AND SRC.AMT > :P1 WHEN MATCHED THEN UPDATE SET SALARY = :P1; END"
check "AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN NOT MATCHED THEN INSERT (EMP_NO, SALARY, DEPT_ID) VALUES (SRC.ID, SRC.AMT, 0); END"
check "(P1 INTEGER) AS BEGIN IF (P1 > 0) THEN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN MATCHED THEN DELETE; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT EMP_NO, SALARY FROM EMPLOYEE WHERE SALARY > :P1 INTO :R1, :R2 AS CURSOR CU DO BEGIN UPDATE EMPLOYEE SET SALARY = SALARY + 1 WHERE CURRENT OF CU; SUSPEND; END END"
check "AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE RATE IS NULL AS CURSOR CU DO DELETE FROM EMPLOYEE WHERE CURRENT OF CU; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; BEGIN FOR SELECT EMP_NO FROM EMPLOYEE INTO :V1 AS CURSOR CU DO BEGIN IF (V1 < :P1) THEN UPDATE EMPLOYEE SET DEPT_ID = DEPT_ID + 1, SALARY = 0 WHERE CURRENT OF CU; END R1 = V1; SUSPEND; END"

# --- slice 24: conditional MERGE, scroll fetch, RETURNING, EXEC STMT ---
check "(P1 INTEGER, P2 INTEGER) AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN MATCHED AND EMPLOYEE.SALARY < :P1 THEN UPDATE SET SALARY = :P2 WHEN NOT MATCHED THEN INSERT (EMP_NO, SALARY) VALUES (SRC.ID, :P2); END"
check "(P1 INTEGER) AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN NOT MATCHED AND SRC.AMT > :P1 THEN INSERT (EMP_NO, SALARY) VALUES (SRC.ID, SRC.AMT); END"
check "AS BEGIN MERGE INTO EMPLOYEE E USING SRC S ON E.EMP_NO = S.ID WHEN MATCHED AND E.DEPT_ID = 100 THEN DELETE; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS DECLARE CX SCROLL CURSOR FOR (SELECT EMP_NO, SALARY FROM EMPLOYEE WHERE SALARY > 0); BEGIN OPEN CX; FETCH LAST FROM CX INTO :R1, :R2; SUSPEND; FETCH FIRST FROM CX INTO :R1, :R2; SUSPEND; FETCH ABSOLUTE 2 FROM CX INTO :R1, :R2; SUSPEND; CLOSE CX; END"
check "RETURNS (R1 INTEGER) AS DECLARE CX SCROLL CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE); BEGIN OPEN CX; FETCH LAST FROM CX INTO :R1; WHILE (ROW_COUNT > 0) DO BEGIN SUSPEND; FETCH PRIOR FROM CX INTO :R1; END CLOSE CX; END"
check "(P1 INTEGER, P2 INTEGER) RETURNS (R1 INTEGER) AS BEGIN INSERT INTO EMPLOYEE (EMP_NO, SALARY) VALUES (:P1, :P2 * 10) RETURNING EMP_NO INTO :R1; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN UPDATE EMPLOYEE SET SALARY = SALARY + 100, DEPT_ID = 0 WHERE EMPLOYEE.EMP_NO = :P1 RETURNING SALARY, DEPT_ID INTO :R1, :R2; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = :P1 RETURNING SALARY INTO :V1; R1 = V1; SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 VARCHAR(20)) AS BEGIN EXECUTE STATEMENT 'select emp_no, first_name from employee' INTO :R1, :R2; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER = 0; BEGIN FOR EXECUTE STATEMENT 'select salary from employee' INTO :V1 DO IF (V1 > 0) THEN BEGIN R1 = V1; SUSPEND; END EXECUTE STATEMENT 'update employee set salary = 0'; END"

# --- slice 25: branch chains, parameterized EXEC STMT, WITH LOCK -------
check "(P1 INTEGER, P2 INTEGER) AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN MATCHED AND EMPLOYEE.SALARY > :P1 THEN UPDATE SET SALARY = :P2 WHEN MATCHED THEN UPDATE SET DEPT_ID = 0 WHEN NOT MATCHED THEN INSERT (EMP_NO, SALARY) VALUES (SRC.ID, SRC.AMT); END"
check "(P1 INTEGER) AS BEGIN MERGE INTO EMPLOYEE E USING SRC S ON E.EMP_NO = S.ID WHEN MATCHED AND E.DEPT_ID = 100 THEN DELETE WHEN MATCHED AND E.SALARY < :P1 THEN UPDATE SET SALARY = :P1 WHEN MATCHED THEN DELETE; END"
check "(P1 INTEGER, P2 INTEGER) AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN NOT MATCHED AND SRC.AMT > :P1 THEN INSERT (EMP_NO) VALUES (SRC.ID) WHEN NOT MATCHED AND SRC.AMT < :P2 THEN INSERT (EMP_NO, SALARY) VALUES (SRC.ID, 0); END"
check "(P1 INTEGER, P2 VARCHAR(20)) RETURNS (R1 INTEGER) AS BEGIN EXECUTE STATEMENT ('select emp_no from employee where salary > ? and first_name = ?') (:P1, :P2) INTO :R1; SUSPEND; END"
check "(P1 INTEGER) AS BEGIN EXECUTE STATEMENT ('update employee set salary = salary + ? where salary > 0') (:P1 * 2); END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS DECLARE V1 INTEGER; BEGIN FOR EXECUTE STATEMENT ('select emp_no, salary from employee where dept_id = ?') (:P1) INTO :R1, :V1 DO BEGIN R2 = V1 * 2; SUSPEND; END END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT EMP_NO, SALARY FROM EMPLOYEE WHERE DEPT_ID = :P1 WITH LOCK INTO :R1, :R2 DO SUSPEND; END"
check "(P1 INTEGER) AS DECLARE V1 INTEGER; DECLARE CX CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE WHERE SALARY < :P1 WITH LOCK); BEGIN OPEN CX; WHILE (1 = 1) DO BEGIN FETCH CX INTO :V1; IF (ROW_COUNT = 0) THEN EXIT; UPDATE EMPLOYEE SET SALARY = 0 WHERE CURRENT OF CX; END CLOSE CX; END"
check "AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WITH LOCK AS CURSOR CU DO UPDATE EMPLOYEE SET DEPT_ID = DEPT_ID + 1 WHERE CURRENT OF CU; END"

# --- slice 26: subroutines, named/modified EXECUTE STATEMENT -----------
check "RETURNS (R1 INTEGER) AS DECLARE FUNCTION CLAMP (V1 INTEGER, LO INTEGER, HI INTEGER) RETURNS INTEGER AS BEGIN IF (V1 < LO) THEN RETURN LO; IF (V1 > HI) THEN RETURN HI; RETURN V1; END BEGIN R1 = CLAMP(150, 0, 100); SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE FUNCTION SIGN2 (X1 INTEGER) RETURNS INTEGER DETERMINISTIC AS BEGIN IF (X1 < 0) THEN RETURN -1; RETURN 1; END BEGIN R1 = SIGN2(:P1) * SIGN2(:P1 + 1); SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE PROCEDURE ADDER (A1 INTEGER, B1 INTEGER) RETURNS (S1 INTEGER) AS BEGIN S1 = A1 + B1; END BEGIN EXECUTE PROCEDURE ADDER(:P1, 10) RETURNING_VALUES :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER = 1; DECLARE V2 INTEGER = 2; DECLARE PROCEDURE PICK RETURNS (O1 INTEGER) AS BEGIN O1 = 42; SUSPEND; END BEGIN EXECUTE PROCEDURE PICK RETURNING_VALUES :V2; R1 = V1 + V2; SUSPEND; END"
check "(P1 INTEGER, P2 VARCHAR(20)) RETURNS (R1 INTEGER) AS BEGIN EXECUTE STATEMENT ('select emp_no from employee where salary > :s and first_name = :n') (s := :P1, n := :P2) INTO :R1; SUSPEND; END"
check "(P1 INTEGER) AS BEGIN EXECUTE STATEMENT ('update employee set salary = :v where salary < 0') (v := :P1 * 2); END"
check "RETURNS (R1 INTEGER) AS BEGIN EXECUTE STATEMENT 'select count(*) from employee' AS USER 'SYSDBA' PASSWORD 'masterkey' INTO :R1; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; BEGIN FOR EXECUTE STATEMENT ('select salary from employee where dept_id = :d') (d := :P1) INTO :V1 DO BEGIN R1 = V1; SUSPEND; END END"
check "RETURNS (R1 INTEGER, R2 INTEGER, R3 INTEGER) AS DECLARE A1 INTEGER = 10; DECLARE B1 INTEGER; DECLARE C1 INTEGER = 30; BEGIN B1 = 20; R1 = A1; R2 = B1; R3 = C1; SUSPEND; END"

# --- slice 27: streams inside subroutines ------------------------------
check "(P1 INTEGER) AS DECLARE PROCEDURE LOGIT (X1 INTEGER, A1 INTEGER) AS BEGIN INSERT INTO SRC (ID, AMT) VALUES (:X1, :A1); END BEGIN EXECUTE PROCEDURE LOGIT(:P1, 0); END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE PROCEDURE TOPSAL (D1 INTEGER) RETURNS (S1 INTEGER) AS BEGIN SELECT MAX(SALARY) FROM EMPLOYEE WHERE DEPT_ID = :D1 INTO :S1; END BEGIN EXECUTE PROCEDURE TOPSAL(:P1) RETURNING_VALUES :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS DECLARE PROCEDURE EACH RETURNS (E1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > 0 ORDER BY EMP_NO INTO :E1 DO SUSPEND; END BEGIN EXECUTE PROCEDURE EACH RETURNING_VALUES :R1; SUSPEND; END"
check "AS DECLARE PROCEDURE ZAPLOW (T1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY < :T1 AS CURSOR CU DO UPDATE EMPLOYEE SET SALARY = :T1 WHERE CURRENT OF CU; END BEGIN EXECUTE PROCEDURE ZAPLOW(100); END"
check "(P1 INTEGER) AS DECLARE PROCEDURE UPSERT (K1 INTEGER, V1 INTEGER) AS BEGIN UPDATE OR INSERT INTO SRC (ID, AMT) VALUES (:K1, :V1) MATCHING (ID); END BEGIN EXECUTE PROCEDURE UPSERT(:P1, :P1 * 2); END"
check "AS DECLARE PROCEDURE SYNC AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN MATCHED THEN UPDATE SET SALARY = SRC.AMT WHEN NOT MATCHED THEN INSERT (EMP_NO, SALARY) VALUES (SRC.ID, SRC.AMT); END BEGIN EXECUTE PROCEDURE SYNC; END"
check "RETURNS (R1 INTEGER) AS DECLARE FUNCTION HEADCOUNT RETURNS INTEGER AS DECLARE C1 INTEGER; BEGIN SELECT COUNT(*) FROM EMPLOYEE INTO :C1; RETURN C1; END BEGIN R1 = HEADCOUNT() + 0; SUSPEND; END"

# --- slice 29: subqueries in bodies, aliased AS CURSOR -----------------
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE EXISTS (SELECT 1 FROM SRC WHERE SRC.ID = EMPLOYEE.EMP_NO AND SRC.AMT > :P1) INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE NOT EXISTS (SELECT 1 FROM SRC WHERE SRC.ID = EMPLOYEE.EMP_NO) INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.DEPT_ID IN (SELECT ID FROM SRC WHERE SRC.AMT < :P1); END"
check "(P1 INTEGER) AS BEGIN UPDATE EMPLOYEE SET SALARY = 0 WHERE EMPLOYEE.SALARY > ALL (SELECT AMT FROM SRC WHERE SRC.ID > :P1); END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS DECLARE V1 INTEGER; BEGIN V1 = (SELECT AMT FROM SRC WHERE SRC.ID = :P1); R1 = V1; R2 = (SELECT ID FROM SRC WHERE SRC.AMT = 0); SUSPEND; END"
check "(P1 INTEGER) AS BEGIN IF (EXISTS (SELECT 1 FROM SRC WHERE SRC.ID = :P1)) THEN DELETE FROM SRC S WHERE S.ID = :P1; END"
check "(P1 INTEGER) AS BEGIN FOR SELECT E.EMP_NO FROM EMPLOYEE E WHERE E.SALARY < :P1 AS CURSOR CU DO UPDATE EMPLOYEE SET SALARY = :P1 WHERE CURRENT OF CU; END"
check "AS DECLARE PROCEDURE SCRUB AS BEGIN FOR SELECT ID FROM SRC QQ AS CURSOR CV DO DELETE FROM SRC WHERE CURRENT OF CV; END BEGIN EXECUTE PROCEDURE SCRUB; END"

# --- slice 30: aggregate scalar subselects -----------------------------
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN R1 = (SELECT SUM(AMT) FROM SRC WHERE SRC.ID > :P1); SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > (SELECT AVG(AMT) FROM SRC) ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.SALARY < (SELECT MIN(AMT) FROM SRC WHERE SRC.ID = :P1); END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN R1 = (SELECT COUNT(*) FROM SRC); R2 = (SELECT COUNT(ID) FROM SRC WHERE SRC.AMT IS NOT NULL); SUSPEND; END"
check "(P1 INTEGER) AS BEGIN UPDATE EMPLOYEE SET SALARY = (SELECT MAX(AMT) FROM SRC) WHERE EMPLOYEE.EMP_NO = :P1; END"
check "RETURNS (R1 INTEGER) AS DECLARE PROCEDURE TALLY RETURNS (O1 INTEGER) AS BEGIN O1 = (SELECT COUNT(*) FROM SRC WHERE SRC.AMT > 0); END BEGIN EXECUTE PROCEDURE TALLY RETURNING_VALUES :R1; SUSPEND; END"

# --- slice 31: cursor-rse subquery aliases, DISTINCT scalars -----------
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE CX CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (SELECT ID FROM SRC WHERE SRC.AMT > :P1)); BEGIN OPEN CX; FETCH CX INTO :R1; CLOSE CX; SUSPEND; END"
check "AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE NOT EXISTS (SELECT 1 FROM SRC Q WHERE Q.ID = EMPLOYEE.EMP_NO) AS CURSOR CU DO DELETE FROM EMPLOYEE WHERE CURRENT OF CU; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN R1 = (SELECT AVG(DISTINCT AMT) FROM SRC WHERE SRC.ID > :P1); SUSPEND; END"
check "RETURNS (R1 INTEGER) AS DECLARE CX CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > (SELECT SUM(AMT) FROM SRC)); BEGIN OPEN CX; FETCH CX INTO :R1; CLOSE CX; SUSPEND; END"

# --- slice 30 refusals -------------------------------------------------
# (cursor-rse subqueries - a slice-30 refusal - flipped in slice 31)
check "RETURNS (R1 INTEGER) AS DECLARE CX CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE WHERE EXISTS (SELECT 1 FROM SRC WHERE SRC.ID = EMPLOYEE.EMP_NO)); BEGIN OPEN CX; FETCH CX INTO :R1; CLOSE CX; SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > ALL (SELECT MAX(AMT) FROM SRC) INTO :R1 DO SUSPEND; END"

# --- slice 29 refusals -------------------------------------------------
# (aggregate scalar subselects - a slice-29 refusal - flipped in slice 30)
check "RETURNS (R1 INTEGER) AS BEGIN R1 = (SELECT MAX(AMT) FROM SRC); SUSPEND; END"

# --- slice 28: aliased streams, subroutines in triggers ----------------
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 VARCHAR(20)) AS BEGIN FOR SELECT E.EMP_NO, E.FIRST_NAME FROM EMPLOYEE E WHERE E.DEPT_ID = :P1 ORDER BY E.FIRST_NAME INTO :R1, :R2 DO SUSPEND; END"
check "(P1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE E WHERE E.SALARY < :P1 AND E.DEPT_ID = 0; END"
check "(P1 INTEGER, P2 INTEGER) AS BEGIN UPDATE EMPLOYEE W SET SALARY = W.SALARY + :P2, DEPT_ID = 100 WHERE W.EMP_NO = :P1; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT A.DEPT_ID, SUM(A.SALARY) FROM EMPLOYEE A WHERE A.SALARY > 0 GROUP BY A.DEPT_ID INTO :R1, :R2 DO SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN SELECT MAX(B.AMT) FROM SRC B WHERE B.ID = :P1 INTO :R1; SUSPEND; END"
check "(P1 INTEGER) AS DECLARE PROCEDURE CLEANUP (T1 INTEGER) AS BEGIN DELETE FROM SRC S WHERE S.AMT < :T1; END BEGIN EXECUTE PROCEDURE CLEANUP(:P1); END"

# --- slice 27 refusals -------------------------------------------------
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS DECLARE PROCEDURE S1 RETURNS (O1 INTEGER) AS BEGIN SELECT ID FROM (SELECT ID FROM SRC) A INTO :O1; END BEGIN EXECUTE PROCEDURE S1 RETURNING_VALUES :R1; SUSPEND; END"

# --- slice 26 refusals -------------------------------------------------
# (streams inside subroutines - a slice-26 refusal - flipped in slice 27)
check "(P1 INTEGER) AS DECLARE PROCEDURE LOGIT (X1 INTEGER) AS BEGIN INSERT INTO EMPLOYEE (EMP_NO) VALUES (:X1); END BEGIN EXECUTE PROCEDURE LOGIT(:P1); END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN RETURN 1; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS DECLARE FUNCTION F1 RETURNS INTEGER AS BEGIN SUSPEND; END BEGIN R1 = F1(); SUSPEND; END"

# --- slice 25 refusals -------------------------------------------------
refuse "CREATE PROCEDURE X (P1 INTEGER) AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN MATCHED THEN DELETE WHEN MATCHED AND EMPLOYEE.SALARY > :P1 THEN UPDATE SET SALARY = 0; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE ORDER BY EMP_NO WITH LOCK INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT COUNT(*) FROM EMPLOYEE WITH LOCK INTO :R1 DO SUSPEND; END"

# --- slice 24 refusals -------------------------------------------------
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS DECLARE CX CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE); BEGIN OPEN CX; FETCH LAST FROM CX INTO :R1; CLOSE CX; SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) AS BEGIN EXECUTE STATEMENT 'delete from employee where emp_no = ?' USING :P1; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN INSERT INTO EMPLOYEE (EMP_NO) VALUES (:P1) RETURNING EMP_NO + 1 INTO :R1; SUSPEND; END"

# --- slice 23 refusals -------------------------------------------------
# (WHEN MATCHED AND - a slice-23 refusal - flipped in slice 24)
check "AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN MATCHED AND SRC.AMT > 0 THEN DELETE; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) AS BEGIN MERGE INTO EMPLOYEE USING SRC ON EMPLOYEE.EMP_NO = SRC.ID WHEN MATCHED THEN UPDATE SET SALARY = :P1 WHEN MATCHED THEN DELETE; END"
refuse "CREATE PROCEDURE X AS BEGIN MERGE INTO EMPLOYEE USING (SELECT ID FROM SRC) A ON EMPLOYEE.EMP_NO = A.ID WHEN MATCHED THEN DELETE; END"
refuse "CREATE PROCEDURE X AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE ORDER BY EMP_NO AS CURSOR CU DO DELETE FROM EMPLOYEE WHERE CURRENT OF CU; END"

# --- slice 22 refusals -------------------------------------------------
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS DECLARE CX CURSOR FOR (SELECT COUNT(DISTINCT DEPT_ID) AS C FROM EMPLOYEE); BEGIN OPEN CX; FETCH CX INTO :R1; CLOSE CX; SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER, R2 INTEGER) AS DECLARE CX CURSOR FOR (SELECT DEPT_ID, COUNT(*) AS C FROM EMPLOYEE GROUP BY DEPT_ID HAVING COUNT(*) > 2); BEGIN OPEN CX; FETCH CX INTO :R1, :R2; CLOSE CX; SUSPEND; END"
refuse "CREATE PROCEDURE X AS DECLARE CX CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE); BEGIN OPEN CX; FETCH CX; DELETE FROM HELPER0 WHERE CURRENT OF CX; CLOSE CX; END"

# --- slice 21: autonomous, cursors, remaining shapes -------------------
check "AS BEGIN IN AUTONOMOUS TRANSACTION DO DELETE FROM EMPLOYEE WHERE EMPLOYEE.SALARY < 0; END"
check "(P1 INTEGER) AS BEGIN IN AUTONOMOUS TRANSACTION DO BEGIN INSERT INTO EMPLOYEE (EMP_NO) VALUES (:P1); POST_EVENT 'logged'; END END"
check "(P1 INTEGER, P2 INTEGER, P3 INTEGER) AS BEGIN UPDATE OR INSERT INTO EMPLOYEE (EMP_NO, DEPT_ID, SALARY) VALUES (:P1, :P2, :P3) MATCHING (EMP_NO, DEPT_ID); END"
check "RETURNS (R1 INTEGER) AS BEGIN BEGIN R1 = 1 / 0; WHEN SQLCODE -802 DO R1 = 0; WHEN ANY DO R1 = -1; END SUSPEND; END"
check "RETURNS (R1 INTEGER) AS DECLARE CX CURSOR FOR (SELECT EMP_NO FROM EMPLOYEE); BEGIN OPEN CX; FETCH CX INTO :R1; CLOSE CX; SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS DECLARE CX CURSOR FOR (SELECT EMP_NO, SALARY FROM EMPLOYEE WHERE SALARY > 0 ORDER BY EMP_NO DESC); BEGIN OPEN CX; FETCH CX INTO :R1, :R2; SUSPEND; CLOSE CX; END"
check "RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; DECLARE CX CURSOR FOR (SELECT DEPT_ID FROM EMPLOYEE); BEGIN OPEN CX; WHILE (1 = 1) DO BEGIN FETCH CX INTO :V1; IF (ROW_COUNT = 0) THEN EXIT; R1 = V1; SUSPEND; END END"

exit $fail
