#!/bin/bash
# SQL -> BLR, against the engine's own compiler. For every statement in
# the battery: the ENGINE runs CREATE VIEW <v> AS <select> - its DSQL
# compiles the SELECT and stores the BLR verbatim in RDB$VIEW_BLR -
# and fire-crab-dsql compiles the identical statement. THE BYTES MUST
# MATCH. This is the purest differential in the project: the oracle is
# the exact artifact under conversion, produced by the original
# compiler on demand.
#
# The battery deliberately goes BEYOND the probes the unit tests pin -
# fresh combinations, so the gate tests the COMPILER, not the probe
# notebook. A statement fire-crab-dsql refuses is only OK if it is in
# the REFUSE list; a refusal of a battery statement is a failure.
#
#   qa/dsql-view-blr.sh
#
# Builds its own scratch database.

set -u
FCDSQL="${FCDSQL:-$(dirname "$0")/../target/release/fcdsql}"
ISQL="${ISQL:-isql}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
DB="$D/fc-dsqlblr.fdb"

mkdir -p "$D"; rm -f "$DB"
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF >/dev/null 2>&1 || { echo "FAIL create"; exit 1; }
CREATE DATABASE '$DB' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
CREATE TABLE EMPLOYEE (
  EMP_NO INTEGER NOT NULL,
  DEPT_ID INTEGER,
  SALARY INTEGER,
  FIRST_NAME VARCHAR(20),
  RATE NUMERIC(9,2),
  HIRED DATE
);
CREATE TABLE DEPARTMENT (
  DEPT_NO INTEGER NOT NULL,
  DNAME VARCHAR(20),
  BUDGET INTEGER
);
CREATE TABLE PROJECT (
  PROJ_ID INTEGER NOT NULL,
  LEAD_NO INTEGER,
  TITLE VARCHAR(20)
);
COMMIT;
EOF

fail=0
n=0
check() { # <select statement>
    n=$((n + 1))
    v="GV$n"
    got=$("$FCDSQL" "$1")
    "$ISQL" -q -b -user "$U" -pas "$P" "$DB" >/dev/null 2>&1 <<SQL
CREATE VIEW $v AS $1;
COMMIT;
SQL
    want=$("$ISQL" -q -b -user "$U" -pas "$P" "$DB" 2>/dev/null <<SQL | tr -d ' \n'
SET HEADING OFF;
SELECT CAST(CAST(RDB\$VIEW_BLR AS BLOB SUB_TYPE 0) AS VARCHAR(250) CHARACTER SET OCTETS) FROM RDB\$RELATIONS WHERE RDB\$RELATION_NAME = '$v';
SQL
)
    if [ -z "$want" ]; then
        echo "DIFF [$1] - the engine did not store a view (bad battery statement?)"
        fail=1
    elif [ "$got" = "$want" ]; then
        echo "OK   $1"
    else
        echo "DIFF $1"
        echo "     engine: $want"
        echo "     fcdsql: $got"
        fail=1
    fi
}
refuse() { # <statement fire-crab-dsql must refuse>
    if [ "$("$FCDSQL" "$1")" = "REFUSED" ]; then
        echo "OK   refused: $1"
    else
        echo "DIFF [$1] compiled instead of refusing"; fail=1
    fi
}

# --- the battery: fresh statements, none of them unit-test pins --------
check "SELECT EMP_NO FROM EMPLOYEE"
check "SELECT EMP_NO, SALARY, FIRST_NAME FROM EMPLOYEE"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > 40000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID = 600"
check "SELECT EMP_NO FROM EMPLOYEE WHERE FIRST_NAME = 'Robert'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY >= 10000 AND SALARY <= 90000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID = 100 OR DEPT_ID = 600 OR DEPT_ID = 900"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NOT (SALARY <= 40000)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NOT (DEPT_ID = 100 AND SALARY > 1)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE FIRST_NAME IS NULL"
check "SELECT EMP_NO FROM EMPLOYEE WHERE FIRST_NAME IS NOT NULL"
check "SELECT EMP_NO FROM EMPLOYEE WHERE RATE = 0.05"
check "SELECT EMP_NO FROM EMPLOYEE WHERE RATE <> 99.9"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY BETWEEN 20000 AND 30000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY NOT BETWEEN 20000 AND 30000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE FIRST_NAME LIKE 'Rob%'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE FIRST_NAME NOT LIKE '%x%'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID = EMP_NO"
check "SELECT EMP_NO FROM EMPLOYEE WHERE (DEPT_ID = 100 OR DEPT_ID = 600) AND SALARY > 500"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NOT (FIRST_NAME LIKE 'a%' OR RATE IS NULL)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NOT (NOT (SALARY = 1))"

# --- slice 2: value expressions, IN, streams, aliases ------------------
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY + 500 > 40000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY * 12 - 1 = 599999"
check "SELECT EMP_NO FROM EMPLOYEE WHERE -DEPT_ID = -600"
check "SELECT EMP_NO FROM EMPLOYEE WHERE (SALARY + 1) / 2 = 700"
check "SELECT EMP_NO FROM EMPLOYEE WHERE RATE = -0.25"
check "SELECT EMP_NO FROM EMPLOYEE WHERE FIRST_NAME = 'Mr ' || 'Big'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (100, 600, 900)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID NOT IN (0, 1)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NOT (DEPT_ID IN (2, 3) OR SALARY = 1)"
check "SELECT EMPLOYEE.EMP_NO FROM EMPLOYEE, DEPARTMENT WHERE EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_NO"
check "SELECT E.EMP_NO FROM EMPLOYEE E WHERE E.SALARY > 1000"
check "SELECT e.EMP_NO FROM EMPLOYEE e WHERE e.SALARY > 1000"
check "SELECT EMPLOYEE.EMP_NO FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_NO"
check "SELECT E.EMP_NO FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO WHERE D.BUDGET > 100"
check "SELECT E.EMP_NO FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO AND E.SALARY > D.BUDGET"

# --- slice 3: outer joins, chains, int64, built-in functions -----------
check "SELECT E.EMP_NO FROM EMPLOYEE E LEFT JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO"
check "SELECT E.EMP_NO FROM EMPLOYEE E LEFT OUTER JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO"
check "SELECT E.EMP_NO FROM EMPLOYEE E RIGHT JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO"
check "SELECT E.EMP_NO FROM EMPLOYEE E FULL JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO"
check "SELECT E.EMP_NO FROM EMPLOYEE E LEFT JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO WHERE D.DEPT_NO IS NULL"
check "SELECT E.EMP_NO FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO JOIN PROJECT P2 ON P2.LEAD_NO = E.EMP_NO"
check "SELECT E.EMP_NO FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO LEFT JOIN PROJECT P2 ON P2.LEAD_NO = E.EMP_NO"
check "SELECT E.EMP_NO FROM EMPLOYEE E LEFT JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO AND D.BUDGET > 0"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY = 5000000000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY <> -9000000000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE UPPER(FIRST_NAME) = 'ROBERT'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE LOWER(FIRST_NAME) LIKE 'rob%'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CHAR_LENGTH(FIRST_NAME) BETWEEN 3 AND 6"
check "SELECT EMP_NO FROM EMPLOYEE WHERE OCTET_LENGTH(FIRST_NAME) = CHAR_LENGTH(FIRST_NAME)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SUBSTRING(FIRST_NAME FROM 2 FOR 3) = 'obe'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE TRIM(FIRST_NAME) = 'Ann'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE TRIM(TRAILING '.' FROM FIRST_NAME) = 'Dr'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE UPPER(TRIM(FIRST_NAME)) = 'ANN'"
check "SELECT E.EMP_NO FROM EMPLOYEE E JOIN DEPARTMENT D ON UPPER(D.DNAME) = UPPER(E.FIRST_NAME)"

# --- slice 4: CAST, CASE, COALESCE, NULLIF, IIF ------------------------
check "SELECT EMP_NO FROM EMPLOYEE WHERE CAST(SALARY AS BIGINT) > 40000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CAST(SALARY AS NUMERIC(9,2)) = 100.25"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CAST(SALARY AS NUMERIC(4,1)) = 5.5"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CAST(SALARY AS DECIMAL(6,3)) = 1.125"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CAST(EMP_NO AS VARCHAR(8)) = '7'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CAST(FIRST_NAME AS CHAR(12)) = 'Robert'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CAST(FIRST_NAME AS TIMESTAMP) IS NULL"
check "SELECT EMP_NO FROM EMPLOYEE WHERE HIRED = CAST(FIRST_NAME AS DATE)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN SALARY > 40000 THEN 1 ELSE 0 END = 1"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN SALARY > 40000 THEN 'hi' WHEN SALARY > 10000 THEN 'mid' ELSE 'lo' END = 'mid'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN RATE IS NULL THEN 0.5 ELSE 2 END = 2"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN SALARY > 40000 THEN 9000000000 ELSE 1 END > 5"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN DEPT_ID = 600 THEN CAST(SALARY AS SMALLINT) ELSE CAST(DEPT_ID AS SMALLINT) END = 3"
check "SELECT EMP_NO FROM EMPLOYEE WHERE IIF(SALARY > 40000, 'big', 'small') = 'big'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN SALARY > 40000 THEN 1 END = 1"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE DEPT_ID WHEN 100 THEN 'sales' WHEN 600 THEN 'eng' ELSE 'other' END = 'eng'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE DEPT_ID WHEN 100 THEN 1 WHEN 600 THEN 2 END = 2"
check "SELECT EMP_NO FROM EMPLOYEE WHERE COALESCE(RATE, 0) > 1"
check "SELECT EMP_NO FROM EMPLOYEE WHERE COALESCE(DEPT_ID, EMP_NO, 0) = 600"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NULLIF(0, 0) IS NULL"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NULLIF('x', FIRST_NAME) = 'x'"
check "SELECT E.EMP_NO FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO WHERE CASE WHEN D.BUDGET > 100 THEN 1 ELSE 0 END = 1"
check "SELECT EMP_NO FROM EMPLOYEE WHERE UPPER(CAST(EMP_NO AS VARCHAR(5))) = '7'"
check "SELECT EMP_NO FROM EMPLOYEE WHERE COALESCE(NULLIF(1, 2), 0) = 1"

# --- slice 5: subquery predicates ---------------------------------------
check "SELECT EMP_NO FROM EMPLOYEE WHERE EXISTS (SELECT 1 FROM DEPARTMENT WHERE DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_ID)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENT WHERE DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_ID)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SINGULAR (SELECT 1 FROM PROJECT WHERE PROJECT.LEAD_NO = EMPLOYEE.EMP_NO)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (SELECT DEPT_NO FROM DEPARTMENT)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (SELECT DEPT_NO FROM DEPARTMENT WHERE DEPARTMENT.BUDGET > 100)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID NOT IN (SELECT DEPT_NO FROM DEPARTMENT WHERE DEPARTMENT.BUDGET = 0)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > ALL (SELECT BUDGET FROM DEPARTMENT)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY >= SOME (SELECT BUDGET FROM DEPARTMENT D WHERE D.DEPT_NO = EMPLOYEE.DEPT_ID)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE EXISTS (SELECT 1 FROM DEPARTMENT WHERE DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_ID) AND SALARY > 1000"
check "SELECT EMP_NO FROM EMPLOYEE WHERE EXISTS (SELECT 1 FROM DEPARTMENT WHERE DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_ID) OR EXISTS (SELECT 1 FROM PROJECT WHERE PROJECT.LEAD_NO = EMPLOYEE.EMP_NO)"
check "SELECT E.EMP_NO FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO WHERE EXISTS (SELECT 1 FROM PROJECT P2 WHERE P2.LEAD_NO = E.EMP_NO)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (SELECT X.DEPT_NO FROM DEPARTMENT X WHERE X.DNAME = 'eng')"
check "SELECT EMP_NO FROM EMPLOYEE WHERE NOT (SALARY < ALL (SELECT BUDGET FROM DEPARTMENT))"
check "SELECT EMP_NO FROM EMPLOYEE WHERE UPPER(FIRST_NAME) IN (SELECT DNAME FROM DEPARTMENT)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN EXISTS (SELECT 1 FROM DEPARTMENT WHERE DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_ID) THEN 1 ELSE 0 END = 1"

# --- slice 6: DISTINCT, scalar subselects, derived tables, UNION -------
check "SELECT DISTINCT DEPT_ID FROM EMPLOYEE"
check "SELECT DISTINCT DEPT_ID, SALARY FROM EMPLOYEE WHERE SALARY > 100"
check "SELECT DISTINCT E.DEPT_ID FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_NO"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY = (SELECT BUDGET FROM DEPARTMENT WHERE DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_ID)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY = (SELECT BUDGET FROM DEPARTMENT)"
check "SELECT EMP_NO FROM EMPLOYEE WHERE (SELECT D.BUDGET FROM DEPARTMENT D WHERE D.DEPT_NO = EMPLOYEE.DEPT_ID) > 400"
check "SELECT EMP_NO FROM EMPLOYEE WHERE SALARY + (SELECT BUDGET FROM DEPARTMENT WHERE DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_ID) > 500"
check "SELECT X.EMP_NO FROM (SELECT EMP_NO FROM EMPLOYEE) X"
check "SELECT X.EMP_NO FROM (SELECT EMP_NO, SALARY FROM EMPLOYEE WHERE SALARY > 100) X WHERE X.EMP_NO < 50"
check "SELECT X.EMP_NO FROM (SELECT EMP_NO, DEPT_ID FROM EMPLOYEE) X JOIN DEPARTMENT D ON X.DEPT_ID = D.DEPT_NO"
check "SELECT DEPT_ID FROM EMPLOYEE UNION SELECT DEPT_NO FROM DEPARTMENT"
check "SELECT DEPT_ID FROM EMPLOYEE UNION ALL SELECT DEPT_NO FROM DEPARTMENT"
check "SELECT DEPT_ID, SALARY FROM EMPLOYEE UNION SELECT DEPT_NO, BUDGET FROM DEPARTMENT"
check "SELECT DEPT_ID FROM EMPLOYEE WHERE SALARY > 100 UNION ALL SELECT DEPT_NO FROM DEPARTMENT WHERE DEPARTMENT.BUDGET > 50"
check "SELECT DEPT_ID FROM EMPLOYEE UNION ALL SELECT DEPT_NO FROM DEPARTMENT UNION ALL SELECT LEAD_NO FROM PROJECT"
check "SELECT E.DEPT_ID FROM EMPLOYEE E UNION SELECT D.DEPT_NO FROM DEPARTMENT D"
check "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (SELECT DEPT_NO FROM DEPARTMENT) AND SALARY = (SELECT BUDGET FROM DEPARTMENT WHERE DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_ID)"

# --- refusals: outside the converted surface, never guessed ------------
refuse "SELECT EMP_NO FROM EMPLOYEE ORDER BY EMP_NO"
refuse "SELECT COUNT(*) FROM EMPLOYEE"
refuse "SELECT EMPLOYEE.EMP_NO FROM EMPLOYEE, DEPARTMENT WHERE DEPT_ID = 1"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE FOO(SALARY) = 1"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE DECODE(DEPT_ID, 1, 2) = 1"
# (FOR-less SUBSTRING - flipped in slice 43: the engine fills the
# length with INT MAX)
check "SELECT EMP_NO FROM EMPLOYEE WHERE SUBSTRING(FIRST_NAME FROM 2) = 'x'"
refuse "SELECT E.EMP_NO FROM EMPLOYEE E CROSS JOIN DEPARTMENT D"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN SALARY > 1 THEN SALARY ELSE 0 END = 1"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE NULLIF(SALARY, 0) = 1"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE CAST(SALARY AS FLOAT) = 1"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE CASE WHEN SALARY > 1 THEN 'x' ELSE 0 END = 'x'"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE EXISTS (SELECT 1 FROM DEPARTMENT D JOIN PROJECT P2 ON D.DEPT_NO = P2.LEAD_NO)"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (SELECT DEPT_NO, BUDGET FROM DEPARTMENT)"
refuse "SELECT DEPT_ID FROM EMPLOYEE UNION SELECT DEPT_NO FROM DEPARTMENT UNION ALL SELECT LEAD_NO FROM PROJECT"
refuse "SELECT DISTINCT UPPER(FIRST_NAME) FROM EMPLOYEE"
refuse "SELECT X.EMP_NO FROM (SELECT EMP_NO FROM EMPLOYEE)"
refuse "SELECT EMP_NO FROM EMPLOYEE WHERE FIRST_NAME IN ('Ann', 'Bob')"

exit $fail
