#!/bin/bash
# SQL -> BLR, oracle number TWO: RDB$PROCEDURE_BLR. Views cannot hold
# ORDER BY - a procedure's FOR SELECT ... DO SUSPEND body can, and the
# engine stores ITS compiled BLR verbatim too. For every statement in
# the battery: the ENGINE runs the CREATE PROCEDURE and fire-crab-dsql
# compiles the identical text. THE BYTES MUST MATCH - the whole body,
# wrapper and all: message layout, declares, stall, labels, the FOR
# loop, both sends.
#
# The battery goes beyond the unit-test probe pins - fresh parameter
# types, fresh sort keys - so the gate tests the COMPILER, not the
# probe notebook. Refusals must answer REFUSED.
#
#   qa/dsql-proc-blr.sh
#
# Builds its own scratch database.

set -u
FCDSQL="${FCDSQL:-$(dirname "$0")/../target/release/fcdsql}"
ISQL="${ISQL:-isql}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
DB="$D/fc-dsqlproc.fdb"

mkdir -p "$D"; rm -f "$DB"
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF >/dev/null 2>&1 || { echo "FAIL create"; exit 1; }
CREATE DATABASE '$DB' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
CREATE TABLE EMPLOYEE (
  EMP_NO INTEGER NOT NULL,
  DEPT_ID INTEGER,
  SALARY INTEGER,
  FIRST_NAME VARCHAR(20),
  RATE NUMERIC(9,2),
  HIRED DATE
);
CREATE EXCEPTION E_BAD 'bad data';
COMMIT;
SET TERM ^ ;
CREATE PROCEDURE HELPER0 (P1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = :P1; END^
CREATE PROCEDURE HELPER1 RETURNS (R1 INTEGER) AS BEGIN R1 = 7; SUSPEND; END^
SET TERM ; ^
COMMIT;
EOF

fail=0
n=0
check() { # <create procedure statement>
    n=$((n + 1))
    name="GP$n"
    stmt="CREATE PROCEDURE $name ${1}"
    got=$("$FCDSQL" "$stmt")
    "$ISQL" -q -b -user "$U" -pas "$P" "$DB" >/dev/null 2>&1 <<SQL
SET TERM ^ ;
$stmt^
SET TERM ; ^
COMMIT;
SQL
    want=$("$ISQL" -q -b -user "$U" -pas "$P" "$DB" 2>/dev/null <<SQL | tr -d ' \n'
SET HEADING OFF;
SELECT CAST(CAST(RDB\$PROCEDURE_BLR AS BLOB SUB_TYPE 0) AS VARCHAR(900) CHARACTER SET OCTETS) FROM RDB\$PROCEDURES WHERE RDB\$PROCEDURE_NAME = '$name';
SQL
)
    if [ -z "$want" ]; then
        echo "DIFF [$stmt] - the engine did not store a procedure (bad battery statement?)"
        fail=1
    elif [ "$got" = "$want" ]; then
        echo "OK   $stmt"
    else
        echo "DIFF $stmt"
        echo "     engine: $want"
        echo "     fcdsql: $got"
        fail=1
    fi
}
refuse() {
    if [ "$("$FCDSQL" "$1")" = "REFUSED" ]; then
        echo "OK   refused: $1"
    else
        echo "DIFF [$1] compiled instead of refusing"; fail=1
    fi
}

# --- the battery -------------------------------------------------------
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE ORDER BY SALARY DESC INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > 1000 ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 VARCHAR(20)) AS BEGIN FOR SELECT EMP_NO, FIRST_NAME FROM EMPLOYEE ORDER BY FIRST_NAME, EMP_NO DESC INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 NUMERIC(9,2)) AS BEGIN FOR SELECT RATE FROM EMPLOYEE WHERE RATE IS NOT NULL INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 DATE) AS BEGIN FOR SELECT HIRED FROM EMPLOYEE ORDER BY HIRED INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 SMALLINT, R2 BIGINT) AS BEGIN FOR SELECT DEPT_ID, SALARY FROM EMPLOYEE WHERE SALARY BETWEEN 1 AND 90000 INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE UPPER(FIRST_NAME) LIKE 'R%' ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 CHAR(5)) AS BEGIN FOR SELECT FIRST_NAME FROM EMPLOYEE WHERE CASE WHEN SALARY > 100 THEN 1 ELSE 0 END = 1 INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (100, 600) AND SALARY + 1 > 500 ORDER BY DEPT_ID, EMP_NO INTO :R1 DO SUSPEND; END"
# INTO in a different order than RETURNS: variables follow the NAMES
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, EMP_NO FROM EMPLOYEE INTO :R2, :R1 DO SUSPEND; END"

# --- slice 8: aggregates and GROUP BY ----------------------------------
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT COUNT(*) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT SUM(SALARY) FROM EMPLOYEE WHERE DEPT_ID = 600 INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 NUMERIC(9,2)) AS BEGIN FOR SELECT AVG(RATE) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT MIN(SALARY), MAX(SALARY) FROM EMPLOYEE INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT COUNT(FIRST_NAME) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE GROUP BY DEPT_ID INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, SUM(SALARY) FROM EMPLOYEE WHERE SALARY > 0 GROUP BY DEPT_ID ORDER BY DEPT_ID INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE GROUP BY DEPT_ID HAVING COUNT(*) > 2 INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, MAX(SALARY) FROM EMPLOYEE GROUP BY DEPT_ID HAVING MIN(SALARY) > 100 AND DEPT_ID > 0 ORDER BY DEPT_ID DESC INTO :R1, :R2 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT SUM(SALARY * 12) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"

# --- slice 9: input parameters -----------------------------------------
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > :P1 INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER, P2 VARCHAR(20)) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID = :P1 AND FIRST_NAME = :P2 ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "(LO INTEGER, HI INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY BETWEEN :LO AND :HI INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE WHERE SALARY > :P1 GROUP BY DEPT_ID INTO :R1, :R2 DO SUSPEND; END"
check "(P1 NUMERIC(9,2)) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE RATE * 2 > :P1 INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE DEPT_ID IN (:P1, 600) INTO :R1 DO SUSPEND; END"
# an UNUSED input still shapes message 0 and the receive wrapper
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE INTO :R1 DO SUSPEND; END"

# --- slice 10: SELECT INTO, FIRST/SKIP, DISTINCT aggregates ------------
check "RETURNS (R1 INTEGER) AS BEGIN SELECT COUNT(*) FROM EMPLOYEE INTO :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN SELECT SUM(SALARY) FROM EMPLOYEE WHERE DEPT_ID = 600 INTO :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN SELECT EMP_NO FROM EMPLOYEE WHERE EMP_NO = 7 INTO :R1; END"
check "RETURNS (R1 INTEGER) AS BEGIN SELECT EMP_NO FROM EMPLOYEE INTO :R1; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN SELECT MAX(SALARY) FROM EMPLOYEE WHERE DEPT_ID = :P1 INTO :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT FIRST 10 EMP_NO FROM EMPLOYEE ORDER BY SALARY DESC INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT FIRST 10 SKIP 5 EMP_NO FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT SKIP 1 EMP_NO FROM EMPLOYEE WHERE SALARY > 0 ORDER BY EMP_NO INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT COUNT(DISTINCT DEPT_ID) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
check "RETURNS (R1 INTEGER) AS BEGIN FOR SELECT SUM(DISTINCT SALARY) FROM EMPLOYEE WHERE SALARY > 0 INTO :R1 DO SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(DISTINCT FIRST_NAME) FROM EMPLOYEE WHERE SALARY > :P1 GROUP BY DEPT_ID INTO :R1, :R2 DO SUSPEND; END"

# --- slice 14: general multi-statement bodies --------------------------
check "RETURNS (R1 INTEGER) AS BEGIN R1 = 42; SUSPEND; END"
check "RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN R1 = 1; R2 = R1 + 1; SUSPEND; R1 = 2; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER = 0; BEGIN WHILE (V1 < P1) DO V1 = V1 + 1; R1 = V1; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN IF (P1 > 100) THEN R1 = 100; ELSE R1 = P1; SUSPEND; END"
check "(P1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = :P1; END"
check "(P1 INTEGER, P2 INTEGER) AS BEGIN UPDATE EMPLOYEE SET SALARY = :P2 WHERE EMPLOYEE.EMP_NO = :P1; END"
check "(P1 INTEGER) AS BEGIN INSERT INTO EMPLOYEE (EMP_NO, SALARY) VALUES (:P1, 0); END"
check "RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; BEGIN SELECT COUNT(*) FROM EMPLOYEE INTO :V1; R1 = V1 * 2; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > :P1 ORDER BY EMP_NO INTO :R1 DO SUSPEND; R1 = 0; SUSPEND; END"
check "(P1 INTEGER) AS BEGIN IF (P1 > 0) THEN INSERT INTO EMPLOYEE (EMP_NO) VALUES (:P1); ELSE DELETE FROM EMPLOYEE WHERE EMPLOYEE.EMP_NO = 0; END"

# --- slice 15: calls, exceptions, exit ---------------------------------
check "AS BEGIN EXECUTE PROCEDURE HELPER0(42); END"
check "(P1 INTEGER) AS BEGIN EXECUTE PROCEDURE HELPER0(:P1 + 1); END"
check "RETURNS (R1 INTEGER) AS BEGIN EXECUTE PROCEDURE HELPER1 RETURNING_VALUES :R1; SUSPEND; END"
check "RETURNS (R1 INTEGER) AS DECLARE V1 INTEGER; BEGIN EXECUTE PROCEDURE HELPER1 RETURNING_VALUES :V1; R1 = V1 * 10; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN IF (P1 < 0) THEN EXCEPTION E_BAD; R1 = P1; SUSPEND; END"
check "(P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN R1 = P1; IF (P1 = 0) THEN EXIT; SUSPEND; END"
check "AS BEGIN IF (1 = 0) THEN EXCEPTION E_BAD; ELSE EXIT; END"
check "RETURNS (R1 INTEGER) AS BEGIN DELETE FROM EMPLOYEE WHERE EMPLOYEE.SALARY < 0; SELECT COUNT(*) FROM EMPLOYEE INTO :R1; SUSPEND; END"

# --- refusals ----------------------------------------------------------
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE ORDER BY 1 INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE INTO :WRONG DO SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE E INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE INTO :R1, :R2 DO SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT EMP_NO FROM EMPLOYEE WHERE SALARY > :NOPE INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) RETURNS (R1 INTEGER, R2 INTEGER) AS BEGIN FOR SELECT DEPT_ID, COUNT(*) FROM EMPLOYEE GROUP BY DEPT_ID HAVING COUNT(*) > :P1 INTO :R1, :R2 DO SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) RETURNS (R1 INTEGER) AS BEGIN FOR SELECT FIRST :P1 EMP_NO FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X RETURNS (R1 INTEGER) AS BEGIN FOR SELECT FIRST 2 COUNT(*) FROM EMPLOYEE INTO :R1 DO SUSPEND; END"
refuse "CREATE PROCEDURE X (P1 INTEGER) AS BEGIN SUSPEND; END"

exit $fail
