#!/bin/bash
# An identity column survives an ALTER TABLE.
#
# ALTER TABLE rebuilds a relation's RDB$RUNTIME from its current fields (the
# engine resolves columns through it). An identity column carries three extra
# runtime segments - the not-null marker, its generator name (tag 22) and its
# identity type (tag 23) - and the engine draws the next value from those. The
# first version of the rebuild listed id / name / source / length / position /
# not-null / default and stopped, so adding a column to a table with an identity
# quietly stripped the identity from the summary: the catalog kept
# RDB$GENERATOR_NAME, but the runtime no longer named it, and an insert failed on
# the (still-enforced) not-null. The rebuild must re-emit the identity segments.
#
# The differential is the engine:
#   1. fire-crab and the engine each create an identity table and ALTER TABLE
#      ADD a column, on two copies; the rebuilt RDB$RUNTIME is compared BYTE FOR
#      BYTE (the identity segments survive);
#   2. the engine still auto-generates the identity on insert after the ALTER;
#   3. gbak round trip and gfix -v -full on fire-crab's raw file.
#
#   qa/serve-real-identityalter.sh [port]
#
# Builds its own scratch databases.

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"; GFIX="${GFIX:-gfix}"; GBAK="${GBAK:-gbak}"
PORT="${1:-4224}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
WORK="$D/fc-ida-work.fdb"; REF="$D/fc-ida-ref.fdb"
FBK="$D/fc-ida-work.fbk"; RST="$D/fc-ida-rst.fdb"

command -v node >/dev/null 2>&1 || { echo "SKIP node not found"; exit 0; }
mkdir -p "$D"; rm -f "$WORK" "$REF" "$FBK" "$RST"

C1="CREATE TABLE T (ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 5 INCREMENT BY 2), N VARCHAR(3))"
C2="ALTER TABLE T ADD E INTEGER"

"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL ref db"; exit 1; }
CREATE DATABASE '$REF' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
$C1; $C2;
COMMIT;
EOF
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL work db"; exit 1; }
CREATE DATABASE '$WORK' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
COMMIT;
EOF

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-ida.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$WORK" "$REF" "$FBK" "$RST"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
# The readiness probe above answers "SOMETHING is listening", not "OUR
# server is listening". If the port was already taken, fcwire exited at
# bind and every check below runs against the OTHER server - a gate that
# reports success while measuring nothing. Fatal, not a warning.
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

strip() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
node_once() {
    FC_DB="$WORK" FC_PORT="$PORT" FC_Q="$1" timeout 15 node -e '
      process.on("uncaughtException",()=>{console.log("CONN_ERR");process.exit(1);});
      const F=require("node-firebird");
      F.attach({host:"127.0.0.1",port:+process.env.FC_PORT,database:process.env.FC_DB,
                user:"SYSDBA",password:"masterkey"},(e,db)=>{
        if(e){console.log("CONN_ERR");process.exit(1);}
        db.query(process.env.FC_Q,(e2,r)=>{
          console.log(e2?("ERR "+(e2.message||"").split("\n")[0]):"OK");
          db.detach();process.exit(0);});
      });' 2>/dev/null
}
node_run() {
    n=0
    while [ $n -lt 10 ]; do
        r=$(node_once "$1")
        case "$r" in
            *CONN_ERR*|"") n=$((n + 1)); sleep 0.3 ;;
            *) printf '%s' "$r" | strip; return ;;
        esac
    done
    echo CONN_ERR
}

fail=0
check() { # <label> <got> <want>
    if [ "$2" = "$3" ]; then echo "OK   $1"; else
        echo "DIFF $1"; echo "     want: $3"; echo "     got:  $2"; fail=1; fi
}

check "fire-crab creates the identity table" "$(node_run "$C1")" "OK"
check "fire-crab ALTER TABLE ADD (rebuilds the runtime)" "$(node_run "$C2")" "OK"
kill $srv 2>/dev/null; wait $srv 2>/dev/null

# --- 1. the rebuilt runtime, byte for byte ----------------------------
rtq() { # <file>
    b=$("$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>/dev/null <<'SQL' | grep -oE '[0-9a-f]+:[0-9a-f]+' | head -1
SET LIST ON;
SELECT RDB$RUNTIME FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T';
SQL
)
    [ -n "$b" ] || { echo "(none)"; return; }
    rm -f /tmp/fc-ida-rt.bin
    printf 'BLOBDUMP %s /tmp/fc-ida-rt.bin;\n' "$b" | "$ISQL" -q -user "$U" -pas "$P" "$1" >/dev/null 2>&1
    od -An -tu1 -v /tmp/fc-ida-rt.bin | tr '\n' ' ' | tr -s ' ' | strip
}
work_rt=$(rtq "$WORK")
check "the rebuilt RDB\$RUNTIME matches the engine byte for byte after the ALTER" "$work_rt" "$(rtq "$REF")"
case "$work_rt" in
    *" 22 82 68 66 "*" 23 "*) echo "OK   the runtime still carries the identity generator (22) and type (23)" ;;
    *) echo "DIFF the runtime lost the identity segments"; fail=1 ;;
esac

# --- 2. the identity still auto-generates after the ALTER -------------
"$ISQL" -q -b -user "$U" -pas "$P" "$WORK" >/dev/null 2>&1 <<'SQL'
INSERT INTO T (N) VALUES ('a');
INSERT INTO T (N) VALUES ('b');
COMMIT;
SQL
applied=$("$ISQL" -q -b -user "$U" -pas "$P" "$WORK" 2>&1 <<'SQL' | strip | grep -v '^$' | tr '\n' ',' | sed 's/,$//'
SET HEADING OFF;
SELECT TRIM(N)||':'||ID FROM T ORDER BY N;
SQL
)
check "the identity still auto-generates after the ALTER (5, then 7)" "$applied" "a:5,b:7"

# --- 3. gbak and gfix ------------------------------------------------
if "$GBAK" -b -g -user "$U" -pas "$P" "$WORK" "$FBK" >/tmp/fc-ida-backup.log 2>&1; then
    echo "OK   gbak backs up the database fire-crab wrote"
else
    echo "DIFF gbak backup"; cat /tmp/fc-ida-backup.log; fail=1
fi
"$GBAK" -c -user "$U" -pas "$P" "$FBK" "$RST" >/tmp/fc-ida-restore.log 2>&1
rc=$?
if [ $rc -eq 0 ] && ! grep -qiE "error" /tmp/fc-ida-restore.log; then
    echo "OK   gbak RESTORES it"
else
    echo "DIFF gbak restore (exit $rc)"; grep -iE "error|cannot" /tmp/fc-ida-restore.log | head; fail=1
fi
valw=$("$GFIX" -v -full -user "$U" -pas "$P" "$WORK" 2>&1)
check "gfix -v -full clean (fc's raw file)" "$(printf '%s' "$valw" | strip)" ""

exit $fail
