#!/bin/bash
# ALTER TABLE ALTER COLUMN ... SET GENERATED { ALWAYS | BY DEFAULT }.
#
# Change an identity column's kind: ALWAYS (RDB$IDENTITY_TYPE 0) forbids an
# explicit value on insert, BY DEFAULT (1) allows one. It patches the column's
# RDB$IDENTITY_TYPE and rebuilds the relation's RDB$RUNTIME so its identity-type
# segment (tag 23) follows; the generator and its value are untouched. A SET
# GENERATED on a non-identity column is refused.
#
# The differential is the engine (both databases start with the same identity
# table and a plain table; then fire-crab ALTERs one copy and the engine the
# other):
#   1. after SET GENERATED ALWAYS, RDB$IDENTITY_TYPE matches and the generator
#      name is unchanged; the RDB$RUNTIME is compared BYTE FOR BYTE;
#   2. changing it back to BY DEFAULT matches too;
#   3. a SET GENERATED on a non-identity column is refused on both;
#   4. gbak round trip and gfix -v -full on fire-crab's raw file.
#
#   qa/serve-real-identitygenerated.sh [port]
#
# Builds its own scratch databases.

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"; GFIX="${GFIX:-gfix}"; GBAK="${GBAK:-gbak}"
PORT="${1:-4225}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
WORK="$D/fc-idg-work.fdb"; REF="$D/fc-idg-ref.fdb"
FBK="$D/fc-idg-work.fbk"; RST="$D/fc-idg-rst.fdb"

command -v node >/dev/null 2>&1 || { echo "SKIP node not found"; exit 0; }
mkdir -p "$D"; rm -f "$WORK" "$REF" "$FBK" "$RST"

SETUP="CREATE TABLE T (ID INTEGER GENERATED BY DEFAULT AS IDENTITY, N VARCHAR(3)); CREATE TABLE U (X INTEGER);"
A_ALW="ALTER TABLE T ALTER COLUMN ID SET GENERATED ALWAYS"
A_DEF="ALTER TABLE T ALTER COLUMN ID SET GENERATED BY DEFAULT"
R_NON="ALTER TABLE U ALTER COLUMN X SET GENERATED ALWAYS"

for f in "$REF" "$WORK"; do
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL db $f"; exit 1; }
CREATE DATABASE '$f' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
$SETUP
COMMIT;
EOF
done
"$ISQL" -q -b -user "$U" -pas "$P" "$REF" >/dev/null 2>&1 <<EOF
$A_ALW;
COMMIT;
EOF
eng_non=$("$ISQL" -q -b -user "$U" -pas "$P" "$REF" 2>&1 <<EOF
$R_NON;
EOF
)

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-idg.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$WORK" "$REF" "$FBK" "$RST"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
# The readiness probe above answers "SOMETHING is listening", not "OUR
# server is listening". If the port was already taken, fcwire exited at
# bind and every check below runs against the OTHER server - a gate that
# reports success while measuring nothing. Fatal, not a warning.
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

strip() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
node_once() {
    FC_DB="$WORK" FC_PORT="$PORT" FC_Q="$1" timeout 15 node -e '
      process.on("uncaughtException",()=>{console.log("CONN_ERR");process.exit(1);});
      const F=require("node-firebird");
      F.attach({host:"127.0.0.1",port:+process.env.FC_PORT,database:process.env.FC_DB,
                user:"SYSDBA",password:"masterkey"},(e,db)=>{
        if(e){console.log("CONN_ERR");process.exit(1);}
        db.query(process.env.FC_Q,(e2,r)=>{
          console.log(e2?("ERR "+(e2.message||"").split("\n")[0]):"OK");
          db.detach();process.exit(0);});
      });' 2>/dev/null
}
node_run() {
    n=0
    while [ $n -lt 10 ]; do
        r=$(node_once "$1")
        case "$r" in
            *CONN_ERR*|"") n=$((n + 1)); sleep 0.3 ;;
            *) printf '%s' "$r" | strip; return ;;
        esac
    done
    echo CONN_ERR
}

fail=0
check() { # <label> <got> <want>
    if [ "$2" = "$3" ]; then echo "OK   $1"; else
        echo "DIFF $1"; echo "     want: $3"; echo "     got:  $2"; fail=1; fi
}
idtq() { "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT 'idt='||RDB$IDENTITY_TYPE||'|gen='||TRIM(RDB$GENERATOR_NAME) FROM RDB$RELATION_FIELDS WHERE RDB$FIELD_NAME='ID';
SQL
}
rtq() {
    b=$("$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>/dev/null <<'SQL' | grep -oE '[0-9a-f]+:[0-9a-f]+' | head -1
SET LIST ON;
SELECT RDB$RUNTIME FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T';
SQL
)
    [ -n "$b" ] || { echo "(none)"; return; }
    rm -f /tmp/fc-idg-rt.bin
    printf 'BLOBDUMP %s /tmp/fc-idg-rt.bin;\n' "$b" | "$ISQL" -q -user "$U" -pas "$P" "$1" >/dev/null 2>&1
    od -An -tu1 -v /tmp/fc-idg-rt.bin | tr '\n' ' ' | tr -s ' ' | strip
}

check "fire-crab: SET GENERATED ALWAYS" "$(node_run "$A_ALW")" "OK"
r=$(node_run "$R_NON")
case "$r" in ERR*) echo "OK   SET GENERATED on a non-identity column is refused" ;;
    *) echo "DIFF non-identity SET GENERATED accepted"; echo "     $r"; fail=1 ;; esac
case "$eng_non" in *[Ff]ailed*|*[Ee]rror*) echo "OK   the engine refuses it too" ;;
    *) echo "DIFF engine did not refuse"; echo "     $eng_non"; fail=1 ;; esac

check "RDB\$IDENTITY_TYPE is now 0 (ALWAYS), generator kept" "$(idtq "$WORK")" "$(idtq "$REF")"
case "$(idtq "$WORK")" in *"idt=0|gen=RDB\$1"*) echo "OK   ALWAYS with the generator unchanged" ;;
    *) echo "DIFF unexpected"; echo "     $(idtq "$WORK")"; fail=1 ;; esac
check "the RDB\$RUNTIME matches the engine byte for byte (identity type segment)" "$(rtq "$WORK")" "$(rtq "$REF")"

check "fire-crab: SET GENERATED BY DEFAULT (back)" "$(node_run "$A_DEF")" "OK"
kill $srv 2>/dev/null; wait $srv 2>/dev/null
"$ISQL" -q -b -user "$U" -pas "$P" "$REF" >/dev/null 2>&1 <<EOF
$A_DEF;
COMMIT;
EOF
check "back to BY DEFAULT: RDB\$IDENTITY_TYPE 1 matches" "$(idtq "$WORK")" "$(idtq "$REF")"
check "the RDB\$RUNTIME matches the engine after changing back" "$(rtq "$WORK")" "$(rtq "$REF")"

# gbak and gfix
if "$GBAK" -b -g -user "$U" -pas "$P" "$WORK" "$FBK" >/tmp/fc-idg-backup.log 2>&1; then
    echo "OK   gbak backs up the database fire-crab wrote"
else
    echo "DIFF gbak backup"; cat /tmp/fc-idg-backup.log; fail=1
fi
"$GBAK" -c -user "$U" -pas "$P" "$FBK" "$RST" >/tmp/fc-idg-restore.log 2>&1
rc=$?
if [ $rc -eq 0 ] && ! grep -qiE "error" /tmp/fc-idg-restore.log; then
    echo "OK   gbak RESTORES it"
else
    echo "DIFF gbak restore (exit $rc)"; grep -iE "error|cannot" /tmp/fc-idg-restore.log | head; fail=1
fi
valw=$("$GFIX" -v -full -user "$U" -pas "$P" "$WORK" 2>&1)
check "gfix -v -full clean (fc's raw file)" "$(printf '%s' "$valw" | strip)" ""

exit $fail
