#!/bin/bash
# OVERRIDING SYSTEM/USER VALUE, INSERT INTO <t> DEFAULT VALUES, and
# parameters in an INSERT..SELECT source - three recorded DML residuals,
# probed cell by cell against live Firebird 6. The laws this gate holds
# fire-crab to:
#
#   1. OVERRIDING USER VALUE SILENTLY DISCARDS the supplied value and
#      draws from the generator - it means the OPPOSITE of what it reads
#      like. OVERRIDING SYSTEM VALUE takes the user's value literally and
#      does NOT advance the generator, so the sequence falls behind the
#      table and Firebird never auto-syncs.
#   2. There are THREE distinct refusal vectors, chosen by METADATA and
#      never by the value: 335545134 (no identity column in the field
#      list - including a table with no identity at all), 335545137
#      (a GENERATED ALWAYS identity named with an explicit value and no
#      OVERRIDING), 335545135 (OSV against a GENERATED BY DEFAULT
#      identity). All three are PREPARE-time, one pre-quoted
#      "SCHEMA"."TBL" argument READ from the catalog (a table in S1 names
#      "S1"."TBL"), no isc_dsql_error wrapper. They are a TABLE verdict:
#      a VIEW target has no identity metadata to judge, so it must not be
#      judged at all.
#   3. The DEFAULT keyword is the sanctioned escape from the ALWAYS rule:
#      VALUES (DEFAULT, ...) succeeds where any other expression refuses,
#      and OVERRIDING does NOT make it literal. Explicit NULL is a hard
#      NOT NULL error (23000/335544347, at EXECUTE) on both identity
#      kinds - never a fallback to the generator - except that CELL 20
#      answers 335545135 INSTEAD, because the metadata check runs first.
#   4. INSERT INTO <t> DEFAULT VALUES applies every column DEFAULT, fires
#      the identity generator for BOTH identity kinds, and is still
#      subject to NOT NULL / CHECK / PK at execute. Its grammar admits NO
#      column list and NO OVERRIDING clause.
#   5. INSERT..SELECT resolves its target list, its unknown-table
#      refusal and its OVERRIDING decision at PREPARE; the implicit
#      target list is DECLARATION (position) order with COMPUTED columns
#      excluded; OSV leaves the generator alone for all N rows and OUV
#      advances it once PER ROW; a `?` in the source WHERE is described
#      from the compared column and binds at execute.
#
# The differential is the engine, statement by statement: two identical
# fixtures, fire-crab drives one through its wire server and the engine
# drives the other through its own (port 3050), and the VERDICT plus the
# RAW status vector (gdscode + pre-quoted args, in order) must match byte
# for byte. Durable state is re-read THROUGH THE ENGINE from the file
# fire-crab wrote; gbak round-trips it and gfix -v -full validates it.
#
# BOUND lines are the priced boundaries: fire-crab refuses where the
# engine answers, or both error with different detail. They are recorded,
# not counted as failures.
#
#   qa/serve-real-overriding.sh [port]
#
# Needs node (node-firebird on NODE_PATH) and the engine's own wire
# server listening on 3050 for the vector differential.

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"; GFIX="${GFIX:-gfix}"; GBAK="${GBAK:-gbak}"
PORT="${1:-4612}"
ENGPORT="${ENGPORT:-3050}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
WORK="$D/fc-ovr-work.fdb"; REF="$D/fc-ovr-ref.fdb"
FBK="$D/fc-ovr-work.fbk"; RST="$D/fc-ovr-rst.fdb"
VJS="$D/fc-ovr-vec.js"

command -v node >/dev/null 2>&1 || { echo "SKIP node not found"; exit 0; }
command -v "$ISQL" >/dev/null 2>&1 || { echo "SKIP isql not found"; exit 0; }
command -v nc >/dev/null 2>&1 && ! nc -z 127.0.0.1 "$ENGPORT" 2>/dev/null && {
    echo "SKIP engine wire server not reachable on port $ENGPORT (the vector differential needs it)"
    exit 0
}
mkdir -p "$D"; rm -f "$WORK" "$REF" "$FBK" "$RST"

# --- the two identical fixtures, both created by the engine ------------
# TA/TD are the identity matrix's ALWAYS / BY DEFAULT pair (their backing
# generators are RDB$1 and RDB$2). POSN has been through ALTER COLUMN ...
# POSITION so its FIELD_ID order differs from its POSITION order: the
# INSERT..SELECT implicit list must follow POSITION.
#
# S1.TA2/S1.TZ3 are the same ALWAYS / BY DEFAULT pair in a NON-PUBLIC
# schema - the vectors' qualifier must be READ from the catalog, not
# assumed. VTA is a view over VBASE: an INSERT there has no identity
# metadata of its own to judge. The identity tables are created in this
# order and the RDB$<n> counter is GLOBAL across schemas, so the backing
# generators are RDB$1 (TA), RDB$2 (TD), RDB$3 (BID), S1.RDB$4 (S1.TA2),
# S1.RDB$5 (S1.TZ3) and RDB$6 (VBASE).
SCHEMA="CREATE TABLE TA (ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, B VARCHAR(10));
CREATE TABLE TD (ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, B VARCHAR(10));
CREATE TABLE PLAIN (A INTEGER, B VARCHAR(10));
CREATE TABLE SRC (X INTEGER, Y VARCHAR(10));
CREATE TABLE PT (A INTEGER, B VARCHAR(10));
CREATE TABLE D_DEF (A INTEGER DEFAULT 42, B VARCHAR(10) DEFAULT 'dd');
CREATE TABLE D_NODEF (A INTEGER, B VARCHAR(10));
CREATE TABLE D_NN (A INTEGER NOT NULL, B VARCHAR(10) DEFAULT 'x');
CREATE TABLE D_NNDEF (A INTEGER DEFAULT 5 NOT NULL, B VARCHAR(10));
CREATE TABLE D_COMP (A INTEGER DEFAULT 3, C COMPUTED BY (A*10));
CREATE TABLE D_PK (A INTEGER DEFAULT 1 PRIMARY KEY, B VARCHAR(10));
CREATE TABLE CMP (A INTEGER, C COMPUTED BY (A*10), B VARCHAR(10));
CREATE TABLE POSN (P1 INTEGER, P2 INTEGER, P3 INTEGER);
CREATE TABLE BND (A INTEGER, B VARCHAR(10));
CREATE TABLE BCMP (A INTEGER DEFAULT 3, C COMPUTED BY (A*10));
CREATE TABLE BID (ID INTEGER GENERATED ALWAYS AS IDENTITY, B VARCHAR(10));
COMMIT;
CREATE SCHEMA S1;
COMMIT;
CREATE TABLE S1.TA2 (ID INTEGER GENERATED ALWAYS AS IDENTITY, B VARCHAR(10));
CREATE TABLE S1.TZ3 (ID INTEGER GENERATED BY DEFAULT AS IDENTITY, B VARCHAR(10));
CREATE TABLE VBASE (ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, B VARCHAR(10));
COMMIT;
CREATE VIEW VTA AS SELECT ID, B FROM VBASE;
COMMIT;
ALTER TABLE POSN ALTER COLUMN P3 POSITION 1;
COMMIT;
INSERT INTO SRC VALUES (7001,'s1');
INSERT INTO SRC VALUES (7002,'s2');
INSERT INTO SRC VALUES (7003,'s3');
COMMIT;"

for f in "$REF" "$WORK"; do
    "$ISQL" -q -b -user "$U" -pas "$P" <<EOF >/dev/null || { echo "FAIL create $f"; exit 1; }
CREATE DATABASE '$f' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
$SCHEMA
EOF
    # the vector differential attaches through the engine's OWN wire
    # server, which runs as another user: it must be able to open both
    # files (embedded isql created them 0660 as this user)
    chmod 666 "$f"
done

# --- the full-status probe: node-firebird's callback hook exposes the
# --- RAW status vector items (gdscode + params), exactly as they ride
# --- the wire - the engine's args arrive PRE-QUOTED and the comparison
# --- keeps them verbatim. PREFIX=n keeps only the first n items (used
# --- where fire-crab ships the generic Dynamic SQL Error and only the
# --- fact of a refusal is comparable). ARGS binds input parameters.
cat > "$VJS" <<'JS'
const cb = require("node-firebird/lib/callback");
const orig = cb.doCallback;
let lastStatus = null;
cb.doCallback = function (obj, callback) {
  if (obj && typeof obj === "object" && obj.status) lastStatus = obj.status;
  return orig(obj, function (err, res) {
    if (err && lastStatus) { err.fullStatus = lastStatus; lastStatus = null; }
    if (callback) callback(err, res);
  });
};
const F = require("node-firebird");
const args = JSON.parse(process.env.ARGS || "[]");
F.attach({host:"127.0.0.1", port:+process.env.PORT, database:process.env.DB,
          user:"SYSDBA", password:"masterkey"}, (e, db) => {
  if (e) { console.log("CONN_ERR"); process.exit(1); }
  db.query(process.env.STMT, args, (qe, rows) => {
    if (qe) {
      let v = qe.fullStatus || [];
      const n = +(process.env.PREFIX || 0);
      if (n > 0) v = v.slice(0, n);
      console.log("ERR " + JSON.stringify(v));
    } else {
      let out = "";
      try {
        const rs = Array.isArray(rows) ? rows : (rows ? [rows] : []);
        out = rs.map(r => Object.keys(r).map(k => {
          const v = r[k];
          return v === null ? "<null>" : (typeof v === "string" ? v.trim() : String(v));
        }).join("|")).join(";");
      } catch (x) { out = "?"; }
      console.log("OK " + out);
    }
    db.detach(); process.exit(0);
  });
});
JS

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-ovr.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$WORK" "$REF" "$FBK" "$RST" "$VJS"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
# "something is listening" is not "OUR server is listening": if the port
# was taken, every check below measures the other server. Fatal.
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

strip() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
run_once() { # <port> <db> <stmt> <argsjson> <prefix>
    PORT="$1" DB="$2" STMT="$3" ARGS="$4" PREFIX="$5" timeout 25 node "$VJS" 2>/dev/null
}
run() { # <port> <db> <stmt> [argsjson] [prefix] - retries connection races
    n=0
    while [ $n -lt 10 ]; do
        r=$(run_once "$1" "$2" "$3" "${4:-[]}" "${5:-0}")
        case "$r" in
            *CONN_ERR*|"") n=$((n + 1)); sleep 0.3 ;;
            *) printf '%s' "$r" | strip; return ;;
        esac
    done
    echo CONN_ERR
}

fail=0; checks=0; bounds=0
check() { # <label> <got> <want>
    checks=$((checks + 1))
    if [ "$2" = "$3" ]; then echo "OK   $1"; else
        echo "DIFF $1"; echo "     want: $3"; echo "     got:  $2"; fail=1; fi
}

# Run one statement on BOTH sides (fc on the work copy, engine on the
# ref copy - the two states advance in lockstep) and compare the verdict
# AND, on a refusal, the raw vector byte for byte. The wanted answer is
# always the ENGINE'S OWN, never hard-coded.
both() { # <label> <stmt> [argsjson] [prefix]
    got=$(run "$PORT" "$WORK" "$2" "${3:-[]}" "${4:-0}")
    want=$(run "$ENGPORT" "$REF" "$2" "${3:-[]}" "${4:-0}")
    check "$1" "$got" "$want"
}

# A PRICED BOUNDARY: fire-crab must ERROR, and what the engine does is
# recorded, not required. Never a silent pass - it still asserts fc did
# not answer.
bound() { # <label> <stmt> [argsjson]
    got=$(run "$PORT" "$WORK" "$2" "${3:-[]}" 1)
    want=$(run "$ENGPORT" "$REF" "$2" "${3:-[]}" 1)
    case "$got" in
        ERR*) bounds=$((bounds + 1)); echo "BOUND $1"; echo "      fc:  $got"; echo "      eng: $want" ;;
        *) checks=$((checks + 1)); echo "DIFF $1 - fire-crab ANSWERED where the boundary says refuse"
           echo "     got:  $got"; fail=1 ;;
    esac
}

# The generator reading, through the same wire on both sides. GEN_ID(g,0)
# must not itself move the sequence - the whole matrix depends on it.
gens() { # <label> <generator>
    both "$1 [GEN_ID($2,0)]" "SELECT GEN_ID($2,0) FROM RDB\$DATABASE"
}

# ======================================================================
# 1. The 24-cell matrix: ALWAYS x {omitted, explicit, NULL, DEFAULT} x
#    {no OVERRIDING, OSV, OUV}, then the same for BY DEFAULT. Each cell
#    compares the outcome AND the full vector; the generator is read
#    after every group, because CELL 05 and CELL 06 differ ONLY in
#    whether the sequence moved.
# ======================================================================
echo "--- 1. the 24-cell OVERRIDING matrix (GENERATED ALWAYS: TA / RDB\$1)"
both "CELL 01 ALWAYS omitted, no OVERRIDING - the generator draws" \
     "INSERT INTO TA (B) VALUES ('AL_OMIT_NO')"
gens "CELL 01 advanced 0 -> 1" 'RDB$1'
both "CELL 02 ALWAYS omitted + OSV - 335545134 (identity not in the field list)" \
     "INSERT INTO TA (B) OVERRIDING SYSTEM VALUE VALUES ('AL_OMIT_OS')"
both "CELL 03 ALWAYS omitted + OUV - 335545134" \
     "INSERT INTO TA (B) OVERRIDING USER VALUE VALUES ('AL_OMIT_OU')"
gens "CELL 02/03 refused with the generator UNMOVED" 'RDB$1'
both "CELL 04 ALWAYS explicit, no OVERRIDING - 335545137" \
     "INSERT INTO TA (ID,B) VALUES (1004,'AL_EXPL_NO')"
both "CELL 05 ALWAYS explicit + OSV - the user value lands" \
     "INSERT INTO TA (ID,B) OVERRIDING SYSTEM VALUE VALUES (1005,'AL_EXPL_OS')"
gens "CELL 05 did NOT advance the generator (the sequence falls behind)" 'RDB$1'
both "CELL 06 ALWAYS explicit + OUV - the value is DISCARDED" \
     "INSERT INTO TA (ID,B) OVERRIDING USER VALUE VALUES (1006,'AL_EXPL_OU')"
gens "CELL 06 DID advance the generator" 'RDB$1'
both "CELL 07 ALWAYS explicit NULL, no OVERRIDING - 335545137, not a default" \
     "INSERT INTO TA (ID,B) VALUES (NULL,'AL_NULL_NO')"
both "CELL 08 ALWAYS NULL + OSV - 23000/335544347 at EXECUTE" \
     "INSERT INTO TA (ID,B) OVERRIDING SYSTEM VALUE VALUES (NULL,'AL_NULL_OS')"
both "CELL 09 ALWAYS NULL + OUV - the NULL is discarded like any value" \
     "INSERT INTO TA (ID,B) OVERRIDING USER VALUE VALUES (NULL,'AL_NULL_OU')"
gens "CELL 07/08 left it alone, CELL 09 advanced it" 'RDB$1'
both "CELL 10 ALWAYS + DEFAULT keyword, no OVERRIDING - the escape hatch" \
     "INSERT INTO TA (ID,B) VALUES (DEFAULT,'AL_DEFK_NO')"
both "CELL 11 ALWAYS + DEFAULT + OSV - OSV does NOT make DEFAULT literal" \
     "INSERT INTO TA (ID,B) OVERRIDING SYSTEM VALUE VALUES (DEFAULT,'AL_DEFK_OS')"
both "CELL 12 ALWAYS + DEFAULT + OUV" \
     "INSERT INTO TA (ID,B) OVERRIDING USER VALUE VALUES (DEFAULT,'AL_DEFK_OU')"
gens "CELL 10/11/12 each advanced the generator (3 -> 6)" 'RDB$1'
both "the ALWAYS table's contents after 12 cells" \
     "SELECT ID, B FROM TA ORDER BY ID"

echo "--- 1b. the same twelve for GENERATED BY DEFAULT (TD / RDB\$2)"
both "CELL 13 BY DEFAULT omitted, no OVERRIDING" \
     "INSERT INTO TD (B) VALUES ('BY_OMIT_NO')"
both "CELL 14 BY DEFAULT omitted + OSV - 335545134, same as ALWAYS" \
     "INSERT INTO TD (B) OVERRIDING SYSTEM VALUE VALUES ('BY_OMIT_OS')"
both "CELL 15 BY DEFAULT omitted + OUV - 335545134" \
     "INSERT INTO TD (B) OVERRIDING USER VALUE VALUES ('BY_OMIT_OU')"
gens "CELL 13 advanced, CELL 14/15 refused with it unmoved" 'RDB$2'
both "CELL 16 BY DEFAULT explicit, no OVERRIDING - lands, no advance" \
     "INSERT INTO TD (ID,B) VALUES (1016,'BY_EXPL_NO')"
both "CELL 17 BY DEFAULT explicit + OSV - 335545135, the THIRD vector" \
     "INSERT INTO TD (ID,B) OVERRIDING SYSTEM VALUE VALUES (1017,'BY_EXPL_OS')"
both "CELL 18 BY DEFAULT explicit + OUV - discarded, generator draws" \
     "INSERT INTO TD (ID,B) OVERRIDING USER VALUE VALUES (1018,'BY_EXPL_OU')"
gens "CELL 16 left it, CELL 17 refused, CELL 18 advanced" 'RDB$2'
both "CELL 19 BY DEFAULT NULL, no OVERRIDING - 335544347 at EXECUTE" \
     "INSERT INTO TD (ID,B) VALUES (NULL,'BY_NULL_NO')"
both "CELL 20 BY DEFAULT NULL + OSV - 335545135 INSTEAD (metadata first)" \
     "INSERT INTO TD (ID,B) OVERRIDING SYSTEM VALUE VALUES (NULL,'BY_NULL_OS')"
both "CELL 21 BY DEFAULT NULL + OUV - discarded, generator draws" \
     "INSERT INTO TD (ID,B) OVERRIDING USER VALUE VALUES (NULL,'BY_NULL_OU')"
both "CELL 22 BY DEFAULT + DEFAULT keyword" \
     "INSERT INTO TD (ID,B) VALUES (DEFAULT,'BY_DEFK_NO')"
both "CELL 23 BY DEFAULT + DEFAULT + OSV - 335545135, value never looked at" \
     "INSERT INTO TD (ID,B) OVERRIDING SYSTEM VALUE VALUES (DEFAULT,'BY_DEFK_OS')"
both "CELL 24 BY DEFAULT + DEFAULT + OUV" \
     "INSERT INTO TD (ID,B) OVERRIDING USER VALUE VALUES (DEFAULT,'BY_DEFK_OU')"
gens "CELL 19..24 moved it exactly three times" 'RDB$2'
both "the BY DEFAULT table's contents after 12 cells" \
     "SELECT ID, B FROM TD ORDER BY ID"

# ======================================================================
# 2. Vector identity, not merely "an error". `both` above already
#    compared the raw items; assert here that the three DISTINCT codes
#    and their pre-quoted arguments really did appear, so a run where
#    every statement quietly succeeded cannot pass.
# ======================================================================
echo "--- 2. the three vectors are distinct, named, and pre-quoted"
v134=$(run "$PORT" "$WORK" "INSERT INTO TA (B) OVERRIDING SYSTEM VALUE VALUES ('x')")
v135=$(run "$PORT" "$WORK" "INSERT INTO TD (ID,B) OVERRIDING SYSTEM VALUE VALUES (1,'x')")
v137=$(run "$PORT" "$WORK" "INSERT INTO TA (ID,B) VALUES (1,'x')")
v134p=$(run "$PORT" "$WORK" "INSERT INTO PLAIN (A,B) OVERRIDING USER VALUE VALUES (1,'p')")
check "335545134 names \"PUBLIC\".\"TA\", alone, no isc_dsql_error wrapper" \
      "$v134" 'ERR [{"gdscode":335545134,"params":["\"PUBLIC\".\"TA\""]}]'
check "335545135 names \"PUBLIC\".\"TD\", alone" \
      "$v135" 'ERR [{"gdscode":335545135,"params":["\"PUBLIC\".\"TD\""]}]'
check "335545137 names \"PUBLIC\".\"TA\", alone" \
      "$v137" 'ERR [{"gdscode":335545137,"params":["\"PUBLIC\".\"TA\""]}]'
check "a table with NO identity takes 335545134 too, naming \"PUBLIC\".\"PLAIN\"" \
      "$v134p" 'ERR [{"gdscode":335545134,"params":["\"PUBLIC\".\"PLAIN\""]}]'
# and the engine agrees with each, item for item
both "335545134 matches the engine item for item" \
     "INSERT INTO TA (B) OVERRIDING SYSTEM VALUE VALUES ('x')"
both "335545135 matches the engine item for item" \
     "INSERT INTO TD (ID,B) OVERRIDING SYSTEM VALUE VALUES (1,'x')"
both "335545137 matches the engine item for item" \
     "INSERT INTO TA (ID,B) VALUES (1,'x')"

# ======================================================================
# 3. Prepare-time, not execute-time: none of the refusals above wrote a
#    row or moved a generator. The engine reads FIRE-CRAB's file for it.
# ======================================================================
echo "--- 3. every refusal left the file untouched (engine reads fc's file)"
col() { # <file> <query>
    "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<SQL | strip | grep -v '^$' | tr '\n' ' ' | strip
SET HEADING OFF;
$2;
SQL
}
check "no refused literal (1004/1017/1018-as-id/9999) reached fc's TA or TD" \
      "$(col "$WORK" "SELECT ID FROM TA WHERE ID IN (1004,1006,1017) UNION ALL SELECT ID FROM TD WHERE ID IN (1017,1018)")" \
      ""
check "the two generators agree with the engine's own file" \
      "$(col "$WORK" "SELECT GEN_ID(RDB\$1,0)||'/'||GEN_ID(RDB\$2,0) FROM RDB\$DATABASE")" \
      "$(col "$REF" "SELECT GEN_ID(RDB\$1,0)||'/'||GEN_ID(RDB\$2,0) FROM RDB\$DATABASE")"

# ======================================================================
# 3b. A NON-PUBLIC schema. The one argument all three vectors carry is
#     the schema-qualified table, and the SCHEMA HALF is READ from the
#     catalog: `INSERT INTO S1.TZ3 ...` names "S1"."TZ3". It used to be
#     the literal "PUBLIC" - right for every table this gate had, wrong
#     the moment a second schema exists.
# ======================================================================
echo "--- 3b. the vectors' qualifier is READ, not assumed (schema S1)"
both "335545135 in S1 - the bare spelling" \
     "INSERT INTO S1.TZ3 (ID,B) OVERRIDING SYSTEM VALUE VALUES (9911,'s')"
both "335545135 in S1 - the QUOTED spelling names the same table" \
     "INSERT INTO \"S1\".\"TZ3\" (ID,B) OVERRIDING SYSTEM VALUE VALUES (9911,'s')"
both "335545134 in S1 - the bare spelling" \
     "INSERT INTO S1.TZ3 (B) OVERRIDING SYSTEM VALUE VALUES ('s')"
both "335545134 in S1 - the QUOTED spelling" \
     "INSERT INTO \"S1\".\"TZ3\" (B) OVERRIDING SYSTEM VALUE VALUES ('s')"
both "335545137 in S1 - the bare spelling" \
     "INSERT INTO S1.TA2 (ID,B) VALUES (77,'s')"
both "335545137 in S1 - the QUOTED spelling" \
     "INSERT INTO \"S1\".\"TA2\" (ID,B) VALUES (77,'s')"
# the argument itself, so a run where the qualifier silently went back to
# PUBLIC cannot pass by matching an engine that also happened to error
s135=$(run "$PORT" "$WORK" "INSERT INTO S1.TZ3 (ID,B) OVERRIDING SYSTEM VALUE VALUES (9911,'s')")
s134=$(run "$PORT" "$WORK" "INSERT INTO S1.TZ3 (B) OVERRIDING SYSTEM VALUE VALUES ('s')")
s137=$(run "$PORT" "$WORK" "INSERT INTO S1.TA2 (ID,B) VALUES (77,'s')")
check "335545135 names \"S1\".\"TZ3\", not \"PUBLIC\".\"TZ3\"" \
      "$s135" 'ERR [{"gdscode":335545135,"params":["\"S1\".\"TZ3\""]}]'
check "335545134 names \"S1\".\"TZ3\", not \"PUBLIC\".\"TZ3\"" \
      "$s134" 'ERR [{"gdscode":335545134,"params":["\"S1\".\"TZ3\""]}]'
check "335545137 names \"S1\".\"TA2\", not \"PUBLIC\".\"TA2\"" \
      "$s137" 'ERR [{"gdscode":335545137,"params":["\"S1\".\"TA2\""]}]'
# the controls: the schema is a QUALIFIER, not a refusal - what the rule
# permits still lands, and the S1 generators move exactly as PUBLIC's do
both "OSV into S1's ALWAYS table still succeeds with the literal id" \
     "INSERT INTO S1.TA2 (ID,B) OVERRIDING SYSTEM VALUE VALUES (3006,'q6') RETURNING ID, B"
both "an omitted identity in S1 still draws from S1's own generator" \
     "INSERT INTO S1.TZ3 (B) VALUES ('q7') RETURNING ID, B"
both "both S1 tables read back identically" \
     "SELECT ID, B FROM S1.TA2 UNION ALL SELECT ID, B FROM S1.TZ3 ORDER BY 1"
check "S1's two generators agree with the engine's own file" \
      "$(col "$WORK" "SELECT GEN_ID(S1.RDB\$4,0)||'/'||GEN_ID(S1.RDB\$5,0) FROM RDB\$DATABASE")" \
      "$(col "$REF" "SELECT GEN_ID(S1.RDB\$4,0)||'/'||GEN_ID(S1.RDB\$5,0) FROM RDB\$DATABASE")"
check "the S1 refusals wrote nothing to fc's file" \
      "$(col "$WORK" "SELECT ID FROM S1.TZ3 WHERE ID = 9911 UNION ALL SELECT ID FROM S1.TA2 WHERE ID = 77")" \
      ""

# ======================================================================
# 4. Parameters: a DISCARDED value must still BIND. The engine describes
#    and consumes both parameters of the OUV form exactly as it does the
#    OSV form; only the WRITE is skipped.
# ======================================================================
echo "--- 4. a discarded parameter still binds (same arity as OSV)"
both "OUV with (?,?) binds two params and stores the GENERATED id" \
     "INSERT INTO TA (ID,B) OVERRIDING USER VALUE VALUES (?,?) RETURNING ID, B" \
     '[555555,"pu"]'
both "OSV with (?,?) binds two params and stores the SUPPLIED id" \
     "INSERT INTO TA (ID,B) OVERRIDING SYSTEM VALUE VALUES (?,?) RETURNING ID, B" \
     '[555556,"ps"]'
gens "OUV advanced once, OSV not at all" 'RDB$1'
both "too few parameters is an error on both (the arity really is 2)" \
     "INSERT INTO TA (ID,B) OVERRIDING USER VALUE VALUES (?,?)" '[7]' 1

# ======================================================================
# 5. RETURNING reports what LANDED - the generated id under OUV, the
#    supplied one under OSV.
# ======================================================================
echo "--- 5. RETURNING answers the value that landed"
both "OUV RETURNING gives the GENERATED id, not the supplied 9999" \
     "INSERT INTO TA (ID,B) OVERRIDING USER VALUE VALUES (9999,'ret') RETURNING ID, B"
both "OSV RETURNING gives the SUPPLIED 8888" \
     "INSERT INTO TA (ID,B) OVERRIDING SYSTEM VALUE VALUES (8888,'ret2') RETURNING ID, B"

# ======================================================================
# 6. Case, position and the repeated column.
# ======================================================================
echo "--- 6. case-insensitive keyword, free column order, repeated column"
both "lowercase 'overriding system value' works" \
     "INSERT INTO TA (ID,B) overriding system value VALUES (313131,'lc')"
both "a REVERSED column list (B,ID) works - order is free" \
     "INSERT INTO TA (B,ID) OVERRIDING SYSTEM VALUE VALUES ('rev',424242)"
bound "a REPEATED column refuses on both (fc generically, engine -206)" \
      "INSERT INTO TA (ID,ID) OVERRIDING SYSTEM VALUE VALUES (1,2)"
check "the repeated-column refusal wrote NOTHING (it used to store ID=2)" \
      "$(col "$WORK" "SELECT COUNT(*) FROM TA WHERE B IS NULL AND ID = 2")" "0"
both "multi-row VALUES (..),(..) is a syntax error on both" \
     "INSERT INTO TA (ID,B) OVERRIDING USER VALUE VALUES (9001,'m1'),(9002,'m2')" '[]' 1

# ======================================================================
# 7. GENERATED ALWAYS is NOT protected on UPDATE - the surprise. The
#    rule is an INSERT-field-list rule only.
# ======================================================================
echo "--- 7. UPDATE is not protected by the ALWAYS rule"
both "UPDATE TA SET ID = ID + 100000 succeeds with no OVERRIDING" \
     "UPDATE TA SET ID = ID + 100000 WHERE B = 'rev'"
both "and the row really moved to 524242" \
     "SELECT ID, B FROM TA WHERE B = 'rev'"

# ======================================================================
# 8. UPDATE OR INSERT ships the TYPED vector at prepare, with the update
#    half not having run.
# ======================================================================
echo "--- 8. UPDATE OR INSERT enforces the same rule, typed"
both "UPDATE OR INSERT without OVERRIDING answers 335545137" \
     "UPDATE OR INSERT INTO TA (ID,B) VALUES (4242,'uoi') MATCHING (ID)"
check "and nothing was written by the refused upsert" \
      "$(col "$WORK" "SELECT COUNT(*) FROM TA WHERE ID = 4242")" "0"
both "UPDATE OR INSERT with OSV succeeds" \
     "UPDATE OR INSERT INTO TA (ID,B) OVERRIDING SYSTEM VALUE VALUES (4242,'uoi') MATCHING (ID)"
both "the upserted row is there on both" "SELECT ID, B FROM TA WHERE ID = 4242"

# ======================================================================
# 9. INSERT ... DEFAULT VALUES.
# ======================================================================
echo "--- 9. INSERT INTO <t> DEFAULT VALUES"
both "every column DEFAULT applies" "INSERT INTO D_DEF DEFAULT VALUES"
both "D_DEF holds (42,'dd')" "SELECT A, B FROM D_DEF"
both "a table with no defaults stores one all-NULL row" "INSERT INTO D_NODEF DEFAULT VALUES"
both "D_NODEF holds one all-NULL row" "SELECT A, B FROM D_NODEF"
both "NOT NULL with no default fails at EXECUTE (23000/335544347)" \
     "INSERT INTO D_NN DEFAULT VALUES"
both "NOT NULL WITH a default is satisfied" "INSERT INTO D_NNDEF DEFAULT VALUES"
both "D_NNDEF holds A=5" "SELECT A, B FROM D_NNDEF"
both "a COMPUTED column is evaluated from the applied defaults" \
     "INSERT INTO D_COMP DEFAULT VALUES"
both "D_COMP reads back A=3, C=30" "SELECT A, C FROM D_COMP"
both "a constant-default PK stores once" "INSERT INTO D_PK DEFAULT VALUES"
both "and the second DEFAULT VALUES is a duplicate key" "INSERT INTO D_PK DEFAULT VALUES"
both "DEFAULT VALUES fires a GENERATED ALWAYS identity with no OVERRIDING" \
     "INSERT INTO TA DEFAULT VALUES RETURNING ID, B"
gens "and it advanced the generator" 'RDB$1'
both "DEFAULT VALUES fires a GENERATED BY DEFAULT identity too" \
     "INSERT INTO TD DEFAULT VALUES RETURNING ID, B"
gens "and it advanced that generator" 'RDB$2'
both "RETURNING the applied defaults" "INSERT INTO D_DEF DEFAULT VALUES RETURNING A, B"
both "no column list is admitted - () DEFAULT VALUES errors on both" \
     "INSERT INTO D_DEF () DEFAULT VALUES" '[]' 1
both "no OVERRIDING clause is admitted either - errors on both" \
     "INSERT INTO TA OVERRIDING SYSTEM VALUE DEFAULT VALUES" '[]' 1

# ======================================================================
# 10. INSERT..SELECT: prepare-time resolution, the implicit list, the
#     OVERRIDING arithmetic, and a real input SQLDA.
# ======================================================================
echo "--- 10. INSERT..SELECT"
both "OSV over 3 source rows lands all three source values" \
     "INSERT INTO TA (ID,B) OVERRIDING SYSTEM VALUE SELECT X, Y FROM SRC"
gens "and the generator did NOT move for any of them" 'RDB$1'
both "OUV over 3 source rows discards all three" \
     "INSERT INTO TA (ID,B) OVERRIDING USER VALUE SELECT X+100, Y FROM SRC"
gens "and the generator advanced ONCE PER ROW (+3)" 'RDB$1'
both "the ids the OUV rows actually got" \
     "SELECT ID, B FROM TA WHERE ID < 100 ORDER BY ID"
both "INSERT..SELECT into ALWAYS with no OVERRIDING is 335545137 at prepare" \
     "INSERT INTO TA (ID,B) SELECT X+400, Y FROM SRC"
both "INSERT..SELECT into BY DEFAULT works with no OVERRIDING" \
     "INSERT INTO TD (ID,B) SELECT X+300, Y FROM SRC"
gens "and left that generator alone" 'RDB$2'
both "OVERRIDING naming only the NON-identity column is 335545134" \
     "INSERT INTO TA (B) OVERRIDING SYSTEM VALUE SELECT Y FROM SRC"
both "an unknown target table errors at PREPARE on both" \
     "INSERT INTO NOSUCH SELECT X, Y FROM SRC" '[]' 1
# the implicit-list regression: the computed column must drop out AND
# the order must be POSITION, not FIELD_ID (POSN was repositioned)
both "the implicit list excludes the COMPUTED column (2-col SELECT, 3-col table)" \
     "INSERT INTO CMP SELECT X, Y FROM SRC"
both "CMP landed the right values in the right columns" \
     "SELECT A, C, B FROM CMP ORDER BY A"
both "the implicit list follows POSITION, not FIELD_ID (repositioned table)" \
     "INSERT INTO POSN SELECT 30, 10, 20 FROM RDB\$DATABASE"
both "POSN landed 10/20/30 - the wrong-write regression test" \
     "SELECT P1, P2, P3 FROM POSN"
# a real input SQLDA: WHERE-clause parameters, typed from the compared
# column, in textual order
both "one WHERE parameter binds and filters" \
     "INSERT INTO PT (A,B) SELECT X, Y FROM SRC WHERE X = ?" '[7002]'
both "two WHERE parameters bind in textual order" \
     "INSERT INTO PT (A,B) SELECT X, Y FROM SRC WHERE X = ? AND Y = ?" '[7001,"s1"]'
both "PT holds exactly the rows the bindings selected" \
     "SELECT A, B FROM PT ORDER BY A"

# ======================================================================
# 11. The priced boundaries. Each records what the engine does so the
#     next slice has its target.
# ======================================================================
echo "--- 11. recorded boundaries (fire-crab refuses; the engine answers)"
# the engine describes these from the INSERT TARGET COLUMN: 496 LONG /
# 448 VARYING len 10 / 570 SQL DATE / 496 LONG scale -3 subtype 1, and
# the nullability bit is the target column's too
# NOTE: a `bound` statement runs on the ENGINE too, and the engine
# ANSWERS it - so every one of them targets BND / BCMP / BID, the three
# tables the final content differential deliberately does not dump.
# Pointing them at PT or D_DEF would silently desynchronise the twins.
bound "select-list ? (engine types it from the TARGET column: 496 LONG + 448 VARYING len 10)" \
      "INSERT INTO BND (A,B) SELECT ?, ? FROM SRC" '[1,"z"]'
bound "select-list ? mixed with a WHERE ? (engine: 01 target BND.A, 02 SRC.X)" \
      "INSERT INTO BND (A,B) SELECT ?, Y FROM SRC WHERE X = ?" '[1,7001]'
bound "? + 1 in the select list (engine keeps the target typing: 496 LONG)" \
      "INSERT INTO BND (A,B) SELECT ? + 1, Y FROM SRC" '[1]'
bound "CAST(? AS SMALLINT) in the select list (engine: 500 SHORT len 2)" \
      "INSERT INTO BND (A,B) SELECT CAST(? AS SMALLINT), Y FROM SRC" '[1]'
bound "MERGE ... WHEN NOT MATCHED THEN INSERT ... OVERRIDING (no MERGE surface at all)" \
      "MERGE INTO BID USING SRC ON BID.ID = SRC.X WHEN NOT MATCHED THEN INSERT (ID,B) OVERRIDING SYSTEM VALUE VALUES (SRC.X, SRC.Y)"
bound "RETURNING * (returning_ident cannot parse '*')" \
      "INSERT INTO BND DEFAULT VALUES RETURNING *"
bound "RETURNING a COMPUTED column (engine evaluates it; fc would answer null-flag bytes)" \
      "INSERT INTO BCMP DEFAULT VALUES RETURNING A, C"
# both error, different vector: fire-crab has no -804 surface
both "? = ? in the source refuses on BOTH (engine -804/HY004, fc generic)" \
     "INSERT INTO BND (A,B) SELECT X, Y FROM SRC WHERE ? = ?" '[1,1]' 1

# ======================================================================
# 11b. A VIEW target. fire-crab has no view-INSERT surface - a priced
#      boundary. What it must NOT do is answer the identity check first:
#      a view carries no identity column of its own, so the metadata rule
#      would confidently ship 335545134 naming the VIEW, where the engine
#      merges the view and writes the BASE table. And when the engine DOES
#      refuse through a view it names the BASE table, so even the argument
#      would be wrong. The typed verdict is therefore a TABLE verdict; a
#      view target falls through to the generic refusal below. VBASE is
#      deliberately absent from the final content dump - the engine
#      ANSWERS these, so the twins part company here.
# ======================================================================
echo "--- 11b. a view target ships no typed identity verdict"
bound "OSV into a view (engine merges and writes VBASE; fc has no view-INSERT surface)" \
      "INSERT INTO VTA (ID,B) OVERRIDING SYSTEM VALUE VALUES (4444,'v9')"
bound "a plain view INSERT naming the identity (the engine's 335545137 names \"PUBLIC\".\"VBASE\")" \
      "INSERT INTO VTA (ID,B) VALUES (3007,'v1')"
bound "a view INSERT omitting the identity (engine: the base generator draws)" \
      "INSERT INTO VTA (B) VALUES ('v2')"
vview=$(run "$PORT" "$WORK" "INSERT INTO VTA (ID,B) OVERRIDING SYSTEM VALUE VALUES (4445,'v10')")
check "the refusal is GENERIC - it used to fabricate 335545134 \"PUBLIC\".\"VTA\"" \
      "$vview" 'ERR [{"gdscode":335544569}]'
check "and the view's BASE table is untouched on fire-crab's side" \
      "$(col "$WORK" "SELECT COUNT(*) FROM VBASE")" "0"

# ======================================================================
# 12. Epilogue: the two files must be identical table by table, then
#     gbak round-trips fire-crab's file and gfix validates it.
# ======================================================================
kill $srv 2>/dev/null; wait $srv 2>/dev/null
echo "--- 12. final differential, gbak and gfix"

dump() { # <file>
    "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT 'TA|'||ID||'|'||COALESCE(TRIM(B),'~') FROM TA ORDER BY ID;
SELECT 'TD|'||ID||'|'||COALESCE(TRIM(B),'~') FROM TD ORDER BY ID;
SELECT 'TA2|'||ID||'|'||COALESCE(TRIM(B),'~') FROM S1.TA2 ORDER BY ID;
SELECT 'TZ3|'||ID||'|'||COALESCE(TRIM(B),'~') FROM S1.TZ3 ORDER BY ID;
SELECT 'PLAIN|'||COALESCE(CAST(A AS VARCHAR(12)),'~') FROM PLAIN ORDER BY 1;
SELECT 'PT|'||COALESCE(CAST(A AS VARCHAR(12)),'~')||'|'||COALESCE(TRIM(B),'~') FROM PT ORDER BY 1;
SELECT 'DDEF|'||COALESCE(CAST(A AS VARCHAR(12)),'~')||'|'||COALESCE(TRIM(B),'~') FROM D_DEF ORDER BY 1;
SELECT 'DNODEF|'||COALESCE(CAST(A AS VARCHAR(12)),'~') FROM D_NODEF;
SELECT 'DNN|'||COUNT(*) FROM D_NN;
SELECT 'DNNDEF|'||COALESCE(CAST(A AS VARCHAR(12)),'~') FROM D_NNDEF;
SELECT 'DCOMP|'||A||'|'||C FROM D_COMP ORDER BY 1;
SELECT 'DPK|'||A FROM D_PK ORDER BY 1;
SELECT 'CMP|'||A||'|'||C||'|'||TRIM(B) FROM CMP ORDER BY 1;
SELECT 'POSN|'||P1||'|'||P2||'|'||P3 FROM POSN;
SELECT 'GEN|'||GEN_ID(RDB$1,0)||'|'||GEN_ID(RDB$2,0) FROM RDB$DATABASE;
SELECT 'S1GEN|'||GEN_ID(S1.RDB$4,0)||'|'||GEN_ID(S1.RDB$5,0) FROM RDB$DATABASE;
SQL
}
work_d=$(dump "$WORK")
check "every table and both generators match the engine's own file" \
      "$work_d" "$(dump "$REF")"
# the comparison must not be vacuous: the load-bearing rows really landed
case "$work_d" in
    *"TA|1005|AL_EXPL_OS"*"TA|7001|s1"*"TA2|3006|q6"*"DCOMP|3|30"*"POSN|10|20|30"*)
        echo "OK   the content comparison is not vacuous (OSV literals in PUBLIC and in S1, INSERT..SELECT rows, POSN order, computed column)" ;;
    *) echo "DIFF the content comparison was vacuous"; echo "     $work_d"; fail=1 ;;
esac
checks=$((checks + 1))

if "$GBAK" -b -g -user "$U" -pas "$P" "$WORK" "$FBK" >/tmp/fc-ovr-backup.log 2>&1; then
    echo "OK   gbak backs up the database fire-crab wrote"
else
    echo "DIFF gbak backup"; cat /tmp/fc-ovr-backup.log; fail=1
fi
checks=$((checks + 1))
"$GBAK" -c -user "$U" -pas "$P" "$FBK" "$RST" >/tmp/fc-ovr-restore.log 2>&1
rc=$?
checks=$((checks + 1))
if [ $rc -eq 0 ] && ! grep -qiE "error" /tmp/fc-ovr-restore.log; then
    echo "OK   gbak RESTORES it"
else
    echo "DIFF gbak restore (exit $rc)"; grep -iE "error|cannot" /tmp/fc-ovr-restore.log | head; fail=1
fi
valw=$("$GFIX" -v -full -user "$U" -pas "$P" "$WORK" 2>&1)
check "gfix -v -full clean (fc's raw file)" "$(printf '%s' "$valw" | strip)" ""

echo "--- $checks differential checks, $bounds recorded boundaries"
exit $fail
