#!/bin/bash
# RDB$FIELD_PRECISION for PLAIN declared columns - the catalog field the
# engine writes on every exact-numeric declaration and fire-crab used to
# leave NULL (only computed columns carried it).
#
# The engine's rule (probed on tables, domains, ALTER ADD and ALTER
# TYPE): the plain exact-int family (SMALLINT/INTEGER/BIGINT/INT128)
# gets precision 0, NUMERIC/DECIMAL(p,s) get the DECLARED p, every
# other type stays NULL. Retyping updates it (INTEGER -> NUMERIC(12)
# sets 12). And one adjacent storage fact this slice flushed out:
# DECIMAL(1..4) stores as a LONG (type 8) where NUMERIC(1..4) is a
# SHORT (type 7) - dialect 3 lets DECIMAL hold more digits than
# declared.
#
# The differential is the engine, three ways:
#   1. fire-crab and the engine run the same DDL matrix (CREATE TABLE
#      with every declarable type incl PK + identity, CREATE DOMAIN,
#      ALTER ADD, ALTER TYPE) on two copies; the full
#      (name, type, sub_type, scale, precision) catalog projection
#      matches row for row;
#   2. the engine CONTINUES on fire-crab's file: inserts into the table
#      and reads back through the retyped and added columns;
#   3. gbak round trip and gfix -v -full.
#
#   qa/serve-real-precision.sh [port]
#
# Builds its own scratch databases.

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"; GFIX="${GFIX:-gfix}"; GBAK="${GBAK:-gbak}"
PORT="${1:-4283}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
WORK="$D/fc-prec-work.fdb"; REF="$D/fc-prec-ref.fdb"
FBK="$D/fc-prec-work.fbk"; RST="$D/fc-prec-rst.fdb"

command -v node >/dev/null 2>&1 || { echo "SKIP node not found"; exit 0; }
mkdir -p "$D"; rm -f "$WORK" "$REF" "$FBK" "$RST"

# the DDL matrix, one statement per line - fire-crab runs it over the
# wire, the engine runs the identical list on the ref copy
DDL=(
  "CREATE TABLE T (ID INTEGER NOT NULL PRIMARY KEY, S1 SMALLINT, B1 BIGINT, X2 INTEGER, N1 NUMERIC(4,1), N2 NUMERIC(9,2), N3 NUMERIC(10,2), N4 NUMERIC(18), D1 DECIMAL(3), D2 DECIMAL(4,1), D3 DECIMAL(15,4), V1 VARCHAR(10), C1 CHAR(5), F1 FLOAT, G1 DOUBLE PRECISION, T1 DATE, X1 BOOLEAN, Q1 INTEGER GENERATED BY DEFAULT AS IDENTITY)"
  "CREATE DOMAIN PDOM AS NUMERIC(12,3)"
  "CREATE DOMAIN IDOM AS INTEGER"
  "CREATE DOMAIN VDOM AS VARCHAR(8)"
  "CREATE TABLE U (A PDOM, B IDOM, C VDOM)"
  "ALTER TABLE T ADD A1 NUMERIC(7,2)"
  "ALTER TABLE T ADD A2 BIGINT"
  "ALTER TABLE T ALTER S1 TYPE NUMERIC(12)"
  "ALTER TABLE T ALTER X2 TYPE BIGINT"
)

"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL ref db"; exit 1; }
CREATE DATABASE '$REF' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
$(printf '%s;\nCOMMIT;\n' "${DDL[@]}")
EOF
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL work db"; exit 1; }
CREATE DATABASE '$WORK' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
COMMIT;
EOF

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-prec.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$WORK" "$REF" "$FBK" "$RST"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
# The readiness probe above answers "SOMETHING is listening", not "OUR
# server is listening". If the port was already taken, fcwire exited at
# bind and every check below runs against the OTHER server - a gate that
# reports success while measuring nothing. Fatal, not a warning.
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

strip() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
node_once() {
    FC_DB="$WORK" FC_PORT="$PORT" FC_Q="$1" timeout 15 node -e '
      process.on("uncaughtException",()=>{console.log("CONN_ERR");process.exit(1);});
      const F=require("node-firebird");
      F.attach({host:"127.0.0.1",port:+process.env.FC_PORT,database:process.env.FC_DB,
                user:"SYSDBA",password:"masterkey"},(e,db)=>{
        if(e){console.log("CONN_ERR");process.exit(1);}
        db.query(process.env.FC_Q,(e2,r)=>{
          console.log(e2?("ERR "+(e2.message||"").split("\n")[0]):"OK");
          db.detach();process.exit(0);});
      });' 2>/dev/null
}
node_run() {
    n=0
    while [ $n -lt 10 ]; do
        r=$(node_once "$1")
        case "$r" in
            *CONN_ERR*|"") n=$((n + 1)); sleep 0.3 ;;
            *) printf '%s' "$r" | strip; return ;;
        esac
    done
    echo CONN_ERR
}

fail=0
check() { # <label> <got> <want>
    if [ "$2" = "$3" ]; then echo "OK   $1"; else
        echo "DIFF $1"; echo "     want: $3"; echo "     got:  $2"; fail=1; fi
}

for s in "${DDL[@]}"; do
    check "fire-crab: ${s:0:44}..." "$(node_run "$s")" "OK"
done
kill $srv 2>/dev/null; wait $srv 2>/dev/null

# --- 1. the (type, sub_type, scale, precision) projection matches ------
catq() { # <file>
    "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT TRIM(rf.RDB$RELATION_NAME)||'.'||TRIM(rf.RDB$FIELD_NAME)||'|'||f.RDB$FIELD_TYPE
       ||'|'||COALESCE(f.RDB$FIELD_SUB_TYPE,-99)||'|'||COALESCE(f.RDB$FIELD_SCALE,-99)
       ||'|'||COALESCE(f.RDB$FIELD_PRECISION,-99)
FROM RDB$RELATION_FIELDS rf JOIN RDB$FIELDS f ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE rf.RDB$RELATION_NAME IN ('T','U') ORDER BY 1;
SELECT 'DOM.'||TRIM(f.RDB$FIELD_NAME)||'|'||f.RDB$FIELD_TYPE
       ||'|'||COALESCE(f.RDB$FIELD_SUB_TYPE,-99)||'|'||COALESCE(f.RDB$FIELD_SCALE,-99)
       ||'|'||COALESCE(f.RDB$FIELD_PRECISION,-99)
FROM RDB$FIELDS f WHERE f.RDB$FIELD_NAME IN ('PDOM','IDOM','VDOM') ORDER BY 1;
SQL
}
work_c=$(catq "$WORK")
check "every column and domain's (type|sub|scale|precision) matches the engine" \
      "$work_c" "$(catq "$REF")"
case "$work_c" in
    *"T.D1|8|2|0|3"*"T.N3|16|1|-2|10"*"T.S1|16|1|0|12"*"DOM.PDOM|16|1|-3|12"*)
        echo "OK   the teeth bite: NUMERIC(10,2)=10, DECIMAL(3) is a LONG p3, retype set 12, domain 12" ;;
    *) echo "DIFF the projection comparison was vacuous"; echo "     $work_c"; fail=1 ;;
esac

# --- 2. the engine continues on fire-crab's file -----------------------
cont=$("$ISQL" -q -b -user "$U" -pas "$P" "$WORK" 2>&1 <<'SQL' | strip | grep -v '^$'
INSERT INTO T (ID, S1, N3, D1, A1) VALUES (1, 123456789012, 5.25, 42, 9.75);
INSERT INTO U (A, B, C) VALUES (1.125, 7, 'ok');
COMMIT;
SET HEADING OFF;
SELECT 'T|'||ID||'|'||S1||'|'||N3||'|'||D1||'|'||A1 FROM T;
SELECT 'U|'||A||'|'||B||'|'||TRIM(C) FROM U;
SQL
)
check "the engine inserts and reads through fc's retyped/added columns" \
      "$cont" "T|1|123456789012|5.25|42|9.75
U|1.125|7|ok"

# --- 3. gbak and gfix --------------------------------------------------
if "$GBAK" -b -g -user "$U" -pas "$P" "$WORK" "$FBK" >/tmp/fc-prec-backup.log 2>&1; then
    echo "OK   gbak backs up the database fire-crab wrote"
else
    echo "DIFF gbak backup"; cat /tmp/fc-prec-backup.log; fail=1
fi
"$GBAK" -c -user "$U" -pas "$P" "$FBK" "$RST" >/tmp/fc-prec-restore.log 2>&1
rc=$?
if [ $rc -eq 0 ] && ! grep -qiE "error" /tmp/fc-prec-restore.log; then
    echo "OK   gbak RESTORES it"
else
    echo "DIFF gbak restore (exit $rc)"; grep -iE "error|cannot" /tmp/fc-prec-restore.log | head; fail=1
fi
valw=$("$GFIX" -v -full -user "$U" -pas "$P" "$WORK" 2>&1)
check "gfix -v -full clean (fc's raw file)" "$(printf '%s' "$valw" | strip)" ""

exit $fail
