#!/bin/bash
# An absolute generator set is DEFERRED, and there is no compensating
# record.
#
# THE ENGINE MODEL, read from its source and probed live (dfw.epp
# set_generator phase 3, dpm.epp DPM_gen_id:1421, Savepoint.cpp:459,
# DdlNodes.epp:6510):
#
#   * SET GENERATOR / ALTER SEQUENCE RESTART / ALTER TABLE ... RESTART
#     never touches the generator page. The value lands in a
#     TRANSACTION-scoped cache (tra_gen_ids, last put wins) and a
#     dfw_set_generator posting lands in the CURRENT savepoint.
#   * Once cached, every later read AND draw of that name lives in the
#     cache; other attachments see the page throughout.
#   * ROLLBACK TO SAVEPOINT deletes the savepoint's postings and
#     nothing else - the cache keeps answering locally.
#   * COMMIT applies the cache's LAST value for every name with a
#     SURVIVING posting, wherever the posting sits; a name whose
#     postings all died never reaches the page, and neither do the
#     draws it absorbed.
#
# The matrix below runs IDENTICALLY against the live engine (embedded)
# and against fcwire, cell by cell - the roadmap's original divergence
# (an undone identity RESTART WITH 100: engine writes ID 100, fc wrote
# ID 2) is the P16 pair.
#
#   qa/serve-real-gencomp.sh [port]

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"
GFIX="${GFIX:-gfix}"
PORT="${1:-4781}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
RE="$D/fc-gencomp-re.fdb"; FC="$D/fc-gencomp-fc.fdb"

mkdir -p "$D"; rm -f "$RE" "$FC"
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF >/dev/null 2>&1 || { echo "FAIL create"; exit 1; }
CREATE DATABASE '$RE' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
CREATE SEQUENCE G;
CREATE TABLE AID (ID BIGINT GENERATED BY DEFAULT AS IDENTITY, V INTEGER);
COMMIT;
EOF
cp "$RE" "$FC"; chmod 666 "$RE" "$FC"

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-gencomp.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$RE" "$FC"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

fail=0
ran=0

# one transaction script, TAG-labelled reads; the engine runs it
# embedded against $RE, fcwire serves $FC
MATRIX='SET AUTODDL OFF;
SET LIST ON;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT SP;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT SP;
SELECT '"'"'TAG P1-undone-set-still-reads '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
COMMIT;
SELECT '"'"'TAG P2-dead-posting-never-lands '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT SP;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT SP;
ROLLBACK;
SELECT '"'"'TAG P3-rollback '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
COMMIT;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT SP;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT SP;
SELECT '"'"'TAG P4-draw-in-cache '"'"' || GEN_ID(G,1) AS T FROM RDB$DATABASE;
COMMIT;
SELECT '"'"'TAG P4-cached-draw-lost '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT SP;
SELECT '"'"'TAG P5-page-draw '"'"' || GEN_ID(G,1) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT SP;
SELECT '"'"'TAG P5-cache-mid '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
COMMIT;
SELECT '"'"'TAG P5-page-draw-survives '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT A;
SET GENERATOR G TO 10;
SAVEPOINT B;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT B;
SELECT '"'"'TAG P6-mid '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
COMMIT;
SELECT '"'"'TAG P6-survivor-applies-LAST-value '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT A;
SET GENERATOR G TO 10;
SAVEPOINT B;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT B;
ROLLBACK TO SAVEPOINT A;
SELECT '"'"'TAG P7-mid '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
COMMIT;
SELECT '"'"'TAG P7-both-die '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT SP;
SET GENERATOR G TO 3;
COMMIT;
SELECT '"'"'TAG P8-survivor-lands '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT SP;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT SP;
SET GENERATOR G TO 7;
COMMIT;
SELECT '"'"'TAG P9-reset-after-undo '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT A;
SET GENERATOR G TO 10;
ROLLBACK TO SAVEPOINT A;
SAVEPOINT B;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT B;
SELECT '"'"'TAG P10-mid '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
COMMIT;
SELECT '"'"'TAG P10-two-dead-postings '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SET GENERATOR G TO 50; COMMIT;
SET GENERATOR G TO 3;
SELECT '"'"'TAG P12-draw-rides-cache '"'"' || GEN_ID(G,1) AS T FROM RDB$DATABASE;
COMMIT;
SELECT '"'"'TAG P12-and-commits '"'"' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
DELETE FROM AID; COMMIT;
ALTER TABLE AID ALTER COLUMN ID RESTART WITH 1; COMMIT;
SAVEPOINT SP;
ALTER TABLE AID ALTER COLUMN ID RESTART WITH 100;
ROLLBACK TO SAVEPOINT SP;
INSERT INTO AID (V) VALUES (3);
SELECT '"'"'TAG P16-identity-draws-cached-100 '"'"' || MAX(ID) AS T FROM AID;
COMMIT;
INSERT INTO AID (V) VALUES (4);
SELECT '"'"'TAG P16-post-commit-draws-page '"'"' || MAX(ID) AS T FROM AID;
COMMIT;'

e_out=$(echo "$MATRIX" | "$ISQL" -q -b -user "$U" -pas "$P" "$RE" 2>&1 \
    | grep -oE 'TAG [^ ]* -?[0-9]+' | sed 's/  */ /g')
f_out=$(echo "$MATRIX" | "$ISQL" -q -b -user "$U" -pas "$P" "localhost/$PORT:$FC" 2>&1 \
    | grep -oE 'TAG [^ ]* -?[0-9]+' | sed 's/  */ /g')

cells=$(echo "$e_out" | grep -c 'TAG')
if [ "$cells" -lt 20 ]; then
    echo "DIFF the engine answered only $cells cells - the matrix itself broke"
    fail=1
fi
while IFS= read -r e_line; do
    ran=$((ran + 1))
    tag=$(echo "$e_line" | awk '{print $2}')
    f_line=$(echo "$f_out" | grep -F "TAG $tag " || true)
    if [ "$e_line" = "$f_line" ]; then
        echo "OK   $e_line"
    else
        echo "DIFF $tag: engine [$e_line] fc [$f_line]"
        fail=1
    fi
done <<< "$e_out"

# --- the cache is PRIVATE: a second attachment reads the page --------
# The holder sets 3 inside an undone savepoint and sleeps; the second
# attachment must read 50 (the page) on BOTH sides while the holder's
# own read answers 3.
xatt() { # <conn-string> -> "mid other post"
    local conn="$1"
    "$ISQL" -q -b -user "$U" -pas "$P" "$conn" <<'EOF' >/tmp/fc-gencomp-hold.log 2>&1 &
SET AUTODDL OFF; SET LIST ON;
SET GENERATOR G TO 50; COMMIT;
SAVEPOINT SP;
SET GENERATOR G TO 3;
ROLLBACK TO SAVEPOINT SP;
SELECT 'TAG mid ' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
SHELL sleep 3;
COMMIT;
SELECT 'TAG post ' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
EOF
    local hold=$!
    sleep 1.5
    local other
    other=$("$ISQL" -q -b -user "$U" -pas "$P" "$conn" <<'EOF' 2>&1 | grep -oE 'TAG other -?[0-9]+' | awk '{print $3}'
SET LIST ON;
SELECT 'TAG other ' || GEN_ID(G,0) AS T FROM RDB$DATABASE;
COMMIT;
EOF
)
    wait $hold 2>/dev/null
    local mid post
    mid=$(grep -oE 'TAG mid -?[0-9]+' /tmp/fc-gencomp-hold.log | awk '{print $3}')
    post=$(grep -oE 'TAG post -?[0-9]+' /tmp/fc-gencomp-hold.log | awk '{print $3}')
    echo "$mid $other $post"
}
ran=$((ran + 1))
chmod 666 "$RE" 2>/dev/null
e_x=$(xatt "localhost:$RE")
f_x=$(xatt "localhost/$PORT:$FC")
if [ -n "$e_x" ] && [ "$e_x" = "$f_x" ]; then
    echo "OK   the cache is private: holder/other/post [$f_x] identical (want 3 50 50)"
else
    echo "DIFF cross-attachment: engine [$e_x] fc [$f_x]"
    fail=1
fi

# --- the file survives the engine's own verifier ----------------------
ran=$((ran + 1))
chmod 666 "$FC" 2>/dev/null
v=$("$GFIX" -v -full -user "$U" -pas "$P" "$FC" 2>&1)
if [ -z "$v" ]; then
    echo "OK   gfix -v -full is clean on fc's file after the whole matrix"
else
    echo "DIFF gfix: $v"
    fail=1
fi

if [ "$ran" -lt 22 ]; then
    echo "DIFF only $ran checks ran (expected at least 22) - did one silently skip?"
    fail=1
fi
kill $srv 2>/dev/null; wait $srv 2>/dev/null
if [ "$fail" = 0 ]; then
    echo "PASS serve-real-gencomp ($ran checks)"
else
    echo "FAIL serve-real-gencomp"
    exit 1
fi
