#!/bin/bash
# AN IDENTITY COLUMN MUST BE EXACT-NUMERIC WITH ZERO SCALE - AN INVALID
# TYPE IS REFUSED AT CREATE AND ALTER, NOT SILENTLY ACCEPTED.
#
# The engine requires a GENERATED {ALWAYS|BY DEFAULT} AS IDENTITY column
# to be SMALLINT / INTEGER / BIGINT / INT128 / NUMERIC|DECIMAL(p,0). A
# NUMERIC(p, s>0), a VARCHAR, a DATE or a DOUBLE identity is rejected at
# CREATE TABLE and at ALTER TABLE ADD with "Identity column ... must be
# of exact number type with zero scale" (SQLSTATE 42000), and no table /
# column is created. fire-crab accepted them silently, persisting a
# table (or column) plus a backing generator the engine would never have
# made - a structurally divergent, unrecoverable database.
#
# fire-crab now validates the identity column's resolved type/scale on
# both the CREATE TABLE and the ALTER TABLE ADD path (after domain
# resolution) and refuses an invalid one, matching the engine's refusal.
# A valid exact-numeric zero-scale identity still creates. Held against
# the live engine on the created-state (a table's presence in
# RDB$RELATIONS, a column's in RDB$RELATION_FIELDS).
#
# Usage: qa/serve-real-identityvalid.sh [port]   (default 4156)
set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"
PORT="${1:-4156}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D="/tmp/fbhandson"
ENG="$D/identityvalid-eng.fdb"; FC="$D/identityvalid-fc.fdb"
rm -f "$ENG" "$FC"
echo "create database '127.0.0.1/3050:$ENG' user '$U' password '$P' page_size 8192;" \
    | "$ISQL" -q -user "$U" -pas "$P" >/dev/null 2>&1 || { echo "FAIL create $ENG"; exit 1; }
"$ISQL" -q -user "$U" -pas "$P" "127.0.0.1/3050:$ENG" >/tmp/identityvalid-build.log 2>&1 <<'SQL'
create table base (a integer);
commit;
SQL
if grep -qi error /tmp/identityvalid-build.log; then echo "FAIL building the fixture:"; sed 's/^/     /' /tmp/identityvalid-build.log; exit 1; fi
cp "$ENG" "$FC"; chmod 666 "$FC"

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-identityvalid.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null' EXIT
i=0; while [ $i -lt 20 ]; do
    kill -0 $srv 2>/dev/null || break
    ( exec 3<>"/dev/tcp/127.0.0.1/$PORT" ) 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
kill -0 $srv 2>/dev/null || { echo "FAIL fcwire is not running - port $PORT already in use?"; exit 1; }

fail=0
relcount() { printf "select count(*) c from rdb\$relations where rdb\$relation_name=upper('%s');\n" "$2" | "$ISQL" -q -user "$U" -pas "$P" "$1" 2>&1 | grep -oiE '[0-9]+' | tail -1; }
fldcount() { printf "select count(*) c from rdb\$relation_fields where rdb\$field_name=upper('%s');\n" "$2" | "$ISQL" -q -user "$U" -pas "$P" "$1" 2>&1 | grep -oiE '[0-9]+' | tail -1; }
runboth() { printf '%s\n' "$1" | "$ISQL" -q -user "$U" -pas "$P" "127.0.0.1/3050:$ENG" >/dev/null 2>&1; printf '%s\n' "$1" | "$ISQL" -q -user "$U" -pas "$P" "127.0.0.1/$PORT:$FC" >/dev/null 2>&1; }

create_state() { # <label> <create-sql> <tbl>  (engine's count is the oracle; fc must match)
    runboth "$2"
    local e f; e=$(relcount "127.0.0.1/3050:$ENG" "$3"); f=$(relcount "127.0.0.1/$PORT:$FC" "$3")
    if [ "$e" = "$f" ]; then echo "OK   $1 (created=$e)"; else echo "FAIL $1 eng-created=$e fc-created=$f"; fail=1; fi
}
add_state() { # <label> <alter-sql> <field>
    runboth "$2"
    local e f; e=$(fldcount "127.0.0.1/3050:$ENG" "$3"); f=$(fldcount "127.0.0.1/$PORT:$FC" "$3")
    if [ "$e" = "$f" ]; then echo "OK   $1 (added=$e)"; else echo "FAIL $1 eng-added=$e fc-added=$f"; fail=1; fi
}

echo "-- CREATE TABLE: a valid exact-numeric zero-scale identity is created --"
create_state "INTEGER identity"        "create table i_int (id integer generated always as identity);" "i_int"
create_state "BIGINT by default"       "create table i_big (id bigint generated by default as identity);" "i_big"
create_state "SMALLINT identity"       "create table i_sml (id smallint generated always as identity);" "i_sml"
create_state "NUMERIC(12,0) identity"  "create table i_n0 (id numeric(12,0) generated always as identity);" "i_n0"
create_state "INT128 identity"         "create table i_128 (id int128 generated always as identity);" "i_128"
echo "-- CREATE TABLE: an invalid identity type is REFUSED (no table) --"
create_state "NUMERIC(12,3) refused"   "create table b_ns (id numeric(12,3) generated always as identity);" "b_ns"
create_state "VARCHAR identity refused" "create table b_vc (id varchar(10) generated always as identity);" "b_vc"
create_state "DATE identity refused"   "create table b_dt (id date generated always as identity);" "b_dt"
create_state "DOUBLE identity refused" "create table b_db (id double precision generated always as identity);" "b_db"
echo "-- ALTER TABLE ADD: same rule --"
add_state "ADD valid integer id"       "alter table base add gid integer generated always as identity;" "gid"
add_state "ADD valid bigint id"        "alter table base add hid bigint generated by default as identity;" "hid"
add_state "ADD bad numeric(9,2) id"    "alter table base add nid numeric(9,2) generated always as identity;" "nid"
add_state "ADD bad varchar id"         "alter table base add vid varchar(5) generated always as identity;" "vid"
echo "-- controls: plain (non-identity) columns of any type are fine --"
create_state "plain table any types"   "create table plain (a numeric(12,3), b varchar(5), c date);" "plain"
add_state "ADD plain varchar column"   "alter table base add pln varchar(5);" "pln"

kill $srv 2>/dev/null; wait $srv 2>/dev/null; trap - EXIT
[ $fail = 0 ] && echo "PASS identityvalid" || echo "FAIL identityvalid"
exit $fail
