#!/bin/bash
# IDENTITY columns - GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY.
#
# An identity column is backed by an implicit generator. CREATE TABLE writes:
# an RDB$GENERATORS row named RDB$<n> (from a counter over RDB$GENERATORS, not
# the auto-domain one), RDB$SYSTEM_FLAG 6, its own security class + owner USAGE
# privilege, and its slot primed to start-increment; the column's
# RDB$RELATION_FIELDS row gets RDB$IDENTITY_TYPE (0 ALWAYS / 1 BY DEFAULT) and
# RDB$GENERATOR_NAME, is implicitly NOT NULL (RDB$NULL_FLAG, but no INTEG
# constraint); and the relation's RDB$RUNTIME carries the not-null, the
# generator name (tag 22) and the identity type (tag 23) - the summary the
# engine draws the next value from on insert. The generator's class follows the
# table's own in the SQL$<n> counter, so numbers still match.
#
# The differential is the engine, six ways:
#   1. fire-crab and the engine create the same table (two identity columns,
#      one ALWAYS with START WITH / INCREMENT BY) on two copies; every
#      RDB$RELATION_FIELDS identity attribute is compared;
#   2. every identity RDB$GENERATORS row is compared (system flag, initial,
#      increment, owner, security class);
#   3. the RDB$RUNTIME is compared BYTE FOR BYTE (the generator/identity tags);
#   4. the generators' primed values match (GEN_ID(g,0) = start - increment);
#   5. the engine applies the identity on insert: omitted columns take the next
#      value (respecting START WITH / INCREMENT BY);
#   6. gbak round trip and gfix -v -full on fire-crab's raw file.
#
#   qa/serve-real-identity.sh [port]
#
# Builds its own scratch databases.

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"; GFIX="${GFIX:-gfix}"; GBAK="${GBAK:-gbak}"
PORT="${1:-4221}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
WORK="$D/fc-idn-work.fdb"; REF="$D/fc-idn-ref.fdb"
FBK="$D/fc-idn-work.fbk"; RST="$D/fc-idn-rst.fdb"

command -v node >/dev/null 2>&1 || { echo "SKIP node not found"; exit 0; }
mkdir -p "$D"; rm -f "$WORK" "$REF" "$FBK" "$RST"

DDL="CREATE TABLE T (ID INTEGER GENERATED BY DEFAULT AS IDENTITY, N VARCHAR(3), C BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 5))"

"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL ref db"; exit 1; }
CREATE DATABASE '$REF' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
$DDL;
COMMIT;
EOF
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL work db"; exit 1; }
CREATE DATABASE '$WORK' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
COMMIT;
EOF

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-idn.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$WORK" "$REF" "$FBK" "$RST"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done

strip() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
node_once() {
    FC_DB="$WORK" FC_PORT="$PORT" FC_Q="$1" timeout 15 node -e '
      process.on("uncaughtException",()=>{console.log("CONN_ERR");process.exit(1);});
      const F=require("node-firebird");
      F.attach({host:"127.0.0.1",port:+process.env.FC_PORT,database:process.env.FC_DB,
                user:"SYSDBA",password:"masterkey"},(e,db)=>{
        if(e){console.log("CONN_ERR");process.exit(1);}
        db.query(process.env.FC_Q,(e2,r)=>{
          console.log(e2?("ERR "+(e2.message||"").split("\n")[0]):"OK");
          db.detach();process.exit(0);});
      });' 2>/dev/null
}
node_run() {
    n=0
    while [ $n -lt 10 ]; do
        r=$(node_once "$1")
        case "$r" in
            *CONN_ERR*|"") n=$((n + 1)); sleep 0.3 ;;
            *) printf '%s' "$r" | strip; return ;;
        esac
    done
    echo CONN_ERR
}

fail=0
check() { # <label> <got> <want>
    if [ "$2" = "$3" ]; then echo "OK   $1"; else
        echo "DIFF $1"; echo "     want: $3"; echo "     got:  $2"; fail=1; fi
}

check "fire-crab creates the identity table" "$(node_run "$DDL")" "OK"
kill $srv 2>/dev/null; wait $srv 2>/dev/null

# --- 1. the RF identity attributes ------------------------------------
rfq() { # <file>
    "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT TRIM(RDB$FIELD_NAME)||'|idt='||COALESCE(CAST(RDB$IDENTITY_TYPE AS VARCHAR(2)),'N')
       ||'|gen='||COALESCE(TRIM(RDB$GENERATOR_NAME),'N')
       ||'|nf='||COALESCE(CAST(RDB$NULL_FLAG AS VARCHAR(2)),'N')
  FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME='T' ORDER BY RDB$FIELD_POSITION;
SQL
}
work_rf=$(rfq "$WORK")
check "every RDB\$RELATION_FIELDS identity attribute matches the engine" "$work_rf" "$(rfq "$REF")"
case "$work_rf" in
    *"ID|idt=1|gen=RDB\$1|nf=1"*"C|idt=0|gen=RDB\$2|nf=1"*)
        echo "OK   ID is BY DEFAULT, C is ALWAYS, both NOT NULL, backed by RDB\$1/RDB\$2" ;;
    *) echo "DIFF the RF comparison was vacuous or wrong"; echo "     $work_rf"; fail=1 ;;
esac
# no INTEG constraint for the implicit not-null
intq() { "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT 'integ='||COUNT(*) FROM RDB$RELATION_CONSTRAINTS WHERE RDB$RELATION_NAME='T' AND RDB$CONSTRAINT_TYPE='NOT NULL';
SQL
}
check "no NOT NULL constraint row for the implicit identity not-null" "$(intq "$WORK")" "$(intq "$REF")"

# --- 2. the identity generators ---------------------------------------
genq() { # <file>
    "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT TRIM(RDB$GENERATOR_NAME)||'|sys='||RDB$SYSTEM_FLAG||'|init='||RDB$INITIAL_VALUE
       ||'|inc='||RDB$GENERATOR_INCREMENT||'|own='||TRIM(RDB$OWNER_NAME)||'|sc='||TRIM(RDB$SECURITY_CLASS)
  FROM RDB$GENERATORS WHERE RDB$SYSTEM_FLAG=6 ORDER BY RDB$GENERATOR_NAME;
SQL
}
check "every identity RDB\$GENERATORS row matches the engine" "$(genq "$WORK")" "$(genq "$REF")"

# --- 3. the runtime byte for byte -------------------------------------
rtq() { # <file>
    b=$("$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>/dev/null <<'SQL' | grep -oE '[0-9a-f]+:[0-9a-f]+' | head -1
SET LIST ON;
SELECT RDB$RUNTIME FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T';
SQL
)
    [ -n "$b" ] || { echo "(none)"; return; }
    rm -f /tmp/fc-idn-rt.bin
    printf 'BLOBDUMP %s /tmp/fc-idn-rt.bin;\n' "$b" | "$ISQL" -q -user "$U" -pas "$P" "$1" >/dev/null 2>&1
    od -An -tu1 -v /tmp/fc-idn-rt.bin | tr '\n' ' ' | tr -s ' ' | strip
}
check "the RDB\$RUNTIME matches the engine byte for byte (identity tags)" "$(rtq "$WORK")" "$(rtq "$REF")"

# --- 4. the generators' primed values ---------------------------------
valq() { "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT 'v1='||GEN_ID(RDB$1,0)||'|v2='||GEN_ID(RDB$2,0) FROM RDB$DATABASE;
SQL
}
check "the generators are primed to start - increment (0 and 95)" "$(valq "$WORK")" "$(valq "$REF")"

# --- 5. the engine applies the identity on insert ---------------------
"$ISQL" -q -b -user "$U" -pas "$P" "$WORK" >/dev/null 2>&1 <<'SQL'
INSERT INTO T (N) VALUES ('a');
INSERT INTO T (N) VALUES ('b');
COMMIT;
SQL
applied=$("$ISQL" -q -b -user "$U" -pas "$P" "$WORK" 2>&1 <<'SQL' | strip | grep -v '^$' | tr '\n' ',' | sed 's/,$//'
SET HEADING OFF;
SELECT TRIM(N)||':'||ID||'/'||C FROM T ORDER BY N;
SQL
)
check "the engine auto-generates the identities on insert (ID 1,2; C 100,105)" "$applied" "a:1/100,b:2/105"

# --- 6. gbak and gfix -------------------------------------------------
if "$GBAK" -b -g -user "$U" -pas "$P" "$WORK" "$FBK" >/tmp/fc-idn-backup.log 2>&1; then
    echo "OK   gbak backs up the database fire-crab wrote"
else
    echo "DIFF gbak backup"; cat /tmp/fc-idn-backup.log; fail=1
fi
"$GBAK" -c -user "$U" -pas "$P" "$FBK" "$RST" >/tmp/fc-idn-restore.log 2>&1
rc=$?
if [ $rc -eq 0 ] && ! grep -qiE "error" /tmp/fc-idn-restore.log; then
    echo "OK   gbak RESTORES it"
else
    echo "DIFF gbak restore (exit $rc)"; grep -iE "error|cannot" /tmp/fc-idn-restore.log | head; fail=1
fi
valw=$("$GFIX" -v -full -user "$U" -pas "$P" "$WORK" 2>&1)
check "gfix -v -full clean (fc's raw file)" "$(printf '%s' "$valw" | strip)" ""

exit $fail
