#!/bin/bash
# `gfix -mode read_only`, AND WHAT A READ-ONLY DATABASE REFUSES.
#
# The flag is one bit - `hdr_read_only` (0x20) in the header page, the
# same place the other gfix switches live - and it was deliberately left
# for last, because the bit is not the work: the REFUSAL PATH is. A
# server that set the bit and went on answering writes would have turned
# the switch into a lie.
#
# Every law below was measured against the live engine before anything was
# written, and each one is a place a converter would guess wrong:
#
#   * the MODE SWITCH TAKES THE DATABASE EXCLUSIVELY, and it does so
#     BEFORE deciding whether the mode would change at all - so `-mode
#     read_only` on a database that is ALREADY read-only still refuses
#     while somebody is attached. `isc_lock_timeout` + `isc_obj_in_use`
#     naming the FILE, immediately (not after a wait), and the header
#     untouched.
#   * ...and it is the ONLY switch that does. `-write`, `-buffers` and
#     `-housekeeping` change the header with an attachment held. A gate
#     that only checked the mode would call the exclusivity a general
#     rule; this checks both sides of it.
#   * ON a read-only database, those same switches are REFUSED
#     ("attempted update on read-only database") - while `-mode
#     read_write` still works, which is how the file gets out again.
#   * a WRITE gets `isc_read_only_database` in ONE of TWO SHAPES: the
#     code alone for DML, an identity draw, `NEXT VALUE FOR` and an
#     EXECUTE BLOCK that writes; the code behind "Dynamic SQL Error" for
#     DDL, which the engine refuses at PREPARE.
#   * a SELECT still answers, and so does `GEN_ID(g, 0)` - the
#     zero-increment READ of a sequence, which is not a write.
#
# RECORDED BOUNDARIES (assertions, not comments): `ALTER TABLE` and `DROP
# TABLE` come wrapped in `isc_no_meta_update` + "<statement> failed", and
# DROP carries the Dynamic SQL Error inside that wrapper where ALTER does
# not. This server has no `no_meta_update` wrapper for any DDL failure
# yet, so those two shapes are held as boundaries with the engine's exact
# text in the gate.
#
# THE TWO SERVERS GET THEIR OWN DATABASE FILE: a read-only file is a
# property of the FILE, so a shared one would have both servers refusing
# each other's writes.
#
#   qa/serve-real-readonly.sh [port]

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"
GFIX="${GFIX:-gfix}"
GSTAT="${GSTAT:-gstat}"
PORT="${1:-4715}"
REAL="${FC_REAL_PORT:-3050}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
DBE="$D/fc-readonly-engine.fdb"
DBF="$D/fc-readonly-crab.fdb"
LOG="/tmp/fc-serve-readonly-$PORT.log"
fail=0
ran=0
mkdir -p "$D"

build() { # <path>
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF >/dev/null 2>&1 || { echo "FAIL create $1"; exit 1; }
CREATE DATABASE '$1' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
CREATE TABLE T (ID INTEGER NOT NULL PRIMARY KEY, V INTEGER);
CREATE TABLE ID2 (ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, V INTEGER);
CREATE SEQUENCE G;
COMMIT;
INSERT INTO T VALUES (1, 10);
COMMIT;
EOF
}
rm -f "$DBE" "$DBF"
build "$DBE"; build "$DBF"; chmod 666 "$DBE" "$DBF"

FC_SRV_TRACE=1 "$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >"$LOG" 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$DBE" "$DBF" "$D/fc-readonly.fifo"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
kill -0 $srv 2>/dev/null || { echo "FAIL fcwire is not running - port $PORT in use?"; exit 1; }

ECONN="127.0.0.1/$REAL:$DBE"
FCONN="127.0.0.1/$PORT:$DBF"

sql() { # <conn> <sql>
    printf '%s\n' "$2" | timeout 30 "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 |
        sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | grep -v '^$' | tr '\n' '|'
}
both() { # <label> <sql>
    local e c
    e=$(sql "$ECONN" "$2"); c=$(sql "$FCONN" "$2")
    ran=$((ran + 1))
    if [ "$e" = "$c" ]; then echo "OK   $1 [$e]"
    else echo "DIFF $1"; echo "     engine: $e"; echo "     fc:     $c"; fail=1; fi
}
# gfix, run against each server's own database, with rc and output compared
# Each server has its OWN file, so an error naming the file cannot match
# literally - the NAME is normalised to <db> and the rest must be equal.
# (That the name is the right one is checked by the in-use section, which
# greps each side's own path.)
gfix_both() { # <label> <switch...>
    local eo ec ro rc
    eo=$("$GFIX" "$@" -user "$U" -pas "$P" "$ECONN" 2>&1 | sed "s|$DBE|<db>|g" | tr '\n' '|'); ro=$?
    ec=$("$GFIX" "$@" -user "$U" -pas "$P" "$FCONN" 2>&1 | sed "s|$DBF|<db>|g" | tr '\n' '|'); rc=$?
    ran=$((ran + 1))
    if [ "$eo|rc=$ro" = "$ec|rc=$rc" ]; then
        echo "OK   gfix $* [rc=$ro] [$eo]"
    else
        echo "DIFF gfix $*"
        echo "     engine: rc=$ro [$eo]"
        echo "     fc:     rc=$rc [$ec]"
        fail=1
    fi
}
attrs() { # <file> - the header attributes, gstat as the oracle for both
    "$GSTAT" -h -user "$U" -pas "$P" "$1" 2>&1 |
        sed -n 's/^[[:space:]]*Attributes[[:space:]]*//p' | tr -d '\n'
}
attrs_both() { # <label>
    local e c
    e=$(attrs "$DBE"); c=$(attrs "$DBF")
    ran=$((ran + 1))
    if [ "$e" = "$c" ]; then echo "OK   $1 [$e]"
    else echo "DIFF $1"; echo "     engine: [$e]"; echo "     fc:     [$c]"; fail=1; fi
}
# hold an attachment open on ONE server through a fifo-fed isql
FIFO="$D/fc-readonly.fifo"
hold() { # <conn>
    rm -f "$FIFO"; mkfifo "$FIFO"
    ( timeout 60 "$ISQL" -q -user "$U" -pas "$P" "$1" <"$FIFO" >/dev/null 2>&1 ) &
    holder=$!
    exec 9>"$FIFO"
    printf 'SELECT COUNT(*) FROM T;\n' >&9
    sleep 2
}
unhold() { printf 'QUIT;\n' >&9 2>/dev/null; exec 9>&-; wait $holder 2>/dev/null; rm -f "$FIFO"; }

# --- 1. THE EXCLUSIVE-ACCESS LAW, and that it belongs to the MODE only ---
# An attachment is held on each server, then every header switch is run.
# Only the mode refuses.
hold "$ECONN"; eholder=$holder; e9=1
# hold on fire-crab too, through a second fifo
FIFO2="$D/fc-readonly2.fifo"; rm -f "$FIFO2"; mkfifo "$FIFO2"
( timeout 60 "$ISQL" -q -user "$U" -pas "$P" "$FCONN" <"$FIFO2" >/dev/null 2>&1 ) &
fholder=$!
exec 8>"$FIFO2"
printf 'SELECT COUNT(*) FROM T;\n' >&8
sleep 2

gfix_both -write async
attrs_both "...and forced writes went off on both, attachment held"
gfix_both -buffers 700
gfix_both -housekeeping 999
gfix_both -mode read_only
attrs_both "...and the mode did NOT change on either, attachment held"
# ...and the object it names is THIS server's own database file
ran=$((ran + 1))
inuse=$("$GFIX" -mode read_only -user "$U" -pas "$P" "$FCONN" 2>&1)
if [ "${inuse#*$DBF}" != "$inuse" ]; then
    echo "OK   the in-use refusal names fire-crab's own file"
else
    echo "DIFF the in-use refusal does not name the file: [$inuse]"; fail=1
fi

printf 'QUIT;\n' >&8 2>/dev/null; exec 8>&-; wait $fholder 2>/dev/null; rm -f "$FIFO2"
printf 'QUIT;\n' >&9 2>/dev/null; exec 9>&-; wait $eholder 2>/dev/null; rm -f "$FIFO"

# --- 2. ...and with nobody attached it works -----------------------------
gfix_both -mode read_only
attrs_both "the header says read only on both"

# --- 3. WHAT A READ-ONLY DATABASE ANSWERS -------------------------------
both "a SELECT still answers" "SET HEADING OFF;
SELECT COUNT(*) FROM T;"
both "GEN_ID(g, 0) - the zero-increment READ - answers" "SET HEADING OFF;
SELECT GEN_ID(G, 0) FROM RDB\$DATABASE;"

# --- 4. THE BARE VECTOR: DML and the generator draws --------------------
both "INSERT is refused" "INSERT INTO T VALUES (2, 20);"
both "UPDATE is refused" "UPDATE T SET V = 99 WHERE ID = 1;"
both "DELETE is refused" "DELETE FROM T WHERE ID = 1;"
both "an INSERT drawing an identity is refused" "INSERT INTO ID2 (V) VALUES (1);"
both "SELECT NEXT VALUE FOR is refused" "SET HEADING OFF;
SELECT NEXT VALUE FOR G FROM RDB\$DATABASE;"
# The column list is not decoration: `INSERT ... VALUES` WITHOUT one is
# outside this server's PSQL surface (a recorded gap), and a block that
# used the bare form would refuse for THAT reason and look like a match.
both "an EXECUTE BLOCK that writes is refused (with its own position)" "SET TERM ^;
EXECUTE BLOCK AS BEGIN INSERT INTO T (ID, V) VALUES (99, 1); END^
SET TERM ;^"

# --- 5. THE DYNAMIC SQL ERROR FORM: DDL --------------------------------
both "CREATE TABLE is refused" "CREATE TABLE RO2 (X INTEGER);"
both "COMMENT ON is refused" "COMMENT ON TABLE T IS 'x';"
both "GRANT is refused" "GRANT SELECT ON T TO PUBLIC;"
both "SET GENERATOR is refused" "SET GENERATOR G TO 5;"
both "ALTER SEQUENCE ... RESTART is refused" "ALTER SEQUENCE G RESTART WITH 7;"

# --- 6. and the other header switches are refused too -------------------
gfix_both -write sync
gfix_both -housekeeping 123
attrs_both "...the header still says read only, nothing else changed"

# --- 7. THE WAY OUT ----------------------------------------------------
gfix_both -mode read_write
attrs_both "the mode is off again on both"
both "...and a write works" "INSERT INTO T VALUES (3, 30);
COMMIT;
SET HEADING OFF;
SELECT COUNT(*) FROM T;"

# --- 8. RECORDED BOUNDARIES --------------------------------------------
# The engine wraps a metadata statement's failure in `isc_no_meta_update`
# + "<statement> failed", and DROP carries the Dynamic SQL Error inside
# that wrapper where ALTER does not. This server has no such wrapper for
# ANY DDL failure, so these two are asserted to DIFFER - if one ever
# stops differing, this gate must say so rather than quietly agree.
gfix -mode read_only -user "$U" -pas "$P" "$ECONN" >/dev/null 2>&1
gfix -mode read_only -user "$U" -pas "$P" "$FCONN" >/dev/null 2>&1
boundary() { # <label> <sql> <engine-substring>
    local e c
    e=$(sql "$ECONN" "$2"); c=$(sql "$FCONN" "$2")
    ran=$((ran + 1))
    if [ "$e" != "$c" ] && [ "${e#*$3}" != "$e" ]; then
        echo "OK   boundary: $1 (engine [$e], fc [$c])"
    else
        echo "DIFF boundary MOVED: $1"
        echo "     engine: $e"
        echo "     fc:     $c"
        fail=1
    fi
}
# CREATE VIEW is not in this server's DDL surface at all - it READS views
# the engine created - so its refusal is the generic one whether the
# database is read-only or not. Asserted, so that the day CREATE VIEW
# lands this gate says the read-only vector has to come with it.
boundary "CREATE VIEW is outside the DDL surface, so the refusal is generic" \
    "CREATE VIEW VW AS SELECT ID FROM T;" "attempted update on read-only database"
boundary "ALTER TABLE carries the no_meta_update wrapper" \
    "ALTER TABLE T ADD Z INTEGER;" "unsuccessful metadata update"
boundary "DROP TABLE carries it AND the Dynamic SQL Error" \
    "DROP TABLE ID2;" "unsuccessful metadata update"

# --- 9. TEETH: the file is still a database, and still writable after ---
ran=$((ran + 1))
v=$("$GFIX" -v -full -user "$U" -pas "$P" "$DBF" 2>&1 | tr -d ' \n')
if [ -z "$v" ]; then echo "OK   gfix -v -full accepts fire-crab's file"
else echo "DIFF gfix -v -full: [$v]"; fail=1; fi
gfix_both -mode read_write
both "teeth: the same statements are ACCEPTED once the mode is off" \
"INSERT INTO T VALUES (4, 40);
COMMIT;
SET HEADING OFF;
SELECT COUNT(*) FROM T;"

echo "ran $ran checks"
exit $fail
