#!/bin/bash
# GENERATOR DURABILITY - the one carve-out in "the image is the truth".
#
# The engine treats generators as NON-TRANSACTIONAL. A draw - GEN_ID(g,n),
# NEXT VALUE FOR g, an identity column's implicit bump - survives
# ROLLBACK, ROLLBACK TO SAVEPOINT and a statement that FAILED: two
# dup-PK inserts drawing 7 then 5 leave the generator at 12 with the
# table empty, and an identity INSERT moves its sequence BEFORE it
# raises 335544665. fire-crab's only undo is the whole-image snapshot, so
# every draw inside an undone window used to retreat with the file - a
# WRONG ANSWER to an ordinary `SELECT GEN_ID(G1,0)`, not a durability
# footnote (0 here against the engine's 12).
#
# THE OTHER HALF OF THE LAW, re-probed for this gate and NOT what the
# roadmap entry claimed: `SET GENERATOR ... TO n`, `ALTER SEQUENCE ...
# RESTART WITH n` and `ALTER TABLE ... ALTER COLUMN ... RESTART WITH n`
# are TRANSACTIONAL. The entry had them "surviving verbatim" because the
# probe ran through isql with AUTODDL ON, which COMMITTED them before the
# rollback could see them.
#
# AND THE SHAPE OF THAT HALF, which the first cut of this gate got wrong
# by one axis: an absolute set does not merely "get rolled back". It
# leaves a COMPENSATING UNDO RECORD naming the value it FOUND, and the
# undo of a window replays those records in reverse. So undoing a window
# puts the generator back to the value it held just before that window's
# FIRST absolute set - and leaves the cell exactly where it is when the
# window holds none. Everything else follows from those two sentences:
#
#   advance to 51, RESTART WITH 3, ROLLBACK          -> 51 (the pre-set)
#   SET GENERATOR TO 3, advance to 4, ROLLBACK       -> 50 (the pre-set
#        again - the compensating record OUTLIVES the later draw, which
#        is the case a "replay the draws made inside the window" rule
#        answers 4 to)
#   advance to 10, SET GENERATOR TO 3, a FAILED
#        statement, COMMIT                           -> 3 (the undone
#        window is the statement, which holds neither)
#
# This gate asserts both halves, and the INTERACTION section below
# asserts them against each other.
#
# AND THE DDL INTERACTION: a rolled-back CREATE SEQUENCE must leave NO
# generator, advance or no advance; a rolled-back DROP SEQUENCE must
# leave the generator WITH the advance drawn inside the window.
#
# THE DIFFERENTIAL: the same script runs against a copy of one database
# through fire-crab and through the engine, and the ENGINE then reads
# BOTH files back - every phase compares the table rows AND every
# generator's STORED value. A matching row set over a diverged generator
# is still a wrong answer, which is why no phase compares rows alone.
#
#   qa/serve-real-gendurable.sh [port]

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"
GFIX="${GFIX:-gfix}"
PORT="${1:-4772}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
SRC="$D/gdu-src.fdb"
W=/tmp/fc-gdu-w.fdb
R=/tmp/fc-gdu-r.fdb

mkdir -p "$D"; rm -f "$SRC" "$W" "$R"
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF >/dev/null 2>&1 || { echo "FAIL create"; exit 1; }
CREATE DATABASE '$SRC' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
CREATE SEQUENCE G1;
CREATE SEQUENCE G2 START WITH 100 INCREMENT BY 5;
CREATE TABLE IDT (ID INTEGER NOT NULL PRIMARY KEY, V INTEGER);
CREATE TABLE AID (ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, V INTEGER);
COMMIT;
EOF

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-gdu.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$SRC" "$W" "$R"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
# The readiness probe above answers "SOMETHING is listening", not "OUR
# server is listening". If the port was already taken, fcwire exited at
# bind and every check below runs against the OTHER server - a gate that
# reports success while measuring nothing. Fatal, not a warning.
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

fail=0
ran=0
# the engine reading a generator's STORED value out of whichever file it
# is pointed at - fire-crab's own included. This is the reading that
# matters: it goes through the ODS, not through fire-crab's answer.
gen_of() { # <file> <generator>
    printf 'SET HEADING OFF;\nSELECT GEN_ID(%s, 0) FROM RDB$DATABASE;\n' "$2" |
        "$ISQL" -q -user "$U" -pas "$P" "$1" 2>&1 | tr -s ' \n' ' '
}
# does the generator exist in the catalog at all (the DDL-rollback half)
gen_exists() { # <file> <generator>
    printf "SET HEADING OFF;\nSELECT COUNT(*) FROM RDB\$GENERATORS WHERE RDB\$GENERATOR_NAME = '%s';\n" "$2" |
        "$ISQL" -q -user "$U" -pas "$P" "$1" 2>&1 | tr -d ' \n'
}
dump() { # <file>
    printf 'SET HEADING OFF;\nSELECT ID, COALESCE(V,-9) FROM IDT ORDER BY ID;\nSELECT ID, COALESCE(V,-9) FROM AID ORDER BY ID;\n' |
        "$ISQL" -q -user "$U" -pas "$P" "$1" 2>&1 | tr -s ' \n' ' '
}
# run one script through BOTH sides on fresh twins
drive() { # <script>
    rm -f "$W" "$R"; cp "$SRC" "$W"; cp "$SRC" "$R"
    printf '%s\n' "$1" | "$ISQL" -q -user "$U" -pas "$P" "127.0.0.1/$PORT:$W" >/dev/null 2>&1
    printf '%s\n' "$1" | "$ISQL" -q -user "$U" -pas "$P" "$R" >/dev/null 2>&1
}
cmp_one() { # <label> <ours> <theirs>
    ran=$((ran + 1))
    if [ "$2" = "$3" ]; then
        echo "OK   $1"
    else
        echo "DIFF $1"; echo "     engine: [$3]"; echo "     fc:     [$2]"; fail=1
    fi
}
# EVERY phase re-reads the generators from BOTH files, then the rows.
same() { # <label> <script> [extra generator ...]
    lbl="$1"; sc="$2"; shift 2
    drive "$sc"
    for g in G1 G2 'RDB$1' "$@"; do
        cmp_one "$lbl | stored $g" "$(gen_of "$W" "$g")" "$(gen_of "$R" "$g")"
    done
    cmp_one "$lbl | rows" "$(dump "$W")" "$(dump "$R")"
}

# --- THE ADVANCE SURVIVES AN UNDO ---------------------------------------
same "GEN_ID advance then ROLLBACK" "SELECT GEN_ID(G1,7) FROM RDB\$DATABASE;
ROLLBACK;"
same "NEXT VALUE FOR then ROLLBACK" "SELECT NEXT VALUE FOR G1 FROM RDB\$DATABASE;
ROLLBACK;"
same "an INCREMENT BY 5 sequence, drawn then rolled back" "SELECT NEXT VALUE FOR G2 FROM RDB\$DATABASE;
ROLLBACK;"
# a NEGATIVE step is an advance too: the LAST drawn value wins, not the
# maximum (probed: 10, then GEN_ID(g,-4), then ROLLBACK leaves 6)
same "a NEGATIVE step then ROLLBACK (the last value, not the max)" "SELECT GEN_ID(G1,10) FROM RDB\$DATABASE;
COMMIT;
SELECT GEN_ID(G1,-4) FROM RDB\$DATABASE;
ROLLBACK;"
same "advance then ROLLBACK TO SAVEPOINT" "SAVEPOINT S;
SELECT GEN_ID(G1,7) FROM RDB\$DATABASE;
ROLLBACK TO S;
COMMIT;"
same "advance, mark, advance, ROLLBACK TO the mark" "SELECT GEN_ID(G1,7) FROM RDB\$DATABASE;
SAVEPOINT S;
SELECT GEN_ID(G1,5) FROM RDB\$DATABASE;
ROLLBACK TO S;
COMMIT;"
same "a rolled-back draw then a kept draw" "SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ROLLBACK;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
COMMIT;"
same "a per-row advance over a table, then ROLLBACK" "INSERT INTO IDT VALUES (1,0);
INSERT INTO IDT VALUES (2,0);
INSERT INTO IDT VALUES (3,0);
COMMIT;
SELECT GEN_ID(G1,1) FROM IDT;
ROLLBACK;"
same "two sequences drawn in one window, both rolled back" "SELECT GEN_ID(G1,3) FROM RDB\$DATABASE;
SELECT NEXT VALUE FOR G2 FROM RDB\$DATABASE;
ROLLBACK;"

# --- THE FAILED STATEMENT STILL BURNS -----------------------------------
# the loudest case: the INSERT raises 23000 and the generator has ALREADY
# moved. Both spellings of the surrounding transaction, because the
# retreat had two separate causes - the discarded work buffer and the
# whole-image restore behind it.
same "a dup-PK INSERT that drew: the draws BURN (committed txn)" "INSERT INTO IDT (ID,V) VALUES (1, GEN_ID(G1,7));
INSERT INTO IDT (ID,V) VALUES (1, GEN_ID(G1,5));
COMMIT;"
same "a dup-PK INSERT that drew: the draws BURN (rolled-back txn)" "INSERT INTO IDT (ID,V) VALUES (1, GEN_ID(G1,7));
INSERT INTO IDT (ID,V) VALUES (1, GEN_ID(G1,5));
ROLLBACK;"
same "an identity INSERT that collides moves its sequence first" "INSERT INTO AID (ID,V) VALUES (1,1);
COMMIT;
INSERT INTO AID (V) VALUES (2);
COMMIT;"
# THE READABLE ROW DIVERGENCE: after a rolled-back identity INSERT the
# NEXT row must not re-use the drawn id. fire-crab answered ID 1 where
# the engine answers ID 3 - a diverged ROW, visible without ever naming
# a generator.
same "a rolled-back identity INSERT does not hand the id back" "INSERT INTO AID (V) VALUES (1);
INSERT INTO AID (V) VALUES (2);
ROLLBACK;
INSERT INTO AID (V) VALUES (3);
COMMIT;"
same "INSERT ... SELECT drawing identities, failing partway" "INSERT INTO IDT VALUES (1,10);
INSERT INTO IDT VALUES (2,20);
INSERT INTO IDT VALUES (3,30);
INSERT INTO AID (ID,V) VALUES (2,99);
COMMIT;
INSERT INTO AID (V) SELECT V FROM IDT ORDER BY ID;
COMMIT;"
same "INSERT ... SELECT drawing identities, then ROLLBACK" "INSERT INTO IDT VALUES (1,10);
INSERT INTO IDT VALUES (2,20);
COMMIT;
INSERT INTO AID (V) SELECT V FROM IDT ORDER BY ID;
ROLLBACK;"

# --- THE OTHER HALF: AN ABSOLUTE SET IS TRANSACTIONAL -------------------
# `SET AUTODDL OFF` is load-bearing in every phase below. With isql's
# default AUTODDL ON the ALTER commits itself and the ROLLBACK has
# nothing left to undo - which is exactly how the roadmap entry came to
# record these as surviving. Both sides run the same script, so the
# setting cannot make the two disagree; it decides WHICH LAW is measured.
same "SET GENERATOR TO is UNDONE by ROLLBACK" "SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SET GENERATOR G1 TO 3;
ROLLBACK;"
same "ALTER SEQUENCE RESTART WITH is UNDONE by ROLLBACK" "SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
ALTER SEQUENCE G1 RESTART WITH 3;
ROLLBACK;"
# the two halves meeting: the ADVANCE survives the undo, the RESTART on
# top of it does not, so the answer is the advanced value - neither the
# pre-transaction one nor the restarted one
same "advance, then RESTART, then ROLLBACK: the ADVANCE wins" "SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ALTER SEQUENCE G1 RESTART WITH 3;
ROLLBACK;"
same "SET GENERATOR, then advance, then ROLLBACK" "SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET GENERATOR G1 TO 3;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ROLLBACK;"
# a COMMITTED absolute set must not be dragged back by a burn recorded
# before it - the burn belongs to the image the commit made the new base
same "a COMMITTED RESTART, then an advance, then ROLLBACK" "SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
ALTER SEQUENCE G1 RESTART WITH 3;
COMMIT;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ROLLBACK;"
same "a COMMITTED SET GENERATOR, then an empty ROLLBACK" "SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET GENERATOR G1 TO 3;
COMMIT;
ROLLBACK;"

# --- THE DDL INTERACTION ------------------------------------------------
# A generator the rollback UN-CREATED must not come back carrying its
# advance. This is the guard that keeps the carve-out from inventing a
# catalog entry: the burn is applied by NAME into the RESTORED image, so
# a name that is not there is dropped with the CREATE.
ddl() { # <label> <generator> <script>
    drive "$3"
    cmp_one "$1 | exists $2" "$(gen_exists "$W" "$2")" "$(gen_exists "$R" "$2")"
    cmp_one "$1 | stored $2" "$(gen_of "$W" "$2")" "$(gen_of "$R" "$2")"
}
ddl "a rolled-back CREATE SEQUENCE leaves nothing" GNEW "SET AUTODDL OFF;
CREATE SEQUENCE GNEW;
SELECT GEN_ID(GNEW,9) FROM RDB\$DATABASE;
ROLLBACK;"
ddl "a COMMITTED CREATE SEQUENCE keeps the rolled-back advance" GNEW "SET AUTODDL OFF;
CREATE SEQUENCE GNEW;
COMMIT;
SET AUTODDL OFF;
SELECT GEN_ID(GNEW,9) FROM RDB\$DATABASE;
ROLLBACK;"
ddl "a rolled-back DROP SEQUENCE keeps the advance" G1 "SET AUTODDL OFF;
SELECT GEN_ID(G1,6) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
DROP SEQUENCE G1;
ROLLBACK;"

# --- THE INTERACTION: AN ABSOLUTE SET MEETS AN UNDO ---------------------
# THE AXIS THE PHASES ABOVE NEVER VARY, and the reason they missed a
# whole class of wrong answer: WHERE the absolute set sits relative to
# the draw, and WHICH window the undo actually closes. Every phase above
# puts the draw first and undoes the whole transaction; a burn scoped to
# the TRANSACTION passes all of them and still overwrites a set that was
# written after the draw and that no undo reached.
#
# The cross is {SET GENERATOR TO, ALTER SEQUENCE RESTART WITH, ALTER
# TABLE ALTER COLUMN RESTART WITH} x {a failed statement, ROLLBACK TO a
# mark that ENCLOSES the pair, ROLLBACK TO a mark set AFTER it, a full
# ROLLBACK, a COMMIT with no undo at all} x {the set BEFORE the draw, and
# AFTER it}. Each phase ends by writing the generator's next value into a
# ROW, so every one of them is also readable the way a client reads it -
# the identity spelling never types GEN_ID at all.
READBACK='SET AUTODDL OFF;
INSERT INTO IDT (ID,V) VALUES (9, GEN_ID(G1,1));
INSERT INTO AID (V) VALUES (8);
COMMIT;'
for setkind in SETGEN ALTSEQ ALTCOL; do
    case "$setkind" in
    SETGEN) sset='SET GENERATOR G1 TO 3;'
            sdraw='SELECT GEN_ID(G1,1) FROM RDB$DATABASE;' ;;
    ALTSEQ) sset='ALTER SEQUENCE G1 RESTART WITH 3;'
            sdraw='SELECT GEN_ID(G1,1) FROM RDB$DATABASE;' ;;
    # the identity spelling reaches the backing RDB$<n> generator, and
    # its draw is an ordinary INSERT - the R4 shape
    ALTCOL) sset='ALTER TABLE AID ALTER COLUMN ID RESTART WITH 100;'
            sdraw='INSERT INTO AID (V) VALUES (7);' ;;
    esac
    for undo in FAILED RBSPOUT RBSPIN ROLLBACK COMMIT; do
        case "$undo" in
        # the undone window is the STATEMENT, which holds neither the
        # set nor the draw
        FAILED)   umark=''
                  uend='INSERT INTO IDT (ID,V) VALUES (1,1);
INSERT INTO IDT (ID,V) VALUES (1,2);
COMMIT;' ;;
        # the mark ENCLOSES the pair: the undo reaches the set
        RBSPOUT)  umark='SAVEPOINT SP;'
                  uend='ROLLBACK TO SP;
COMMIT;' ;;
        # the mark is set AFTER the pair: the undo reaches neither
        RBSPIN)   umark=''
                  uend='SAVEPOINT SP;
INSERT INTO IDT (ID,V) VALUES (5,5);
ROLLBACK TO SP;
COMMIT;' ;;
        ROLLBACK) umark=''; uend='ROLLBACK;' ;;
        COMMIT)   umark=''; uend='COMMIT;' ;;
        esac
        for order in BEFORE AFTER; do
            case "$order" in
            BEFORE) body="$sset
$sdraw" ;;
            AFTER)  body="$sdraw
$sset" ;;
            esac
            same "INTERACTION $setkind/$undo/set-$order" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
INSERT INTO AID (V) VALUES (1);
COMMIT;
SET AUTODDL OFF;
$umark
$body
$uend
$READBACK"
        done
    done
done

# NESTING, RELEASE, AND TWO UNDOS OF DIFFERENT KINDS. A compensating
# record belongs to the mark it was made under: an inner RELEASE hands it
# to the enclosing mark (so an outer rollback still puts the value back),
# an inner ROLLBACK TO consumes it (so the outer rollback must NOT put it
# back a second time).
same "nested marks, the set under the INNER one" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SAVEPOINT S1;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
SAVEPOINT S2;
SET GENERATOR G1 TO 3;
ROLLBACK TO S2;
COMMIT;"
same "nested marks, inner undo then an OUTER rollback" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
SAVEPOINT S2;
SET GENERATOR G1 TO 3;
ROLLBACK TO S2;
ROLLBACK;"
same "an inner RELEASE hands the set to the outer mark" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SAVEPOINT S1;
SAVEPOINT S2;
SET GENERATOR G1 TO 3;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
RELEASE SAVEPOINT S2;
ROLLBACK TO S1;
COMMIT;"
same "RELEASE, then a full ROLLBACK" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SAVEPOINT S1;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ALTER SEQUENCE G1 RESTART WITH 3;
RELEASE SAVEPOINT S1;
ROLLBACK;"
same "the same mark name declared twice" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SAVEPOINT S1;
SET GENERATOR G1 TO 3;
SAVEPOINT S1;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ROLLBACK TO S1;
COMMIT;"
same "two undos of different kinds in one transaction" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SAVEPOINT SP;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ROLLBACK TO SP;
SET GENERATOR G1 TO 3;
INSERT INTO IDT (ID,V) VALUES (1,1);
INSERT INTO IDT (ID,V) VALUES (1,2);
COMMIT;"
same "three marks deep, undo the OUTERMOST one" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SAVEPOINT S1;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
SAVEPOINT S2;
SET GENERATOR G1 TO 3;
SAVEPOINT S3;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ROLLBACK TO S1;
COMMIT;"
same "a mark that sets ONE sequence and draws ANOTHER" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SAVEPOINT SP;
SET GENERATOR G1 TO 3;
SELECT NEXT VALUE FOR G2 FROM RDB\$DATABASE;
ROLLBACK TO SP;
COMMIT;"
same "two sequences, only ONE of them absolutely set" "SET AUTODDL OFF;
SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
SELECT NEXT VALUE FOR G2 FROM RDB\$DATABASE;
SET GENERATOR G1 TO 3;
ROLLBACK;"
same "a sequence created, drawn, set and rolled back in one window" "SET AUTODDL OFF;
CREATE SEQUENCE GNEW;
SELECT GEN_ID(GNEW,9) FROM RDB\$DATABASE;
SET GENERATOR GNEW TO 3;
ROLLBACK;"
same "INSERT ... SELECT failing partway, over an absolute set" "INSERT INTO IDT VALUES (1,10);
INSERT INTO IDT VALUES (2,20);
INSERT INTO IDT VALUES (3,30);
INSERT INTO AID (ID,V) VALUES (2,99);
COMMIT;
SET AUTODDL OFF;
ALTER TABLE AID ALTER COLUMN ID RESTART WITH 100;
INSERT INTO AID (V) SELECT V FROM IDT ORDER BY ID;
COMMIT;"

# --- teeth --------------------------------------------------------------
# The differential above is symmetric: a phase where BOTH sides retreat
# would read OK. These pin the ENGINE'S OWN NUMBERS, so the gate still
# fails if the engine and fire-crab retreat together.
teeth() { # <label> <generator> <want> <script>
    drive "$4"
    got=$(gen_of "$W" "$2" | tr -d ' ')
    ran=$((ran + 1))
    if [ "$got" = "$3" ]; then
        echo "OK   teeth: $1 (fc stores $got)"
    else
        echo "DIFF teeth: $1 - fc stores [$got], want $3"; fail=1
    fi
}
teeth "an advance survives ROLLBACK" G1 7 "SELECT GEN_ID(G1,7) FROM RDB\$DATABASE;
ROLLBACK;"
teeth "two failed draws burn 7+5" G1 12 "INSERT INTO IDT (ID,V) VALUES (1, GEN_ID(G1,7));
INSERT INTO IDT (ID,V) VALUES (1, GEN_ID(G1,5));
ROLLBACK;"
teeth "a rolled-back SET GENERATOR really is undone" G1 50 "SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SET GENERATOR G1 TO 3;
ROLLBACK;"
# THE FOUR NUMBERS THE WHOLE INTERACTION TURNS ON, pinned so that no
# rescoping of the record can quietly satisfy the symmetric compare by
# moving both sides. The first two pull in opposite directions and any
# rule that gets one by giving up the other is wrong.
teeth "the undone window is the TRANSACTION: the draw before the set wins" G1 51 \
"SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ALTER SEQUENCE G1 RESTART WITH 3;
ROLLBACK;"
teeth "the undone window is the STATEMENT: the set stands" G1 3 \
"SET AUTODDL OFF;
SELECT GEN_ID(G1,10) FROM RDB\$DATABASE;
SET GENERATOR G1 TO 3;
INSERT INTO IDT (ID,V) VALUES (1,1);
INSERT INTO IDT (ID,V) VALUES (1,2);
COMMIT;"
teeth "the set outlives a draw made AFTER it" G1 50 \
"SELECT GEN_ID(G1,50) FROM RDB\$DATABASE;
COMMIT;
SET AUTODDL OFF;
SET GENERATOR G1 TO 3;
SELECT GEN_ID(G1,1) FROM RDB\$DATABASE;
ROLLBACK;"
teeth "the same, reached through ALTER SEQUENCE" G1 2 \
"SET AUTODDL OFF;
SELECT GEN_ID(G1,10) FROM RDB\$DATABASE;
ALTER SEQUENCE G1 RESTART WITH 3;
INSERT INTO IDT (ID,V) VALUES (1,1);
INSERT INTO IDT (ID,V) VALUES (1,2);
COMMIT;"
# ...and the same law read as a ROW, which is how a client meets it: an
# identity column must NOT hand back an id the RESTART moved past just
# because a later statement failed.
rowteeth() { # <label> <want> <script>
    drive "$3"
    got=$(printf 'SET HEADING OFF;\nSELECT ID FROM AID ORDER BY ID DESC ROWS 1;\n' |
        "$ISQL" -q -user "$U" -pas "$P" "$W" 2>&1 | tr -d ' \n')
    ran=$((ran + 1))
    if [ "$got" = "$2" ]; then
        echo "OK   teeth: $1 (fc writes id $got)"
    else
        echo "DIFF teeth: $1 - fc writes id [$got], want $2"; fail=1
    fi
}
rowteeth "an identity RESTART survives a later statement's failure" 100 \
"SET AUTODDL OFF;
INSERT INTO AID (V) VALUES (1);
INSERT INTO AID (V) VALUES (2);
INSERT INTO AID (V) VALUES (3);
ALTER TABLE AID ALTER COLUMN ID RESTART WITH 100;
INSERT INTO IDT (ID,V) VALUES (1,1);
INSERT INTO IDT (ID,V) VALUES (1,2);
INSERT INTO AID (V) VALUES (9);
COMMIT;"
# ...and the file the carve-out wrote is still a valid database: the burn
# edits the generator page of an image that was just restored wholesale
val=$("$GFIX" -v -full -user "$U" -pas "$P" "$W" 2>&1 | tr -s ' \n' ' ')
ran=$((ran + 1))
if [ -z "$(printf '%s' "$val" | tr -d ' ')" ]; then
    echo "OK   gfix -v -full accepts the file the burn wrote"
else
    echo "DIFF gfix after a generator burn: $val"; fail=1
fi

echo "ran $ran"
exit $fail
