#!/bin/bash
# IDENTITY columns AT INSERT TIME - the generator actually firing.
#
# serve-real-identity.sh gates the DDL side (fire-crab CREATE TABLE
# writes the same RDB$RELATION_FIELDS / RDB$GENERATORS / RDB$RUNTIME
# bytes the engine does; its insert step runs through isql). This gate
# is the OTHER half: INSERT through fire-crab on ENGINE-created identity
# tables (fc-created catalogs are byte-identical, so one read path
# serves both - that equivalence is the other gate's assertion).
#
# The probed laws (FB6 LI-T6.0.0.2076):
#   * an identity column OMITTED from the column list takes the next
#     value from its backing RDB$n generator - 1, 2, ... and, with
#     START WITH 100 INCREMENT BY 5, 100, 105, ...;
#   * `RETURNING ID` answers the ASSIGNED value as the type-8 OBJ
#     singleton (op_execute2), on BOTH driver generations;
#   * an EXPLICIT value into a BY DEFAULT column is stored as given and
#     the generator does NOT advance (later inserts may collide -
#     engine-faithful);
#   * an explicit value into a GENERATED ALWAYS column WITHOUT
#     OVERRIDING refuses AT PREPARE (isc_overriding_missing, 335545137,
#     SQLSTATE 42000) - and the IMPLICIT column list counts too. fc
#     used to ACCEPT AND WRITE that row - the wrong write this gate is
#     the regression fence for;
#   * an explicit NULL does NOT trigger generation - it is a validation
#     error (23000), no row.
#
# Twin pattern (serve-real-returning.sh): every statement runs through
# the SAME driver against fire-crab (file A) and the live engine (file
# B); the rows AND the error shapes must match, and at the end the
# ENGINE reads identical rows and identical GEN_ID from both files.
#
#   qa/serve-real-identity2.sh [port]

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"; GFIX="${GFIX:-gfix}"; GBAK="${GBAK:-gbak}"
PORT="${1:-4331}"
REAL="${FC_REAL_PORT:-3050}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
A="$D/fc-idn2-crab.fdb"
B="$D/fc-idn2-engine.fdb"
FBK="$D/fc-idn2-crab.fbk"; RST="$D/fc-idn2-rst.fdb"

command -v node >/dev/null 2>&1 || { echo "SKIP node not found"; exit 0; }
# both driver generations (the outblr pattern): the type-8 singleton
# dispatch must hold through stock 2.11.0 and the patched 2.14.1
N211="${N211:-/home/ubuntu/conceptual-architecture-for-firebird-paper/samples/nodejs/node_modules}"
N214="${N214:-${NODE_PATH:-/home/ubuntu/work}}"
NODE_PATH="$N211" node -e "require('node-firebird')" 2>/dev/null || { echo "SKIP node-firebird 2.11.0 not found"; exit 0; }
NODE_PATH="$N214" node -e "require('node-firebird')" 2>/dev/null || { echo "SKIP node-firebird 2.14.1 not found"; exit 0; }
mkdir -p "$D"
fail=0

# ENGINE-created identity tables, in a fixed order so the backing
# generators are RDB$1 (IDT), RDB$2 (IDA), RDB$3 (IDS) in both files
make_db() {
    rm -f "$1"
    "$ISQL" -q -b -user "$U" -pas "$P" <<EOF >/dev/null 2>&1 || return 1
CREATE DATABASE '$1' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
CREATE TABLE IDT (ID INTEGER GENERATED BY DEFAULT AS IDENTITY, V VARCHAR(10));
CREATE TABLE IDA (ID INTEGER GENERATED ALWAYS AS IDENTITY, V VARCHAR(10));
CREATE TABLE IDS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5), V VARCHAR(10));
COMMIT;
EOF
    chmod 666 "$1"
}
make_db "$A" || { echo "FAIL scratch A"; exit 1; }
make_db "$B" || { echo "FAIL scratch B"; exit 1; }

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-identity2.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$A" "$B" "$FBK" "$RST"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
# The readiness probe above answers "SOMETHING is listening", not "OUR
# server is listening". If the port was already taken, fcwire exited at
# bind and every check below runs against the OTHER server - a gate that
# reports success while measuring nothing. Fatal, not a warning.
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

query() { # <sql> <port> <db> [node_modules-path]
    n=0
    while [ $n -lt 6 ]; do
        r=$(timeout 25 env NODE_PATH="${4:-${NODE_PATH:-}}" FC_Q="$1" FC_PORT="$2" FC_DB="$3" node -e '
          process.on("uncaughtException", () => { console.log("CONN_ERR"); process.exit(0); });
          const F=require("node-firebird");
          F.attach({host:"127.0.0.1",port:+process.env.FC_PORT,database:process.env.FC_DB,
                    user:"SYSDBA",password:"masterkey"},(e,db)=>{
            if(e){console.log("CONN_ERR");process.exit(0);}
            db.query(process.env.FC_Q,(e2,r)=>{
              if(e2){console.log("ERR "+(e2.message||"").split("\n")[0].slice(0,60));db.detach();process.exit(0);}
              const rows=Array.isArray(r)?r:(r?[r]:[]);
              // the SHAPE is part of the answer: insert-values
              // RETURNING is the type-8 OBJ singleton, a SELECT an ARR
              console.log((Array.isArray(r)?"ARR ":"OBJ ")+JSON.stringify(rows));
              db.detach();process.exit(0);});});' 2>/dev/null)
        case "$r" in
            CONN_ERR|"") n=$((n + 1)); sleep 0.3 ;;
            *) printf '%s' "$r"; return ;;
        esac
    done
    printf 'CONN_ERR'
}

both() { # <label> <sql>
    a=$(query "$2" "$PORT" "$A")
    b=$(query "$2" "$REAL" "$B")
    if [ "$a" = "$b" ]; then
        echo "OK   $1: $a"
    else
        echo "DIFF $1"
        echo "     fcwire: $a"
        echo "     engine: $b"
        fail=1
    fi
}

refused_no_write() { # <label> <sql> <count-sql>
    a=$(query "$2" "$PORT" "$A")
    b=$(query "$2" "$REAL" "$B")
    aft_a=$(query "$3" "$PORT" "$A")
    aft_b=$(query "$3" "$REAL" "$B")
    # the driver renders its message FROM THE VECTOR, so requiring the
    # two renderings equal pins fc's status vector to the engine's
    # (code AND argument) - ERR-prefix alone would let a generic
    # Dynamic SQL Error impersonate 335545137
    case "$a:$b" in
        ERR*:ERR*)
            if [ "$a" = "$b" ] && [ "$aft_a" = "$aft_b" ]; then
                echo "OK   $1 is refused by BOTH with the same vector, and neither wrote the row"
            else
                echo "DIFF $1 refusal/rows diverge:"
                echo "     fcwire: $a rows [$aft_a]"
                echo "     engine: $b rows [$aft_b]"; fail=1
            fi ;;
        *) echo "DIFF $1: fcwire [$a] engine [$b]"; fail=1 ;;
    esac
}

# --- the generator fires on an omitted column --------------------------
both "IDT omit-column insert (BY DEFAULT generates 1)" \
     "INSERT INTO IDT (V) VALUES ('a')"
both "IDT omit-column insert (generates 2)" \
     "INSERT INTO IDT (V) VALUES ('b')"
both "IDS omit-column insert (START WITH 100)" \
     "INSERT INTO IDS (V) VALUES ('p')"
both "IDS omit-column insert (INCREMENT BY 5 -> 105)" \
     "INSERT INTO IDS (V) VALUES ('q')"
both "IDA omit-column insert (ALWAYS generates 1)" \
     "INSERT INTO IDA (V) VALUES ('g')"
a=$(query "SELECT ID, V FROM IDT ORDER BY ID" "$PORT" "$A")
want='ARR [{"ID":1,"V":"a"},{"ID":2,"V":"b"}]'
if [ "$a" = "$want" ]; then
    echo "OK   the assigned ids are the engine's own (1, 2)"
else
    echo "DIFF assigned ids: got [$a] want [$want]"; fail=1
fi
a=$(query "SELECT ID, V FROM IDS ORDER BY ID" "$PORT" "$A")
want='ARR [{"ID":100,"V":"p"},{"ID":105,"V":"q"}]'
if [ "$a" = "$want" ]; then
    echo "OK   START WITH / INCREMENT BY are honoured (100, 105)"
else
    echo "DIFF START WITH/INCREMENT BY ids: got [$a] want [$want]"; fail=1
fi

# --- RETURNING the assigned id: the type-8 OBJ singleton ---------------
# probed [node-eng]: `OBJ {"ID":n}` - op_execute2, not a cursor - and
# the dispatch must hold through BOTH driver generations
for NP in "$N211" "$N214"; do
    gen=$(NODE_PATH="$NP" node -e 'console.log(require("node-firebird/package.json").version)' 2>/dev/null)
    a=$(query "INSERT INTO IDT (V) VALUES ('r$gen') RETURNING ID" "$PORT" "$A" "$NP")
    b=$(query "INSERT INTO IDT (V) VALUES ('r$gen') RETURNING ID" "$REAL" "$B" "$NP")
    if [ "$a" = "$b" ] && [ "${a#OBJ }" != "$a" ]; then
        echo "OK   node-firebird $gen: RETURNING ID answers the assigned id as ONE OBJECT: $a"
    else
        echo "DIFF RETURNING ID through node-firebird $gen"
        echo "     fcwire: $a"; echo "     engine: $b"; fail=1
    fi
done

# --- explicit value on BY DEFAULT: stored, generator NOT advanced ------
both "explicit value into a BY DEFAULT column is accepted" \
     "INSERT INTO IDT (ID, V) VALUES (50, 'z')"
both "the explicit row stored as given" \
     "SELECT ID, V FROM IDT WHERE ID = 50"

# --- the WRONG-WRITE fence: GENERATED ALWAYS refuses at prepare --------
# fc used to accept and WRITE these rows where the engine refuses at
# prepare with 335545137 - the twin row-compare is the regression fence
refused_no_write "explicit value into GENERATED ALWAYS (column list)" \
    "INSERT INTO IDA (ID, V) VALUES (50, 'z')" \
    "SELECT ID, V FROM IDA ORDER BY ID"
refused_no_write "explicit value into GENERATED ALWAYS (IMPLICIT column list)" \
    "INSERT INTO IDA VALUES (60, 'q')" \
    "SELECT ID, V FROM IDA ORDER BY ID"

# --- explicit NULL does NOT trigger generation -------------------------
refused_no_write "explicit NULL into an identity column" \
    "INSERT INTO IDT (ID, V) VALUES (NULL, 'n')" \
    "SELECT COUNT(*) FROM IDT"

# --- the ENGINE reads both files: rows and generator state -------------
kill $srv 2>/dev/null; wait $srv 2>/dev/null
strip() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
rows_of() { # <file>
    "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT ID || '|' || TRIM(V) FROM IDT ORDER BY ID;
SELECT ID || '|' || TRIM(V) FROM IDA ORDER BY ID;
SELECT ID || '|' || TRIM(V) FROM IDS ORDER BY ID;
SELECT 'g1=' || GEN_ID(RDB$1,0) || '|g2=' || GEN_ID(RDB$2,0) || '|g3=' || GEN_ID(RDB$3,0) FROM RDB$DATABASE;
SQL
}
ra=$(rows_of "$A"); rb=$(rows_of "$B")
if [ "$ra" = "$rb" ]; then
    echo "OK   ENGINE reads identical rows AND identical GEN_ID from both files"
else
    echo "DIFF engine read of the two files"
    echo "--- fcwire file:"; echo "$ra"
    echo "--- engine file:"; echo "$rb"; fail=1
fi
# and the concrete expected values, so a both-wrong bug cannot pass:
# IDT got 1,2 then two RETURNING inserts (3,4) then explicit 50 - the
# explicit value did NOT advance RDB$1, so it stays 4; IDA generated 1;
# IDS sits at 105 after its two inserts
case "$ra" in
    *"g1=4|g2=1|g3=105"*)
        echo "OK   the explicit BY DEFAULT value left RDB\$1 at 4 (not advanced)" ;;
    *) echo "DIFF generator states: $ra"; fail=1 ;;
esac

# --- engine-side structural validation of fc's file --------------------
val=$("$GFIX" -v -full -user "$U" -pas "$P" "$A" 2>&1)
if [ -z "$(printf '%s' "$val" | strip)" ]; then
    echo "OK   gfix -v -full finds nothing wrong with fc's file"
else
    echo "DIFF gfix -v -full: $val"; fail=1
fi
if "$GBAK" -b -g -user "$U" -pas "$P" "$A" "$FBK" >/tmp/fc-idn2-backup.log 2>&1; then
    echo "OK   gbak backs up the file fire-crab wrote"
else
    echo "DIFF gbak backup"; cat /tmp/fc-idn2-backup.log; fail=1
fi
"$GBAK" -c -user "$U" -pas "$P" "$FBK" "$RST" >/tmp/fc-idn2-restore.log 2>&1
rc=$?
if [ $rc -eq 0 ] && ! grep -qiE "error" /tmp/fc-idn2-restore.log; then
    echo "OK   gbak RESTORES it"
else
    echo "DIFF gbak restore (exit $rc)"; grep -iE "error|cannot" /tmp/fc-idn2-restore.log | head; fail=1
fi

exit $fail
