#!/bin/bash
# ALTER TABLE ALTER COLUMN ... RESTART [WITH n] - reposition an identity.
#
# RESTART repositions an identity column's generator without touching the
# catalog: RESTART WITH n primes it to yield n next (stored n - increment); a
# bare RESTART uses the generator's RDB$INITIAL_VALUE. RDB$INITIAL_VALUE and the
# increment are unchanged - only the generator's stored value moves. A RESTART
# on a non-identity column is refused.
#
# The differential is the engine (both databases start with the same identity
# table and a plain table, written by the engine; then fire-crab RESTARTs one
# copy and the engine the other):
#   1. after RESTART WITH n, the generator row and its stored value match, and
#      RDB$INITIAL_VALUE / increment are unchanged;
#   2. after a bare RESTART, the stored value returns to start - increment;
#   3. a RESTART on a non-identity column is refused on both;
#   4. the engine applies the restart: the next insert takes the new value;
#   5. gbak round trip and gfix -v -full on fire-crab's raw file.
#
#   qa/serve-real-identityrestart.sh [port]
#
# Builds its own scratch databases.

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"; GFIX="${GFIX:-gfix}"; GBAK="${GBAK:-gbak}"
PORT="${1:-4223}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
WORK="$D/fc-idr-work.fdb"; REF="$D/fc-idr-ref.fdb"
FBK="$D/fc-idr-work.fbk"; RST="$D/fc-idr-rst.fdb"

command -v node >/dev/null 2>&1 || { echo "SKIP node not found"; exit 0; }
mkdir -p "$D"; rm -f "$WORK" "$REF" "$FBK" "$RST"

SETUP="CREATE TABLE T (ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5), N VARCHAR(3)); CREATE TABLE U (X INTEGER);"
A_WITH="ALTER TABLE T ALTER COLUMN ID RESTART WITH 100"
A_BARE="ALTER TABLE T ALTER COLUMN ID RESTART"
R_NON="ALTER TABLE U ALTER COLUMN X RESTART WITH 5"

for f in "$REF" "$WORK"; do
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL db $f"; exit 1; }
CREATE DATABASE '$f' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
$SETUP
COMMIT;
EOF
done
"$ISQL" -q -b -user "$U" -pas "$P" "$REF" >/dev/null 2>&1 <<EOF
$A_WITH;
COMMIT;
EOF
eng_non=$("$ISQL" -q -b -user "$U" -pas "$P" "$REF" 2>&1 <<EOF
$R_NON;
EOF
)

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-idr.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$WORK" "$REF" "$FBK" "$RST"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
# The readiness probe above answers "SOMETHING is listening", not "OUR
# server is listening". If the port was already taken, fcwire exited at
# bind and every check below runs against the OTHER server - a gate that
# reports success while measuring nothing. Fatal, not a warning.
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

strip() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
node_once() {
    FC_DB="$WORK" FC_PORT="$PORT" FC_Q="$1" timeout 15 node -e '
      process.on("uncaughtException",()=>{console.log("CONN_ERR");process.exit(1);});
      const F=require("node-firebird");
      F.attach({host:"127.0.0.1",port:+process.env.FC_PORT,database:process.env.FC_DB,
                user:"SYSDBA",password:"masterkey"},(e,db)=>{
        if(e){console.log("CONN_ERR");process.exit(1);}
        db.query(process.env.FC_Q,(e2,r)=>{
          console.log(e2?("ERR "+(e2.message||"").split("\n")[0]):"OK");
          db.detach();process.exit(0);});
      });' 2>/dev/null
}
node_run() {
    n=0
    while [ $n -lt 10 ]; do
        r=$(node_once "$1")
        case "$r" in
            *CONN_ERR*|"") n=$((n + 1)); sleep 0.3 ;;
            *) printf '%s' "$r" | strip; return ;;
        esac
    done
    echo CONN_ERR
}

fail=0
check() { # <label> <got> <want>
    if [ "$2" = "$3" ]; then echo "OK   $1"; else
        echo "DIFF $1"; echo "     want: $3"; echo "     got:  $2"; fail=1; fi
}
genq() { # <file>
    "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT 'init='||RDB$INITIAL_VALUE||'|inc='||RDB$GENERATOR_INCREMENT||'|stored='||GEN_ID(RDB$1,0)
  FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='RDB$1';
SQL
}

check "fire-crab: RESTART WITH 100" "$(node_run "$A_WITH")" "OK"
r=$(node_run "$R_NON")
case "$r" in ERR*) echo "OK   RESTART on a non-identity column is refused" ;;
    *) echo "DIFF non-identity RESTART accepted"; echo "     $r"; fail=1 ;; esac
case "$eng_non" in *[Ff]ailed*|*[Ee]rror*) echo "OK   the engine refuses the non-identity RESTART too" ;;
    *) echo "DIFF engine did not refuse"; echo "     $eng_non"; fail=1 ;; esac

check "after RESTART WITH 100, the generator matches (stored 95, init/inc kept)" "$(genq "$WORK")" "$(genq "$REF")"
case "$(genq "$WORK")" in
    *"init=10|inc=5|stored=95"*) echo "OK   RDB\$INITIAL_VALUE and increment are unchanged; stored is 100-5" ;;
    *) echo "DIFF the restart did not land as expected"; echo "     $(genq "$WORK")"; fail=1 ;;
esac

# the engine applies it: next insert takes 100
"$ISQL" -q -b -user "$U" -pas "$P" "$WORK" >/dev/null 2>&1 <<'SQL'
INSERT INTO T (N) VALUES ('a');
COMMIT;
SQL
check "the engine's next insert takes the restarted value (ID=100)" \
      "$("$ISQL" -q -b -user "$U" -pas "$P" "$WORK" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT ID FROM T;
SQL
)" "100"

# bare RESTART -> stored = start - increment = 5
check "fire-crab: bare RESTART" "$(node_run "$A_BARE")" "OK"
kill $srv 2>/dev/null; wait $srv 2>/dev/null
"$ISQL" -q -b -user "$U" -pas "$P" "$REF" >/dev/null 2>&1 <<EOF
$A_BARE;
COMMIT;
EOF
check "after a bare RESTART, the stored value returns to start - increment (5)" "$(genq "$WORK")" "$(genq "$REF")"
case "$(genq "$WORK")" in *"stored=5"*) echo "OK   the bare RESTART primes the generator from RDB\$INITIAL_VALUE" ;;
    *) echo "DIFF bare RESTART wrong"; echo "     $(genq "$WORK")"; fail=1 ;; esac

# gbak and gfix
if "$GBAK" -b -g -user "$U" -pas "$P" "$WORK" "$FBK" >/tmp/fc-idr-backup.log 2>&1; then
    echo "OK   gbak backs up the database fire-crab wrote"
else
    echo "DIFF gbak backup"; cat /tmp/fc-idr-backup.log; fail=1
fi
"$GBAK" -c -user "$U" -pas "$P" "$FBK" "$RST" >/tmp/fc-idr-restore.log 2>&1
rc=$?
if [ $rc -eq 0 ] && ! grep -qiE "error" /tmp/fc-idr-restore.log; then
    echo "OK   gbak RESTORES it"
else
    echo "DIFF gbak restore (exit $rc)"; grep -iE "error|cannot" /tmp/fc-idr-restore.log | head; fail=1
fi
valw=$("$GFIX" -v -full -user "$U" -pas "$P" "$WORK" 2>&1)
check "gfix -v -full clean (fc's raw file)" "$(printf '%s' "$valw" | strip)" ""

exit $fail
