#!/bin/bash
# ALTER TABLE ALTER COLUMN ... DROP IDENTITY - make an identity column ordinary.
#
# DROP IDENTITY clears the column's RDB$IDENTITY_TYPE and RDB$GENERATOR_NAME
# (its RDB$NULL_FLAG stays - the column remains NOT NULL), drops the implicit
# generator and its security class and privilege rows, and rebuilds the runtime
# (the identity segments 22/23 go, the not-null stays). A DROP IDENTITY on a
# non-identity column is refused.
#
# The differential is the engine (both databases start with the same identity
# table and a plain table; fire-crab ALTERs one copy, the engine the other):
#   1. after DROP IDENTITY, RDB$RELATION_FIELDS (identity type, generator, null
#      flag) and the generator / class / privilege counts match;
#   2. the RDB$RUNTIME is compared BYTE FOR BYTE (identity segments gone,
#      not-null kept);
#   3. the column is still NOT NULL (a NULL insert fails, a value inserts);
#   4. a DROP IDENTITY on a non-identity column is refused on both;
#   5. gbak round trip and gfix -v -full on fire-crab's raw file.
#
#   qa/serve-real-identitydrop.sh [port]
#
# Builds its own scratch databases.

set -u
FCWIRE="${FCWIRE:-$(dirname "$0")/../target/release/fcwire}"
ISQL="${ISQL:-isql}"; GFIX="${GFIX:-gfix}"; GBAK="${GBAK:-gbak}"
PORT="${1:-4226}"
U="${ISC_USER:-SYSDBA}"; P="${ISC_PASSWORD:-masterkey}"
D=/tmp/fbhandson
WORK="$D/fc-idd-work.fdb"; REF="$D/fc-idd-ref.fdb"
FBK="$D/fc-idd-work.fbk"; RST="$D/fc-idd-rst.fdb"

command -v node >/dev/null 2>&1 || { echo "SKIP node not found"; exit 0; }
mkdir -p "$D"; rm -f "$WORK" "$REF" "$FBK" "$RST"

SETUP="CREATE TABLE T (ID INTEGER GENERATED BY DEFAULT AS IDENTITY, N VARCHAR(3)); CREATE TABLE U (X INTEGER);"
A_DROP="ALTER TABLE T ALTER COLUMN ID DROP IDENTITY"
R_NON="ALTER TABLE U ALTER COLUMN X DROP IDENTITY"

for f in "$REF" "$WORK"; do
"$ISQL" -q -b -user "$U" -pas "$P" <<EOF || { echo "FAIL db $f"; exit 1; }
CREATE DATABASE '$f' USER '$U' PASSWORD '$P' PAGE_SIZE 8192;
$SETUP
COMMIT;
EOF
done
"$ISQL" -q -b -user "$U" -pas "$P" "$REF" >/dev/null 2>&1 <<EOF
$A_DROP;
COMMIT;
EOF
eng_non=$("$ISQL" -q -b -user "$U" -pas "$P" "$REF" 2>&1 <<EOF
$R_NON;
EOF
)

"$FCWIRE" serve "127.0.0.1:$PORT" "$U" "$P" >/tmp/fc-serve-idd.log 2>&1 &
srv=$!
trap 'kill $srv 2>/dev/null; rm -f "$WORK" "$REF" "$FBK" "$RST"' EXIT
i=0; while [ $i -lt 20 ]; do
    command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$PORT" 2>/dev/null && break
    i=$((i + 1)); sleep 0.1
done
# The readiness probe above answers "SOMETHING is listening", not "OUR
# server is listening". If the port was already taken, fcwire exited at
# bind and every check below runs against the OTHER server - a gate that
# reports success while measuring nothing. Fatal, not a warning.
kill -0 $srv 2>/dev/null || {
    echo "FAIL fcwire is not running - port $PORT already in use? (see the server log)"
    exit 1
}

strip() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }
node_once() {
    FC_DB="$WORK" FC_PORT="$PORT" FC_Q="$1" timeout 15 node -e '
      process.on("uncaughtException",()=>{console.log("CONN_ERR");process.exit(1);});
      const F=require("node-firebird");
      F.attach({host:"127.0.0.1",port:+process.env.FC_PORT,database:process.env.FC_DB,
                user:"SYSDBA",password:"masterkey"},(e,db)=>{
        if(e){console.log("CONN_ERR");process.exit(1);}
        db.query(process.env.FC_Q,(e2,r)=>{
          console.log(e2?("ERR "+(e2.message||"").split("\n")[0]):"OK");
          db.detach();process.exit(0);});
      });' 2>/dev/null
}
node_run() {
    n=0
    while [ $n -lt 10 ]; do
        r=$(node_once "$1")
        case "$r" in
            *CONN_ERR*|"") n=$((n + 1)); sleep 0.3 ;;
            *) printf '%s' "$r" | strip; return ;;
        esac
    done
    echo CONN_ERR
}

fail=0
check() { if [ "$2" = "$3" ]; then echo "OK   $1"; else
        echo "DIFF $1"; echo "     want: $3"; echo "     got:  $2"; fail=1; fi; }
metaq() { "$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF;
SELECT 'RF:idt='||COALESCE(CAST(RDB$IDENTITY_TYPE AS VARCHAR(2)),'NULL')||'|gen='||COALESCE(TRIM(RDB$GENERATOR_NAME),'NULL')||'|nf='||COALESCE(CAST(RDB$NULL_FLAG AS VARCHAR(2)),'NULL') FROM RDB$RELATION_FIELDS WHERE RDB$FIELD_NAME='ID';
SELECT 'gens='||COUNT(*) FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='RDB$1';
SELECT 'privs='||COUNT(*) FROM RDB$USER_PRIVILEGES WHERE RDB$RELATION_NAME='RDB$1';
SQL
}
rtq() { b=$("$ISQL" -q -b -user "$U" -pas "$P" "$1" 2>/dev/null <<'SQL' | grep -oE '[0-9a-f]+:[0-9a-f]+' | head -1
SET LIST ON; SELECT RDB$RUNTIME FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'T';
SQL
); [ -n "$b" ] || { echo "(none)"; return; }
    rm -f /tmp/fc-idd-rt.bin; printf 'BLOBDUMP %s /tmp/fc-idd-rt.bin;\n' "$b" | "$ISQL" -q -user "$U" -pas "$P" "$1" >/dev/null 2>&1
    od -An -tu1 -v /tmp/fc-idd-rt.bin | tr '\n' ' ' | tr -s ' ' | strip; }

check "fire-crab: DROP IDENTITY" "$(node_run "$A_DROP")" "OK"
r=$(node_run "$R_NON")
case "$r" in ERR*) echo "OK   DROP IDENTITY on a non-identity column is refused" ;;
    *) echo "DIFF non-identity DROP IDENTITY accepted"; echo "     $r"; fail=1 ;; esac
case "$eng_non" in *[Ff]ailed*|*[Ee]rror*) echo "OK   the engine refuses it too" ;;
    *) echo "DIFF engine did not refuse"; echo "     $eng_non"; fail=1 ;; esac

work_meta=$(metaq "$WORK")
check "RF identity metadata cleared, generator + privileges dropped (null flag kept)" "$work_meta" "$(metaq "$REF")"
case "$work_meta" in *"RF:idt=NULL|gen=NULL|nf=1"*"gens=0"*"privs=0"*)
        echo "OK   the column is no longer an identity but stays NOT NULL; the generator is gone" ;;
    *) echo "DIFF unexpected"; echo "     $work_meta"; fail=1 ;; esac
check "the RDB\$RUNTIME matches the engine byte for byte (identity segments gone)" "$(rtq "$WORK")" "$(rtq "$REF")"

# the column is still NOT NULL
null_ins=$("$ISQL" -q -b -user "$U" -pas "$P" "$WORK" 2>&1 <<'SQL'
INSERT INTO T (N) VALUES ('a');
SQL
)
case "$null_ins" in *[Vv]alidation*|*"*** null ***"*) echo "OK   the column is still NOT NULL (a NULL insert fails)" ;;
    *) echo "DIFF the column lost its not-null"; echo "     $null_ins"; fail=1 ;; esac
"$ISQL" -q -b -user "$U" -pas "$P" "$WORK" >/dev/null 2>&1 <<'SQL'
INSERT INTO T (ID,N) VALUES (7,'b'); COMMIT;
SQL
check "a plain value inserts now (no auto-generation)" \
      "$("$ISQL" -q -b -user "$U" -pas "$P" "$WORK" 2>&1 <<'SQL' | strip | grep -v '^$'
SET HEADING OFF; SELECT ID FROM T;
SQL
)" "7"

if "$GBAK" -b -g -user "$U" -pas "$P" "$WORK" "$FBK" >/tmp/fc-idd-backup.log 2>&1; then
    echo "OK   gbak backs up the database fire-crab wrote"
else echo "DIFF gbak backup"; cat /tmp/fc-idd-backup.log; fail=1; fi
"$GBAK" -c -user "$U" -pas "$P" "$FBK" "$RST" >/tmp/fc-idd-restore.log 2>&1
rc=$?
if [ $rc -eq 0 ] && ! grep -qiE "error" /tmp/fc-idd-restore.log; then echo "OK   gbak RESTORES it"
else echo "DIFF gbak restore (exit $rc)"; grep -iE "error|cannot" /tmp/fc-idd-restore.log | head; fail=1; fi
valw=$("$GFIX" -v -full -user "$U" -pas "$P" "$WORK" 2>&1)
check "gfix -v -full clean (fc's raw file)" "$(printf '%s' "$valw" | strip)" ""
exit $fail
